// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native.Backends;

/// <summary>
/// Gamepad selection automatically starts in AutoFirst mode, picking first available SDL_Gamepad. You may override this.
/// When using manual mode, caller is responsible for opening/closing gamepad.
/// </summary>
public enum GamepadMode
{
    AutoFirst = 0,
    AutoAll = 1,
    Manual = 2
}
