// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;
using static Sdl3Sharp.Native.Gpu;

namespace SdlSharp.ImGui.Native.Backends;

/// <summary>
/// - Remember to set ColorTargetFormat to the correct format. If you're rendering to the swapchain, call SDL_GetGPUSwapchainTextureFormat() to query the right value
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct GpuInitInfo
{
    public SDL_GPUDevice* Device;

    public SDL_GPUTextureFormat ColorTargetFormat;

    public SDL_GPUSampleCount MSAASamples;

    /// <summary>
    /// Only used in multi-viewports mode.
    /// </summary>
    public SDL_GPUSwapchainComposition SwapchainComposition;

    /// <summary>
    /// Only used in multi-viewports mode.
    /// </summary>
    public SDL_GPUPresentMode PresentMode;
}
