// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;
using static Sdl3Sharp.Native.Render;

namespace Sdl3Sharp.ImGui.Native.Backends;

/// <summary>
/// [BETA] Selected render state data shared with callbacks.
/// This is temporarily stored in GetPlatformIO().Renderer_RenderState during the ImGui_ImplSDLRenderer3_RenderDrawData() call.
/// (Please open an issue if you feel you need access to more data)
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiSdl3RendererRenderState
{
    public SDL_Renderer* Renderer;
}
