// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;
using static Sdl3Sharp.Native.Events;
using static Sdl3Sharp.Native.Gamepad;
using static Sdl3Sharp.Native.Render;
using static Sdl3Sharp.Native.Video;

namespace Sdl3Sharp.ImGui.Native.Backends;

internal static unsafe partial class ImGuiSdl3
{
    #region General

    [LibraryImport(Common.ImGuiNative, EntryPoint = "cImGui_ImplSDL3_InitForSDLRenderer")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool InitForSDLRenderer(SDL_Window* window, SDL_Renderer* renderer);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "cImGui_ImplSDL3_InitForSDLGPU")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool InitForSDLGPU(SDL_Window* window);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "cImGui_ImplSDL3_Shutdown")]
    public static partial void Shutdown();

    [LibraryImport(Common.ImGuiNative, EntryPoint = "cImGui_ImplSDL3_NewFrame")]
    public static partial void NewFrame();

    [LibraryImport(Common.ImGuiNative, EntryPoint = "cImGui_ImplSDL3_ProcessEvent")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool ProcessEvent(SDL_Event* @event);

    /// <summary>
    /// Implied manual_gamepads_array = nullptr, manual_gamepads_count = -1
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "cImGui_ImplSDL3_SetGamepadMode")]
    public static partial void SetGamepadMode(ImGui_ImplSDL3_GamepadMode mode);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "cImGui_ImplSDL3_SetGamepadModeEx")]
    public static partial void SetGamepadModeEx(ImGui_ImplSDL3_GamepadMode mode, nint manual_gamepads_array, int manual_gamepads_count);

    #endregion

}
