using System.Text;

namespace Sdl3Sharp.ImGui.Generator;

/// <summary>
/// Helper class for writing formatted C# code.
/// </summary>
public sealed class CodeWriter
{
    private readonly StringBuilder _sb = new();
    private int _indentLevel;
    private const string IndentString = "    ";

    public void AppendLine()
    {
        _ = _sb.AppendLine();
    }

    public void AppendLine(string line)
    {
        if (string.IsNullOrEmpty(line))
        {
            _ = _sb.AppendLine();
            return;
        }

        for (var i = 0; i < _indentLevel; i++)
        {
            _ = _sb.Append(IndentString);
        }

        _ = _sb.AppendLine(line);
    }

    public void Append(string text)
    {
        _ = _sb.Append(text);
    }

    public void OpenBrace()
    {
        AppendLine("{");
        _indentLevel++;
    }

    public void CloseBrace(bool withSemicolon = false)
    {
        _indentLevel--;
        AppendLine(withSemicolon ? "};" : "}");
    }

    public void Indent()
    {
        _indentLevel++;
    }

    public void Unindent()
    {
        _indentLevel--;
    }

    public override string ToString()
    {
        return _sb.ToString();
    }

    /// <summary>
    /// Writes the standard file header.
    /// </summary>
    public void WriteFileHeader()
    {
        AppendLine("// <auto-generated>");
        AppendLine("// This file was generated by Sdl3Sharp.ImGui.Generator");
        AppendLine("// Do not modify this file directly.");
        AppendLine("// </auto-generated>");
        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();
    }

    /// <summary>
    /// Writes a summary XML doc comment.
    /// </summary>
    public void WriteSummary(string? summary)
    {
        if (string.IsNullOrWhiteSpace(summary))
        {
            return;
        }

        // Clean up the comment
        summary = summary.Trim();
        if (summary.StartsWith("//"))
        {
            summary = summary[2..].Trim();
        }

        AppendLine("/// <summary>");
        AppendLine($"/// {EscapeXml(summary)}");
        AppendLine("/// </summary>");
    }

    /// <summary>
    /// Writes XML doc comments from the attached comment.
    /// </summary>
    public void WriteDocComment(Comments? comments)
    {
        if (comments == null)
        {
            return;
        }

        var lines = new List<string>();

        if (comments.Preceding != null)
        {
            foreach (var line in comments.Preceding)
            {
                var cleaned = CleanComment(line);
                if (!string.IsNullOrWhiteSpace(cleaned))
                {
                    lines.Add(cleaned);
                }
            }
        }

        if (!string.IsNullOrWhiteSpace(comments.Attached))
        {
            var cleaned = CleanComment(comments.Attached);
            if (!string.IsNullOrWhiteSpace(cleaned))
            {
                lines.Add(cleaned);
            }
        }

        if (lines.Count == 0)
        {
            return;
        }

        AppendLine("/// <summary>");
        foreach (var line in lines)
        {
            AppendLine($"/// {EscapeXml(line)}");
        }

        AppendLine("/// </summary>");
    }

    private static string CleanComment(string comment)
    {
        comment = comment.Trim();
        if (comment.StartsWith("//"))
        {
            comment = comment[2..].Trim();
        }

        return comment;
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}