using Sdl3Sharp.ImGui.Generator;

// Determine paths
var baseDir = FindSolutionRoot();
var dearBindingsDir = Path.Combine(baseDir, "src", "Sdl3Sharp.ImGui.Native", "dear_bindings");
var outputDir = Path.Combine(baseDir, "src", "Sdl3Sharp.ImGui");

Console.WriteLine($"Solution root: {baseDir}");
Console.WriteLine($"Dear Bindings dir: {dearBindingsDir}");
Console.WriteLine($"Output dir: {outputDir}");

// Clean and recreate output directories
if (Directory.Exists(outputDir))
{
    foreach (var file in Directory.GetFiles(outputDir, "*.cs", SearchOption.AllDirectories))
    {
        File.Delete(file);
    }
}

Directory.CreateDirectory(outputDir);
Directory.CreateDirectory(Path.Combine(outputDir, "Backends"));

// Write shared native library constants
var commonContent = $$"""
    // <auto-generated>
    // This file was generated by Sdl3Sharp.ImGui.Generator
    // Do not modify this file directly.
    // </auto-generated>

    namespace Sdl3Sharp.ImGui.Native;

    /// <summary>
    /// Shared constants for native library interop.
    /// </summary>
    internal static class Common
    {
        /// <summary>
        /// The name of the native ImGui library.
        /// </summary>
        public const string ImGuiNative = "Sdl3Sharp.ImGui.Native";
    }
    """;
File.WriteAllText(Path.Combine(outputDir, "Common.cs"), commonContent);

TypeMapper mainTypes = HeaderGenerator.Generate(
    Path.Combine(dearBindingsDir, "dcimgui.json"),
    "Sdl3Sharp.ImGui.Native",
    outputDir,
    "ImGui",
    [],
    null);

// Load backend JSONs
var backendFiles = new List<(string Name, string HeaderPath, HashSet<string> ExcludedFunctions)>
{
    ("ImGuiSdl3", Path.Combine(dearBindingsDir, "backends", "dcimgui_impl_sdl3.json"), [
        "cImGui_ImplSDL3_InitForOpenGL",
        "cImGui_ImplSDL3_InitForVulkan",
        "cImGui_ImplSDL3_InitForD3D",
        "cImGui_ImplSDL3_InitForMetal",
        "cImGui_ImplSDL3_InitForOther",
    ]),
    ("ImGuiSdl3Gpu", Path.Combine(dearBindingsDir, "backends", "dcimgui_impl_sdlgpu3.json"), []),
    ("ImGuiSdl3Renderer", Path.Combine(dearBindingsDir, "backends", "dcimgui_impl_sdlrenderer3.json"), []),
};

foreach ((var name, var headerPath, HashSet<string> excludedFunctions) in backendFiles)
{
    _ = HeaderGenerator.Generate(
        headerPath,
        "Sdl3Sharp.ImGui.Native.Backends",
        Path.Combine(outputDir, "Backends"),
        name,
        excludedFunctions,
        mainTypes);
}

// === Helper Functions ===

static string FindSolutionRoot()
{
    var dir = Directory.GetCurrentDirectory();

    // Walk up until we find the .slnx file
    while (dir != null)
    {
        if (Directory.GetFiles(dir, "*.slnx").Length > 0 ||
            Directory.GetFiles(dir, "*.sln").Length > 0)
        {
            return dir;
        }

        dir = Directory.GetParent(dir)?.FullName;
    }

    throw new InvalidOperationException(
        "Could not find solution root. Please run from the solution directory or a project directory.");
}