<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<SdlVersion>3</SdlVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SdlSharp.Redist" Version="$(SdlRedistVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Sdl3Sharp.ImGui\Sdl3Sharp.ImGui.csproj" />
		<ProjectReference Include="..\Sdl3Sharp\Sdl3Sharp.csproj" />
	</ItemGroup>

</Project>
