namespace SdlSharp.Input;

/// <summary>
/// Virtual key code, dependent on the current keyboard layout.
/// </summary>
public enum Keycode : uint
{
    Unknown = (uint)Native.SDL_Keycode.SDLK_UNKNOWN,
    Return = (uint)Native.SDL_Keycode.SDLK_RETURN,
    Escape = (uint)Native.SDL_Keycode.SDLK_ESCAPE,
    Backspace = (uint)Native.SDL_Keycode.SDLK_BACKSPACE,
    Tab = (uint)Native.SDL_Keycode.SDLK_TAB,
    Space = (uint)Native.SDL_Keycode.SDLK_SPACE,
    Comma = (uint)Native.SDL_Keycode.SDLK_COMMA,
    Minus = (uint)Native.SDL_Keycode.SDLK_MINUS,
    Period = (uint)Native.SDL_Keycode.SDLK_PERIOD,
    Slash = (uint)Native.SDL_Keycode.SDLK_SLASH,
    Num0 = (uint)Native.SDL_Keycode.SDLK_0,
    Num1 = (uint)Native.SDL_Keycode.SDLK_1,
    Num2 = (uint)Native.SDL_Keycode.SDLK_2,
    Num3 = (uint)Native.SDL_Keycode.SDLK_3,
    Num4 = (uint)Native.SDL_Keycode.SDLK_4,
    Num5 = (uint)Native.SDL_Keycode.SDLK_5,
    Num6 = (uint)Native.SDL_Keycode.SDLK_6,
    Num7 = (uint)Native.SDL_Keycode.SDLK_7,
    Num8 = (uint)Native.SDL_Keycode.SDLK_8,
    Num9 = (uint)Native.SDL_Keycode.SDLK_9,
    Semicolon = (uint)Native.SDL_Keycode.SDLK_SEMICOLON,
    Equals = (uint)Native.SDL_Keycode.SDLK_EQUALS,
    LeftBracket = (uint)Native.SDL_Keycode.SDLK_LEFTBRACKET,
    Backslash = (uint)Native.SDL_Keycode.SDLK_BACKSLASH,
    RightBracket = (uint)Native.SDL_Keycode.SDLK_RIGHTBRACKET,
    Grave = (uint)Native.SDL_Keycode.SDLK_GRAVE,
    A = (uint)Native.SDL_Keycode.SDLK_A,
    B = (uint)Native.SDL_Keycode.SDLK_B,
    C = (uint)Native.SDL_Keycode.SDLK_C,
    D = (uint)Native.SDL_Keycode.SDLK_D,
    E = (uint)Native.SDL_Keycode.SDLK_E,
    F = (uint)Native.SDL_Keycode.SDLK_F,
    G = (uint)Native.SDL_Keycode.SDLK_G,
    H = (uint)Native.SDL_Keycode.SDLK_H,
    I = (uint)Native.SDL_Keycode.SDLK_I,
    J = (uint)Native.SDL_Keycode.SDLK_J,
    K = (uint)Native.SDL_Keycode.SDLK_K,
    L = (uint)Native.SDL_Keycode.SDLK_L,
    M = (uint)Native.SDL_Keycode.SDLK_M,
    N = (uint)Native.SDL_Keycode.SDLK_N,
    O = (uint)Native.SDL_Keycode.SDLK_O,
    P = (uint)Native.SDL_Keycode.SDLK_P,
    Q = (uint)Native.SDL_Keycode.SDLK_Q,
    R = (uint)Native.SDL_Keycode.SDLK_R,
    S = (uint)Native.SDL_Keycode.SDLK_S,
    T = (uint)Native.SDL_Keycode.SDLK_T,
    U = (uint)Native.SDL_Keycode.SDLK_U,
    V = (uint)Native.SDL_Keycode.SDLK_V,
    W = (uint)Native.SDL_Keycode.SDLK_W,
    X = (uint)Native.SDL_Keycode.SDLK_X,
    Y = (uint)Native.SDL_Keycode.SDLK_Y,
    Z = (uint)Native.SDL_Keycode.SDLK_Z,
    Delete = (uint)Native.SDL_Keycode.SDLK_DELETE,
    CapsLock = (uint)Native.SDL_Keycode.SDLK_CAPSLOCK,
    F1 = (uint)Native.SDL_Keycode.SDLK_F1,
    F2 = (uint)Native.SDL_Keycode.SDLK_F2,
    F3 = (uint)Native.SDL_Keycode.SDLK_F3,
    F4 = (uint)Native.SDL_Keycode.SDLK_F4,
    F5 = (uint)Native.SDL_Keycode.SDLK_F5,
    F6 = (uint)Native.SDL_Keycode.SDLK_F6,
    F7 = (uint)Native.SDL_Keycode.SDLK_F7,
    F8 = (uint)Native.SDL_Keycode.SDLK_F8,
    F9 = (uint)Native.SDL_Keycode.SDLK_F9,
    F10 = (uint)Native.SDL_Keycode.SDLK_F10,
    F11 = (uint)Native.SDL_Keycode.SDLK_F11,
    F12 = (uint)Native.SDL_Keycode.SDLK_F12,
    PrintScreen = (uint)Native.SDL_Keycode.SDLK_PRINTSCREEN,
    ScrollLock = (uint)Native.SDL_Keycode.SDLK_SCROLLLOCK,
    Pause = (uint)Native.SDL_Keycode.SDLK_PAUSE,
    Insert = (uint)Native.SDL_Keycode.SDLK_INSERT,
    Home = (uint)Native.SDL_Keycode.SDLK_HOME,
    PageUp = (uint)Native.SDL_Keycode.SDLK_PAGEUP,
    End = (uint)Native.SDL_Keycode.SDLK_END,
    PageDown = (uint)Native.SDL_Keycode.SDLK_PAGEDOWN,
    Right = (uint)Native.SDL_Keycode.SDLK_RIGHT,
    Left = (uint)Native.SDL_Keycode.SDLK_LEFT,
    Down = (uint)Native.SDL_Keycode.SDLK_DOWN,
    Up = (uint)Native.SDL_Keycode.SDLK_UP,
    LCtrl = (uint)Native.SDL_Keycode.SDLK_LCTRL,
    LShift = (uint)Native.SDL_Keycode.SDLK_LSHIFT,
    LAlt = (uint)Native.SDL_Keycode.SDLK_LALT,
    LGui = (uint)Native.SDL_Keycode.SDLK_LGUI,
    RCtrl = (uint)Native.SDL_Keycode.SDLK_RCTRL,
    RShift = (uint)Native.SDL_Keycode.SDLK_RSHIFT,
    RAlt = (uint)Native.SDL_Keycode.SDLK_RALT,
    RGui = (uint)Native.SDL_Keycode.SDLK_RGUI,
}

/// <summary>
/// Key modifier flags.
/// </summary>
[Flags]
public enum KeyModifiers : ushort
{
    None = (ushort)Native.SDL_Keymod.SDL_KMOD_NONE,
    LShift = (ushort)Native.SDL_Keymod.SDL_KMOD_LSHIFT,
    RShift = (ushort)Native.SDL_Keymod.SDL_KMOD_RSHIFT,
    LCtrl = (ushort)Native.SDL_Keymod.SDL_KMOD_LCTRL,
    RCtrl = (ushort)Native.SDL_Keymod.SDL_KMOD_RCTRL,
    LAlt = (ushort)Native.SDL_Keymod.SDL_KMOD_LALT,
    RAlt = (ushort)Native.SDL_Keymod.SDL_KMOD_RALT,
    LGui = (ushort)Native.SDL_Keymod.SDL_KMOD_LGUI,
    RGui = (ushort)Native.SDL_Keymod.SDL_KMOD_RGUI,
    Num = (ushort)Native.SDL_Keymod.SDL_KMOD_NUM,
    Caps = (ushort)Native.SDL_Keymod.SDL_KMOD_CAPS,
    Mode = (ushort)Native.SDL_Keymod.SDL_KMOD_MODE,
    Scroll = (ushort)Native.SDL_Keymod.SDL_KMOD_SCROLL,
    Ctrl = LCtrl | RCtrl,
    Shift = LShift | RShift,
    Alt = LAlt | RAlt,
    Gui = LGui | RGui,
}
