// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Shared constants for native library interop.
/// </summary>
internal static class Common
{
    /// <summary>
    /// The name of the native ImGui library.
    /// </summary>
    public const string ImGuiNative = "Sdl3Sharp.ImGui.Native";
}