// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Draw command list
/// This is the low-level list of polygons that ImGui:: functions are filling. At the end of the frame,
/// all command lists are passed to your ImGuiIO::RenderDrawListFn function for rendering.
/// Each dear imgui window contains its own ImDrawList. You can use ImGui::GetWindowDrawList() to
/// access the current window draw list and draw custom primitives.
/// You can interleave normal ImGui:: calls and adding primitives to the current draw list.
/// In single viewport mode, top-left is == GetMainViewport()-&gt;Pos (generally 0,0), bottom-right is == GetMainViewport()-&gt;Pos+Size (generally io.DisplaySize).
/// You are totally free to apply whatever transformation matrix you want to the data (depending on the use of the transformation you may want to apply it to ClipRect as well!)
/// Important: Primitives are always added to the list and not culled (culling is done at higher-level by ImGui:: functions), if you use this API a lot consider coarse culling your drawn objects.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImDrawList
{
    /// <summary>
    /// This is what you have to render
    /// Draw commands. Typically 1 command = 1 GPU draw call, unless the command is a callback.
    /// </summary>
    public ImVector_ImDrawCmd CmdBuffer;

    /// <summary>
    /// Index buffer. Each command consume ImDrawCmd::ElemCount of those
    /// </summary>
    public ImVector_ImDrawIdx IdxBuffer;

    /// <summary>
    /// Vertex buffer.
    /// </summary>
    public ImVector_ImDrawVert VtxBuffer;

    /// <summary>
    /// Flags, you may poke into these to adjust anti-aliasing settings per-primitive.
    /// </summary>
    public ImDrawListFlags Flags;

    /// <summary>
    /// [Internal, used while building lists]
    /// [Internal] generally == VtxBuffer.Size unless we are past 64K vertices, in which case this gets reset to 0.
    /// </summary>
    public uint VtxCurrentIdx;

    /// <summary>
    /// Pointer to shared draw data (you can use ImGui::GetDrawListSharedData() to get the one from current ImGui context)
    /// </summary>
    public ImDrawListSharedData* Data;

    /// <summary>
    /// [Internal] point within VtxBuffer.Data after each add command (to avoid using the ImVector&lt;&gt; operators too much)
    /// </summary>
    public ImDrawVert* VtxWritePtr;

    /// <summary>
    /// [Internal] point within IdxBuffer.Data after each add command (to avoid using the ImVector&lt;&gt; operators too much)
    /// </summary>
    public ImDrawIdx* IdxWritePtr;

    /// <summary>
    /// [Internal] current path building
    /// </summary>
    public ImVector_ImVec2 Path;

    /// <summary>
    /// [Internal] template of active commands. Fields should match those of CmdBuffer.back().
    /// </summary>
    public ImDrawCmdHeader CmdHeader;

    /// <summary>
    /// [Internal] for channels api (note: prefer using your own persistent instance of ImDrawListSplitter!)
    /// </summary>
    public ImDrawListSplitter Splitter;

    /// <summary>
    /// [Internal]
    /// </summary>
    public ImVector_ImVec4 ClipRectStack;

    /// <summary>
    /// [Internal]
    /// </summary>
    public ImVector_ImTextureRef TextureStack;

    /// <summary>
    /// [Internal]
    /// </summary>
    public ImVector_ImU8 CallbacksDataBuf;

    /// <summary>
    /// [Internal] anti-alias fringe is scaled by this value, this helps to keep things sharp while zooming at vertex buffer content
    /// </summary>
    public float FringeScale;

    /// <summary>
    /// Pointer to owner window's name for debugging
    /// </summary>
    public byte* OwnerName;

    /// <summary>
    /// Render-level scissoring. This is passed down to your render function but not used for CPU-side coarse clipping. Prefer using higher-level ImGui::PushClipRect() to affect logic (hit-testing and widget culling)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PushClipRect")]
    public static partial void PushClipRect(ImDrawList* self, ImVec2 clip_rect_min, ImVec2 clip_rect_max, [MarshalAs(UnmanagedType.U1)] bool intersect_with_current_clip_rect);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PushClipRectFullScreen")]
    public static partial void PushClipRectFullScreen(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PopClipRect")]
    public static partial void PopClipRect(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PushTexture")]
    public static partial void PushTexture(ImDrawList* self, ImTextureRef tex_ref);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PopTexture")]
    public static partial void PopTexture(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_GetClipRectMin")]
    public static partial ImVec2 GetClipRectMin(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_GetClipRectMax")]
    public static partial ImVec2 GetClipRectMax(ImDrawList* self);

    /// <summary>
    /// Primitives
    /// - Filled shapes must always use clockwise winding order. The anti-aliasing fringe depends on it. Counter-clockwise shapes will have "inward" anti-aliasing.
    /// - For rectangular primitives, "p_min" and "p_max" represent the upper-left and lower-right corners.
    /// - For circle primitives, use "num_segments == 0" to automatically calculate tessellation (preferred).
    /// In older versions (until Dear ImGui 1.77) the AddCircle functions defaulted to num_segments == 12.
    /// In future versions we will use textures to provide cheaper and higher-quality circles.
    /// Use AddNgon() and AddNgonFilled() functions if you need to guarantee a specific number of sides.
    /// Implied thickness = 1.0f
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddLine")]
    public static partial void AddLine(ImDrawList* self, ImVec2 p1, ImVec2 p2, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddLineEx")]
    public static partial void AddLine(ImDrawList* self, ImVec2 p1, ImVec2 p2, uint col, float thickness);

    /// <summary>
    /// Implied rounding = 0.0f, flags = 0, thickness = 1.0f
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddRect")]
    public static partial void AddRect(ImDrawList* self, ImVec2 p_min, ImVec2 p_max, uint col);

    /// <summary>
    /// a: upper-left, b: lower-right (== upper-left + size)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddRectEx")]
    public static partial void AddRect(ImDrawList* self, ImVec2 p_min, ImVec2 p_max, uint col, float rounding, ImDrawFlags flags, float thickness);

    /// <summary>
    /// Implied rounding = 0.0f, flags = 0
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddRectFilled")]
    public static partial void AddRectFilled(ImDrawList* self, ImVec2 p_min, ImVec2 p_max, uint col);

    /// <summary>
    /// a: upper-left, b: lower-right (== upper-left + size)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddRectFilledEx")]
    public static partial void AddRectFilled(ImDrawList* self, ImVec2 p_min, ImVec2 p_max, uint col, float rounding, ImDrawFlags flags);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddRectFilledMultiColor")]
    public static partial void AddRectFilledMultiColor(ImDrawList* self, ImVec2 p_min, ImVec2 p_max, uint col_upr_left, uint col_upr_right, uint col_bot_right, uint col_bot_left);

    /// <summary>
    /// Implied thickness = 1.0f
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddQuad")]
    public static partial void AddQuad(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddQuadEx")]
    public static partial void AddQuad(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, uint col, float thickness);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddQuadFilled")]
    public static partial void AddQuadFilled(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, uint col);

    /// <summary>
    /// Implied thickness = 1.0f
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddTriangle")]
    public static partial void AddTriangle(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddTriangleEx")]
    public static partial void AddTriangle(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, uint col, float thickness);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddTriangleFilled")]
    public static partial void AddTriangleFilled(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, uint col);

    /// <summary>
    /// Implied num_segments = 0, thickness = 1.0f
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddCircle")]
    public static partial void AddCircle(ImDrawList* self, ImVec2 center, float radius, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddCircleEx")]
    public static partial void AddCircle(ImDrawList* self, ImVec2 center, float radius, uint col, int num_segments, float thickness);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddCircleFilled")]
    public static partial void AddCircleFilled(ImDrawList* self, ImVec2 center, float radius, uint col, int num_segments);

    /// <summary>
    /// Implied thickness = 1.0f
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddNgon")]
    public static partial void AddNgon(ImDrawList* self, ImVec2 center, float radius, uint col, int num_segments);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddNgonEx")]
    public static partial void AddNgon(ImDrawList* self, ImVec2 center, float radius, uint col, int num_segments, float thickness);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddNgonFilled")]
    public static partial void AddNgonFilled(ImDrawList* self, ImVec2 center, float radius, uint col, int num_segments);

    /// <summary>
    /// Implied rot = 0.0f, num_segments = 0, thickness = 1.0f
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddEllipse")]
    public static partial void AddEllipse(ImDrawList* self, ImVec2 center, ImVec2 radius, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddEllipseEx")]
    public static partial void AddEllipse(ImDrawList* self, ImVec2 center, ImVec2 radius, uint col, float rot, int num_segments, float thickness);

    /// <summary>
    /// Implied rot = 0.0f, num_segments = 0
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddEllipseFilled")]
    public static partial void AddEllipseFilled(ImDrawList* self, ImVec2 center, ImVec2 radius, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddEllipseFilledEx")]
    public static partial void AddEllipseFilled(ImDrawList* self, ImVec2 center, ImVec2 radius, uint col, float rot, int num_segments);

    /// <summary>
    /// Implied text_end = NULL
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddText")]
    public static partial void AddText(ImDrawList* self, ImVec2 pos, uint col, byte* text_begin);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddTextEx")]
    public static partial void AddText(ImDrawList* self, ImVec2 pos, uint col, byte* text_begin, byte* text_end);

    /// <summary>
    /// Implied text_end = NULL, wrap_width = 0.0f, cpu_fine_clip_rect = NULL
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddTextImFontPtr")]
    public static partial void AddText(ImDrawList* self, ImFont* font, float font_size, ImVec2 pos, uint col, byte* text_begin);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddTextImFontPtrEx")]
    public static partial void AddText(ImDrawList* self, ImFont* font, float font_size, ImVec2 pos, uint col, byte* text_begin, byte* text_end, float wrap_width, ImVec4* cpu_fine_clip_rect);

    /// <summary>
    /// Cubic Bezier (4 control points)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddBezierCubic")]
    public static partial void AddBezierCubic(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, uint col, float thickness, int num_segments);

    /// <summary>
    /// Quadratic Bezier (3 control points)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddBezierQuadratic")]
    public static partial void AddBezierQuadratic(ImDrawList* self, ImVec2 p1, ImVec2 p2, ImVec2 p3, uint col, float thickness, int num_segments);

    /// <summary>
    /// General polygon
    /// - Only simple polygons are supported by filling functions (no self-intersections, no holes).
    /// - Concave polygon fill is more expensive than convex one: it has O(N^2) complexity. Provided as a convenience for the user but not used by the main library.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddPolyline")]
    public static partial void AddPolyline(ImDrawList* self, ImVec2* points, int num_points, uint col, ImDrawFlags flags, float thickness);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddConvexPolyFilled")]
    public static partial void AddConvexPolyFilled(ImDrawList* self, ImVec2* points, int num_points, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddConcavePolyFilled")]
    public static partial void AddConcavePolyFilled(ImDrawList* self, ImVec2* points, int num_points, uint col);

    /// <summary>
    /// Image primitives
    /// - Read FAQ to understand what ImTextureID/ImTextureRef are.
    /// - "p_min" and "p_max" represent the upper-left and lower-right corners of the rectangle.
    /// - "uv_min" and "uv_max" represent the normalized texture coordinates to use for those corners. Using (0,0)-&gt;(1,1) texture coordinates will generally display the entire texture.
    /// Implied uv_min = ImVec2(0, 0), uv_max = ImVec2(1, 1), col = IM_COL32_WHITE
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddImage")]
    public static partial void AddImage(ImDrawList* self, ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddImageEx")]
    public static partial void AddImage(ImDrawList* self, ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max, ImVec2 uv_min, ImVec2 uv_max, uint col);

    /// <summary>
    /// Implied uv1 = ImVec2(0, 0), uv2 = ImVec2(1, 0), uv3 = ImVec2(1, 1), uv4 = ImVec2(0, 1), col = IM_COL32_WHITE
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddImageQuad")]
    public static partial void AddImageQuad(ImDrawList* self, ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddImageQuadEx")]
    public static partial void AddImageQuad(ImDrawList* self, ImTextureRef tex_ref, ImVec2 p1, ImVec2 p2, ImVec2 p3, ImVec2 p4, ImVec2 uv1, ImVec2 uv2, ImVec2 uv3, ImVec2 uv4, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddImageRounded")]
    public static partial void AddImageRounded(ImDrawList* self, ImTextureRef tex_ref, ImVec2 p_min, ImVec2 p_max, ImVec2 uv_min, ImVec2 uv_max, uint col, float rounding, ImDrawFlags flags);

    /// <summary>
    /// Stateful path API, add points then finish with PathFillConvex() or PathStroke()
    /// - Important: filled shapes must always use clockwise winding order! The anti-aliasing fringe depends on it. Counter-clockwise shapes will have "inward" anti-aliasing.
    /// so e.g. 'PathArcTo(center, radius, PI * -0.5f, PI)' is ok, whereas 'PathArcTo(center, radius, PI, PI * -0.5f)' won't have correct anti-aliasing when followed by PathFillConvex().
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathClear")]
    public static partial void PathClear(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathLineTo")]
    public static partial void PathLineTo(ImDrawList* self, ImVec2 pos);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathLineToMergeDuplicate")]
    public static partial void PathLineToMergeDuplicate(ImDrawList* self, ImVec2 pos);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathFillConvex")]
    public static partial void PathFillConvex(ImDrawList* self, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathFillConcave")]
    public static partial void PathFillConcave(ImDrawList* self, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathStroke")]
    public static partial void PathStroke(ImDrawList* self, uint col, ImDrawFlags flags, float thickness);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathArcTo")]
    public static partial void PathArcTo(ImDrawList* self, ImVec2 center, float radius, float a_min, float a_max, int num_segments);

    /// <summary>
    /// Use precomputed angles for a 12 steps circle
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathArcToFast")]
    public static partial void PathArcToFast(ImDrawList* self, ImVec2 center, float radius, int a_min_of_12, int a_max_of_12);

    /// <summary>
    /// Implied num_segments = 0
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathEllipticalArcTo")]
    public static partial void PathEllipticalArcTo(ImDrawList* self, ImVec2 center, ImVec2 radius, float rot, float a_min, float a_max);

    /// <summary>
    /// Ellipse
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathEllipticalArcToEx")]
    public static partial void PathEllipticalArcTo(ImDrawList* self, ImVec2 center, ImVec2 radius, float rot, float a_min, float a_max, int num_segments);

    /// <summary>
    /// Cubic Bezier (4 control points)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathBezierCubicCurveTo")]
    public static partial void PathBezierCubicCurveTo(ImDrawList* self, ImVec2 p2, ImVec2 p3, ImVec2 p4, int num_segments);

    /// <summary>
    /// Quadratic Bezier (3 control points)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathBezierQuadraticCurveTo")]
    public static partial void PathBezierQuadraticCurveTo(ImDrawList* self, ImVec2 p2, ImVec2 p3, int num_segments);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PathRect")]
    public static partial void PathRect(ImDrawList* self, ImVec2 rect_min, ImVec2 rect_max, float rounding, ImDrawFlags flags);

    /// <summary>
    /// Advanced: Draw Callbacks
    /// - May be used to alter render state (change sampler, blending, current shader). May be used to emit custom rendering commands (difficult to do correctly, but possible).
    /// - Use special ImDrawCallback_ResetRenderState callback to instruct backend to reset its render state to the default.
    /// - Your rendering loop must check for 'UserCallback' in ImDrawCmd and call the function instead of rendering triangles. All standard backends are honoring this.
    /// - For some backends, the callback may access selected render-states exposed by the backend in a ImGui_ImplXXXX_RenderState structure pointed to by platform_io.Renderer_RenderState.
    /// - IMPORTANT: please be mindful of the different level of indirection between using size==0 (copying argument) and using size&gt;0 (copying pointed data into a buffer).
    /// - If userdata_size == 0: we copy/store the 'userdata' argument as-is. It will be available unmodified in ImDrawCmd::UserCallbackData during render.
    /// - If userdata_size &gt; 0,  we copy/store 'userdata_size' bytes pointed to by 'userdata'. We store them in a buffer stored inside the drawlist. ImDrawCmd::UserCallbackData will point inside that buffer so you have to retrieve data from there. Your callback may need to use ImDrawCmd::UserCallbackDataSize if you expect dynamically-sized data.
    /// - Support for userdata_size &gt; 0 was added in v1.91.4, October 2024. So earlier code always only allowed to copy/store a simple void*.
    /// Implied userdata_size = 0
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddCallback")]
    public static partial void AddCallback(ImDrawList* self, delegate* unmanaged[Cdecl]<ImDrawList*, ImDrawCmd*, void> callback, void* userdata);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddCallbackEx")]
    public static partial void AddCallback(ImDrawList* self, delegate* unmanaged[Cdecl]<ImDrawList*, ImDrawCmd*, void> callback, void* userdata, nuint userdata_size);

    /// <summary>
    /// Advanced: Miscellaneous
    /// This is useful if you need to forcefully create a new draw call (to allow for dependent rendering / blending). Otherwise primitives are merged into the same draw-call as much as possible
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_AddDrawCmd")]
    public static partial void AddDrawCmd(ImDrawList* self);

    /// <summary>
    /// Create a clone of the CmdBuffer/IdxBuffer/VtxBuffer. For multi-threaded rendering, consider using `imgui_threaded_rendering` from https://github.com/ocornut/imgui_club instead.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_CloneOutput")]
    public static partial ImDrawList* CloneOutput(ImDrawList* self);

    /// <summary>
    /// Advanced: Channels
    /// - Use to split render into layers. By switching channels to can render out-of-order (e.g. submit FG primitives before BG primitives)
    /// - Use to minimize draw calls (e.g. if going back-and-forth between multiple clipping rectangles, prefer to append into separate channels then merge at the end)
    /// - This API shouldn't have been in ImDrawList in the first place!
    /// Prefer using your own persistent instance of ImDrawListSplitter as you can stack them.
    /// Using the ImDrawList::ChannelsXXXX you cannot stack a split over another.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_ChannelsSplit")]
    public static partial void ChannelsSplit(ImDrawList* self, int count);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_ChannelsMerge")]
    public static partial void ChannelsMerge(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_ChannelsSetCurrent")]
    public static partial void ChannelsSetCurrent(ImDrawList* self, int n);

    /// <summary>
    /// Advanced: Primitives allocations
    /// - We render triangles (three vertices)
    /// - All primitives needs to be reserved via PrimReserve() beforehand.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimReserve")]
    public static partial void PrimReserve(ImDrawList* self, int idx_count, int vtx_count);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimUnreserve")]
    public static partial void PrimUnreserve(ImDrawList* self, int idx_count, int vtx_count);

    /// <summary>
    /// Axis aligned rectangle (composed of two triangles)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimRect")]
    public static partial void PrimRect(ImDrawList* self, ImVec2 a, ImVec2 b, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimRectUV")]
    public static partial void PrimRectUV(ImDrawList* self, ImVec2 a, ImVec2 b, ImVec2 uv_a, ImVec2 uv_b, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimQuadUV")]
    public static partial void PrimQuadUV(ImDrawList* self, ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a, ImVec2 uv_b, ImVec2 uv_c, ImVec2 uv_d, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimWriteVtx")]
    public static partial void PrimWriteVtx(ImDrawList* self, ImVec2 pos, ImVec2 uv, uint col);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimWriteIdx")]
    public static partial void PrimWriteIdx(ImDrawList* self, ImDrawIdx idx);

    /// <summary>
    /// Write vertex with unique index
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList_PrimVtx")]
    public static partial void PrimVtx(ImDrawList* self, ImVec2 pos, ImVec2 uv, uint col);

    /// <summary>
    /// [Internal helpers]
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__SetDrawListSharedData")]
    public static partial void _SetDrawListSharedData(ImDrawList* self, ImDrawListSharedData* data);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__ResetForNewFrame")]
    public static partial void _ResetForNewFrame(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__ClearFreeMemory")]
    public static partial void _ClearFreeMemory(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__PopUnusedDrawCmd")]
    public static partial void _PopUnusedDrawCmd(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__TryMergeDrawCmds")]
    public static partial void _TryMergeDrawCmds(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__OnChangedClipRect")]
    public static partial void _OnChangedClipRect(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__OnChangedTexture")]
    public static partial void _OnChangedTexture(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__OnChangedVtxOffset")]
    public static partial void _OnChangedVtxOffset(ImDrawList* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__SetTexture")]
    public static partial void _SetTexture(ImDrawList* self, ImTextureRef tex_ref);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__CalcCircleAutoSegmentCount")]
    public static partial int _CalcCircleAutoSegmentCount(ImDrawList* self, float radius);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__PathArcToFastEx")]
    public static partial void _PathArcToFastEx(ImDrawList* self, ImVec2 center, float radius, int a_min_sample, int a_max_sample, int a_step);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawList__PathArcToN")]
    public static partial void _PathArcToN(ImDrawList* self, ImVec2 center, float radius, float a_min, float a_max, int num_segments);

}
