// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// -&gt; enum ImDrawTextFlags_      // Internal, do not use!
/// </summary>
/// <param name="value">The underlying ImDrawTextFlags value.</param>
public readonly struct ImDrawTextFlags(int value)
{
    /// <summary>The underlying ImDrawTextFlags value.</summary>
    public readonly int Value = value;

    /// <summary>Implicitly converts a ImDrawTextFlags to int.</summary>
    /// <param name="id">The ImDrawTextFlags to convert.</param>
    public static implicit operator int(ImDrawTextFlags id) => id.Value;

    /// <summary>Implicitly converts a int to ImDrawTextFlags.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImDrawTextFlags(int value) => new(value);
}
