// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Data shared among multiple draw lists (typically owned by parent ImGui context, but you may create one yourself)
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImDrawListSharedData
{
}
