// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// All draw data to render a Dear ImGui frame
/// (NB: the style and the naming convention here is a little inconsistent, we currently preserve them for backward compatibility purpose,
/// as this is one of the oldest structure exposed by the library! Basically, ImDrawList == CmdList)
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImDrawData
{
    /// <summary>
    /// Only valid after Render() is called and before the next NewFrame() is called.
    /// </summary>
    public bool Valid;

    /// <summary>
    /// == CmdLists.Size. (OBSOLETE: exists for legacy reasons). Number of ImDrawList* to render.
    /// </summary>
    public int CmdListsCount;

    /// <summary>
    /// For convenience, sum of all ImDrawList's IdxBuffer.Size
    /// </summary>
    public int TotalIdxCount;

    /// <summary>
    /// For convenience, sum of all ImDrawList's VtxBuffer.Size
    /// </summary>
    public int TotalVtxCount;

    /// <summary>
    /// Array of ImDrawList* to render. The ImDrawLists are owned by ImGuiContext and only pointed to from here.
    /// </summary>
    public ImVector_ImDrawListPtr CmdLists;

    /// <summary>
    /// Top-left position of the viewport to render (== top-left of the orthogonal projection matrix to use) (== GetMainViewport()-&gt;Pos for the main viewport, == (0.0) in most single-viewport applications)
    /// </summary>
    public ImVec2 DisplayPos;

    /// <summary>
    /// Size of the viewport to render (== GetMainViewport()-&gt;Size for the main viewport, == io.DisplaySize in most single-viewport applications)
    /// </summary>
    public ImVec2 DisplaySize;

    /// <summary>
    /// Amount of pixels for each unit of DisplaySize. Copied from viewport-&gt;FramebufferScale (== io.DisplayFramebufferScale for main viewport). Generally (1,1) on normal display, (2,2) on OSX with Retina display.
    /// </summary>
    public ImVec2 FramebufferScale;

    /// <summary>
    /// Viewport carrying the ImDrawData instance, might be of use to the renderer (generally not).
    /// </summary>
    public ImGuiViewport* OwnerViewport;

    /// <summary>
    /// List of textures to update. Most of the times the list is shared by all ImDrawData, has only 1 texture and it doesn't need any update. This almost always points to ImGui::GetPlatformIO().Textures[]. May be overridden or set to NULL if you want to manually update textures.
    /// </summary>
    public ImVector_ImTextureDataPtr* Textures;

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawData_Clear")]
    public static partial void Clear(ImDrawData* self);

    /// <summary>
    /// Helper to add an external draw list into an existing ImDrawData.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawData_AddDrawList")]
    public static partial void AddDrawList(ImDrawData* self, ImDrawList* draw_list);

    /// <summary>
    /// Helper to convert all buffers from indexed to non-indexed, in case you cannot render indexed. Note: this is slow and most likely a waste of resources. Always prefer indexed rendering!
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawData_DeIndexAllBuffers")]
    public static partial void DeIndexAllBuffers(ImDrawData* self);

    /// <summary>
    /// Helper to scale the ClipRect field of each ImDrawCmd. Use if your final output buffer is at a different scale than Dear ImGui expects, or if there is a difference between your window resolution and framebuffer resolution.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawData_ScaleClipRects")]
    public static partial void ScaleClipRects(ImDrawData* self, ImVec2 fb_scale);

}
