// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Default: 16-bit (for maximum compatibility with renderer backends)
/// </summary>
/// <param name="value">The underlying ImDrawIdx value.</param>
public readonly struct ImDrawIdx(ushort value)
{
    /// <summary>The underlying ImDrawIdx value.</summary>
    public readonly ushort Value = value;

    /// <summary>Implicitly converts a ImDrawIdx to ushort.</summary>
    /// <param name="id">The ImDrawIdx to convert.</param>
    public static implicit operator ushort(ImDrawIdx id) => id.Value;

    /// <summary>Implicitly converts a ushort to ImDrawIdx.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImDrawIdx(ushort value) => new(value);
}
