// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// An opaque identifier to a rectangle in the atlas. -1 when invalid.
/// The rectangle may move and UV may be invalidated, use GetCustomRect() to retrieve it.
/// </summary>
/// <param name="value">The underlying ImFontAtlasRectId value.</param>
public readonly struct ImFontAtlasRectId(int value)
{
    /// <summary>The underlying ImFontAtlasRectId value.</summary>
    public readonly int Value = value;

    /// <summary>Implicitly converts a ImFontAtlasRectId to int.</summary>
    /// <param name="id">The ImFontAtlasRectId to convert.</param>
    public static implicit operator int(ImFontAtlasRectId id) => id.Value;

    /// <summary>Implicitly converts a int to ImFontAtlasRectId.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImFontAtlasRectId(int value) => new(value);
}
