// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Load and rasterize multiple TTF/OTF fonts into a same texture. The font atlas will build a single texture holding:
/// - One or more fonts.
/// - Custom graphics data needed to render the shapes needed by Dear ImGui.
/// - Mouse cursor shapes for software cursor rendering (unless setting 'Flags |= ImFontAtlasFlags_NoMouseCursors' in the font atlas).
/// - If you don't call any AddFont*** functions, the default font embedded in the code will be loaded for you.
/// It is the rendering backend responsibility to upload texture into your graphics API:
/// - ImGui_ImplXXXX_RenderDrawData() functions generally iterate platform_io-&gt;Textures[] to create/update/destroy each ImTextureData instance.
/// - Backend then set ImTextureData's TexID and BackendUserData.
/// - Texture id are passed back to you during rendering to identify the texture. Read FAQ entry about ImTextureID/ImTextureRef for more details.
/// Legacy path:
/// - Call Build() + GetTexDataAsAlpha8() or GetTexDataAsRGBA32() to build and retrieve pixels data.
/// - Call SetTexID(my_tex_id); and pass the pointer/identifier to your texture in a format natural to your graphics API.
/// Common pitfalls:
/// - If you pass a 'glyph_ranges' array to AddFont*** functions, you need to make sure that your array persist up until the
/// atlas is build (when calling GetTexData*** or Build()). We only copy the pointer, not the data.
/// - Important: By default, AddFontFromMemoryTTF() takes ownership of the data. Even though we are not writing to it, we will free the pointer on destruction.
/// You can set font_cfg-&gt;FontDataOwnedByAtlas=false to keep ownership of your data and it won't be freed,
/// - Even though many functions are suffixed with "TTF", OTF data is supported just as well.
/// - This is an old API and it is currently awkward for those and various other reasons! We will address them in the future!
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImFontAtlas
{
    /// <summary>
    /// Input
    /// Build flags (see ImFontAtlasFlags_)
    /// </summary>
    public ImFontAtlasFlags Flags;

    /// <summary>
    /// Desired texture format (default to ImTextureFormat_RGBA32 but may be changed to ImTextureFormat_Alpha8).
    /// </summary>
    public ImTextureFormat TexDesiredFormat;

    /// <summary>
    /// FIXME: Should be called "TexPackPadding". Padding between glyphs within texture in pixels. Defaults to 1. If your rendering method doesn't rely on bilinear filtering you may set this to 0 (will also need to set AntiAliasedLinesUseTex = false).
    /// </summary>
    public int TexGlyphPadding;

    /// <summary>
    /// Minimum desired texture width. Must be a power of two. Default to 512.
    /// </summary>
    public int TexMinWidth;

    /// <summary>
    /// Minimum desired texture height. Must be a power of two. Default to 128.
    /// </summary>
    public int TexMinHeight;

    /// <summary>
    /// Maximum desired texture width. Must be a power of two. Default to 8192.
    /// </summary>
    public int TexMaxWidth;

    /// <summary>
    /// Maximum desired texture height. Must be a power of two. Default to 8192.
    /// </summary>
    public int TexMaxHeight;

    /// <summary>
    /// Store your own atlas related user-data (if e.g. you have multiple font atlas).
    /// </summary>
    public nint UserData;

    /// <summary>
    /// Latest texture identifier == TexData-&gt;GetTexRef().
    /// </summary>
    public ImTextureRef TexRef;

    /// <summary>
    /// Latest texture.
    /// </summary>
    public ImTextureData* TexData;

    private ImVector_ImTextureDataPtr _internal0; // TexList

    private bool _internal1; // Locked

    private bool _internal2; // RendererHasTextures

    private bool _internal3; // TexIsBuilt

    private bool _internal4; // TexPixelsUseColors

    private ImVec2 _internal5; // TexUvScale

    private ImVec2 _internal6; // TexUvWhitePixel

    private ImVector_ImFontPtr _internal7; // Fonts

    private ImVector_ImFontConfig _internal8; // Sources

    // TODO: Fixed array of ImVec4[IM_DRAWLIST_TEX_LINES_WIDTH_MAX+1]
    private ImVec4 __internal9_0; // TexUvLines

    private int _internal10; // TexNextUniqueID

    private int _internal11; // FontNextUniqueID

    private ImVector_ImDrawListSharedDataPtr _internal12; // DrawListSharedDatas

    private ImFontAtlasBuilder* _internal13; // Builder

    private ImFontLoader* _internal14; // FontLoader

    private byte* _internal15; // FontLoaderName

    private nint _internal16; // FontLoaderData

    private uint _internal17; // FontLoaderFlags

    private int _internal18; // RefCount

    private ImGuiContext* _internal19; // OwnerContext

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_AddFont")]
    public static partial ImFont* AddFont(ImFontAtlas* self, ImFontConfig* font_cfg);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_AddFontDefault")]
    public static partial ImFont* AddFontDefault(ImFontAtlas* self, ImFontConfig* font_cfg);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_AddFontFromFileTTF")]
    public static partial ImFont* AddFontFromFileTTF(ImFontAtlas* self, byte* filename, float size_pixels, ImFontConfig* font_cfg, ushort* glyph_ranges);

    /// <summary>
    /// Note: Transfer ownership of 'ttf_data' to ImFontAtlas! Will be deleted after destruction of the atlas. Set font_cfg-&gt;FontDataOwnedByAtlas=false to keep ownership of your data and it won't be freed.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_AddFontFromMemoryTTF")]
    public static partial ImFont* AddFontFromMemoryTTF(ImFontAtlas* self, nint font_data, int font_data_size, float size_pixels, ImFontConfig* font_cfg, ushort* glyph_ranges);

    /// <summary>
    /// 'compressed_font_data' still owned by caller. Compress with binary_to_compressed_c.cpp.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_AddFontFromMemoryCompressedTTF")]
    public static partial ImFont* AddFontFromMemoryCompressedTTF(ImFontAtlas* self, nint compressed_font_data, int compressed_font_data_size, float size_pixels, ImFontConfig* font_cfg, ushort* glyph_ranges);

    /// <summary>
    /// 'compressed_font_data_base85' still owned by caller. Compress with binary_to_compressed_c.cpp with -base85 parameter.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_AddFontFromMemoryCompressedBase85TTF")]
    public static partial ImFont* AddFontFromMemoryCompressedBase85TTF(ImFontAtlas* self, byte* compressed_font_data_base85, float size_pixels, ImFontConfig* font_cfg, ushort* glyph_ranges);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_RemoveFont")]
    public static partial void RemoveFont(ImFontAtlas* self, ImFont* font);

    /// <summary>
    /// Clear everything (input fonts, output glyphs/textures).
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_Clear")]
    public static partial void Clear(ImFontAtlas* self);

    /// <summary>
    /// Compact cached glyphs and texture.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_CompactCache")]
    public static partial void CompactCache(ImFontAtlas* self);

    /// <summary>
    /// Change font loader at runtime.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_SetFontLoader")]
    public static partial void SetFontLoader(ImFontAtlas* self, ImFontLoader* font_loader);

    /// <summary>
    /// As we are transitioning toward a new font system, we expect to obsolete those soon:
    /// [OBSOLETE] Clear input data (all ImFontConfig structures including sizes, TTF data, glyph ranges, etc.) = all the data used to build the texture and fonts.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_ClearInputData")]
    public static partial void ClearInputData(ImFontAtlas* self);

    /// <summary>
    /// [OBSOLETE] Clear input+output font data (same as ClearInputData() + glyphs storage, UV coordinates).
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_ClearFonts")]
    public static partial void ClearFonts(ImFontAtlas* self);

    /// <summary>
    /// [OBSOLETE] Clear CPU-side copy of the texture data. Saves RAM once the texture has been copied to graphics memory.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_ClearTexData")]
    public static partial void ClearTexData(ImFontAtlas* self);

    /// <summary>
    /// Since 1.92: specifying glyph ranges is only useful/necessary if your backend doesn't support ImGuiBackendFlags_RendererHasTextures!
    /// Basic Latin, Extended Latin
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_GetGlyphRangesDefault")]
    public static partial ushort* GetGlyphRangesDefault(ImFontAtlas* self);

    /// <summary>
    /// Register and retrieve custom rectangles
    /// - You can request arbitrary rectangles to be packed into the atlas, for your own purpose.
    /// - Since 1.92.0, packing is done immediately in the function call (previously packing was done during the Build call)
    /// - You can render your pixels into the texture right after calling the AddCustomRect() functions.
    /// - VERY IMPORTANT:
    /// - Texture may be created/resized at any time when calling ImGui or ImFontAtlas functions.
    /// - IT WILL INVALIDATE RECTANGLE DATA SUCH AS UV COORDINATES. Always use latest values from GetCustomRect().
    /// - UV coordinates are associated to the current texture identifier aka 'atlas-&gt;TexRef'. Both TexRef and UV coordinates are typically changed at the same time.
    /// - If you render colored output into your custom rectangles: set 'atlas-&gt;TexPixelsUseColors = true' as this may help some backends decide of preferred texture format.
    /// - Read docs/FONTS.md for more details about using colorful icons.
    /// - Note: this API may be reworked further in order to facilitate supporting e.g. multi-monitor, varying DPI settings.
    /// - (Pre-1.92 names) ------------&gt; (1.92 names)
    /// - GetCustomRectByIndex()   --&gt; Use GetCustomRect()
    /// - CalcCustomRectUV()       --&gt; Use GetCustomRect() and read uv0, uv1 fields.
    /// - AddCustomRectRegular()   --&gt; Renamed to AddCustomRect()
    /// - AddCustomRectFontGlyph() --&gt; Prefer using custom ImFontLoader inside ImFontConfig
    /// - ImFontAtlasCustomRect    --&gt; Renamed to ImFontAtlasRect
    /// Register a rectangle. Return -1 (ImFontAtlasRectId_Invalid) on error.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_AddCustomRect")]
    public static partial ImFontAtlasRectId AddCustomRect(ImFontAtlas* self, int width, int height, ImFontAtlasRect* out_r);

    /// <summary>
    /// Unregister a rectangle. Existing pixels will stay in texture until resized / garbage collected.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_RemoveCustomRect")]
    public static partial void RemoveCustomRect(ImFontAtlas* self, ImFontAtlasRectId id);

    /// <summary>
    /// Get rectangle coordinates for current texture. Valid immediately, never store this (read above)!
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontAtlas_GetCustomRect")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool GetCustomRect(ImFontAtlas* self, ImFontAtlasRectId id, ImFontAtlasRect* out_r);

}
