// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Font flags
/// (in future versions as we redesign font loading API, this will become more important and better documented. for now please consider this as internal/advanced use)
/// </summary>
[Flags]
public enum ImFontFlags
{
    None = 0,
    NoLoadError = 1 << 1 // Disable throwing an error/assert when calling AddFontXXX() with missing file/data. Calling code is expected to check AddFontXXX() return value.
}
