// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Font runtime data for a given size
/// Important: pointers to ImFontBaked are only valid for the current frame.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImFontBaked
{
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontBaked_ClearOutputData")]
    public static partial void ClearOutputData(ImFontBaked* self);

    /// <summary>
    /// Return U+FFFD glyph if requested glyph doesn't exists.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontBaked_FindGlyph")]
    public static partial ImFontGlyph* FindGlyph(ImFontBaked* self, ushort c);

    /// <summary>
    /// Return NULL if glyph doesn't exist
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontBaked_FindGlyphNoFallback")]
    public static partial ImFontGlyph* FindGlyphNoFallback(ImFontBaked* self, ushort c);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontBaked_GetCharAdvance")]
    public static partial float GetCharAdvance(ImFontBaked* self, ushort c);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontBaked_IsGlyphLoaded")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool IsGlyphLoaded(ImFontBaked* self, ushort c);

}
