// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>Opaque handle to an internal ImGui ImFontAtlasBuilder structure.</summary>
public readonly struct ImFontAtlasBuilder;
