// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Output of ImFontAtlas::GetCustomRect() when using custom rectangles.
/// Those values may not be cached/stored as they are only valid for the current value of atlas-&gt;TexRef
/// (this is in theory derived from ImTextureRect but we use separate structures for reasons)
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImFontAtlasRect
{
    /// <summary>
    /// Position (in current texture)
    /// </summary>
    public ushort X;

    /// <summary>
    /// Position (in current texture)
    /// </summary>
    public ushort Y;

    /// <summary>
    /// Size
    /// </summary>
    public ushort W;

    /// <summary>
    /// Size
    /// </summary>
    public ushort H;

    /// <summary>
    /// UV coordinates (in current texture)
    /// </summary>
    public ImVec2 Uv0;

    /// <summary>
    /// UV coordinates (in current texture)
    /// </summary>
    public ImVec2 Uv1;
}
