// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Flags for ImFontAtlas build
/// </summary>
[Flags]
public enum ImFontAtlasFlags
{
    None = 0,
    NoPowerOfTwoHeight = 1 << 0, // Don't round the height to next power of two
    NoMouseCursors = 1 << 1, // Don't build software mouse cursors into the atlas (save a little texture memory)
    NoBakedLines = 1 << 2 // Don't build thick line textures into the atlas (save a little texture memory, allow support for point/nearest filtering). The AntiAliasedLinesUseTex features uses them, otherwise they will be rendered using polygons (more expensive for CPU/GPU).
}
