// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Font runtime data and rendering
/// - ImFontAtlas automatically loads a default embedded font for you if you didn't load one manually.
/// - Since 1.92.0 a font may be rendered as any size! Therefore a font doesn't have one specific size.
/// - Use 'font-&gt;GetFontBaked(size)' to retrieve the ImFontBaked* corresponding to a given size.
/// - If you used g.Font + g.FontSize (which is frequent from the ImGui layer), you can use g.FontBaked as a shortcut, as g.FontBaked == g.Font-&gt;GetFontBaked(g.FontSize).
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImFont
{
    /// <summary>
    /// 4     // in  // Legacy base font scale (~1.0f), multiplied by the per-window font scale which you can adjust with SetWindowFontScale()
    /// </summary>
    public float Scale;

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFont_IsGlyphInFont")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool IsGlyphInFont(ImFont* self, ushort c);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFont_IsLoaded")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool IsLoaded(ImFont* self);

    /// <summary>
    /// Fill ImFontConfig::Name.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFont_GetDebugName")]
    public static partial nint GetDebugName(ImFont* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFont_CalcWordWrapPositionA")]
    public static partial nint CalcWordWrapPositionA(ImFont* self, float scale, [MarshalAs(UnmanagedType.LPUTF8Str)] string text, [MarshalAs(UnmanagedType.LPUTF8Str)] string text_end, float wrap_width);

}
