// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Helper to build glyph ranges from text/string data. Feed your application strings/characters to it then call BuildRanges().
/// This is essentially a tightly packed of vector of 64k booleans = 8KB storage.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImFontGlyphRangesBuilder
{
    /// <summary>
    /// Store 1-bit per Unicode code point (0=unused, 1=used)
    /// </summary>
    public ImVector_ImU32 UsedChars;

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontGlyphRangesBuilder_Clear")]
    public static partial void Clear(ImFontGlyphRangesBuilder* self);

    /// <summary>
    /// Get bit n in the array
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontGlyphRangesBuilder_GetBit")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool GetBit(ImFontGlyphRangesBuilder* self, nuint n);

    /// <summary>
    /// Set bit n in the array
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontGlyphRangesBuilder_SetBit")]
    public static partial void SetBit(ImFontGlyphRangesBuilder* self, nuint n);

    /// <summary>
    /// Add character
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontGlyphRangesBuilder_AddChar")]
    public static partial void AddChar(ImFontGlyphRangesBuilder* self, ushort c);

    /// <summary>
    /// Add string (each character of the UTF-8 string are added)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontGlyphRangesBuilder_AddText")]
    public static partial void AddText(ImFontGlyphRangesBuilder* self, [MarshalAs(UnmanagedType.LPUTF8Str)] string text, [MarshalAs(UnmanagedType.LPUTF8Str)] string text_end);

    /// <summary>
    /// Add ranges, e.g. builder.AddRanges(ImFontAtlas::GetGlyphRangesDefault()) to force add all of ASCII/Latin+Ext
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontGlyphRangesBuilder_AddRanges")]
    public static partial void AddRanges(ImFontGlyphRangesBuilder* self, ushort* ranges);

    /// <summary>
    /// Output new ranges (ImVector_Construct()/ImVector_Destruct() can be used to safely construct out_ranges)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImFontGlyphRangesBuilder_BuildRanges")]
    public static partial void BuildRanges(ImFontGlyphRangesBuilder* self, ImVector_ImWchar* out_ranges);

}
