// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::BeginTabBar()
/// </summary>
[Flags]
public enum ImGuiTabBarFlags
{
    None = 0,
    Reorderable = 1 << 0, // Allow manually dragging tabs to re-order them + New tabs are appended at the end of list
    AutoSelectNewTabs = 1 << 1, // Automatically select new tabs when they appear
    TabListPopupButton = 1 << 2, // Disable buttons to open the tab list popup
    NoCloseWithMiddleMouseButton = 1 << 3, // Disable behavior of closing tabs (that are submitted with p_open != NULL) with middle mouse button. You may handle this behavior manually on user's side with if (IsItemHovered() && IsMouseClicked(2)) *p_open = false.
    NoTabListScrollingButtons = 1 << 4, // Disable scrolling buttons (apply when fitting policy is ImGuiTabBarFlags_FittingPolicyScroll)
    NoTooltip = 1 << 5, // Disable tooltips when hovering a tab
    DrawSelectedOverline = 1 << 6, // Draw selected overline markers over selected tab
    FittingPolicyMixed = 1 << 7, // Shrink down tabs when they don't fit, until width is style.TabMinWidthShrink, then enable scrolling buttons.
    FittingPolicyShrink = 1 << 8, // Shrink down tabs when they don't fit
    FittingPolicyScroll = 1 << 9, // Enable scrolling buttons when tabs don't fit
    FittingPolicyResizeDown = 1 << 8 // Renamed in 1.92.2
}
