// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::IsWindowFocused()
/// </summary>
[Flags]
public enum ImGuiFocusedFlags
{
    None = 0,
    ChildWindows = 1 << 0, // Return true if any children of the window is focused
    RootWindow = 1 << 1, // Test from root window (top most parent of the current hierarchy)
    AnyWindow = 1 << 2, // Return true if any window is focused. Important: If you are trying to tell how to dispatch your low-level inputs, do NOT use this. Use 'io.WantCaptureMouse' instead! Please read the FAQ!
    NoPopupHierarchy = 1 << 3, // Do not consider popup hierarchy (do not treat popup emitter as parent of popup) (when used with _ChildWindows or _RootWindow)
    RootAndChildWindows = 3
}
