// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Callback function for ImGui::SetNextWindowSizeConstraints()
/// </summary>
/// <param name="value">The underlying function pointer.</param>
public readonly unsafe struct ImGuiSizeCallback(delegate* unmanaged[Cdecl]<ImGuiSizeCallbackData*, void> value)
{
    /// <summary>The underlying function pointer.</summary>
    public readonly delegate* unmanaged[Cdecl]<ImGuiSizeCallbackData*, void> Value = value;

    /// <summary>Implicitly converts a ImGuiSizeCallback to its underlying function pointer.</summary>
    /// <param name="callback">The ImGuiSizeCallback to convert.</param>
    public static implicit operator delegate* unmanaged[Cdecl]<ImGuiSizeCallbackData*, void>(ImGuiSizeCallback callback) => callback.Value;

    /// <summary>Implicitly converts a function pointer to ImGuiSizeCallback.</summary>
    /// <param name="value">The function pointer to convert.</param>
    public static implicit operator ImGuiSizeCallback(delegate* unmanaged[Cdecl]<ImGuiSizeCallbackData*, void> value) => new(value);
}
