// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Shared state of InputText(), passed as an argument to your callback when a ImGuiInputTextFlags_Callback* flag is used.
/// The callback function should return 0 by default.
/// Callbacks (follow a flag name and see comments in ImGuiInputTextFlags_ declarations for more details)
/// - ImGuiInputTextFlags_CallbackEdit:        Callback on buffer edit. Note that InputText() already returns true on edit + you can always use IsItemEdited(). The callback is useful to manipulate the underlying buffer while focus is active.
/// - ImGuiInputTextFlags_CallbackAlways:      Callback on each iteration
/// - ImGuiInputTextFlags_CallbackCompletion:  Callback on pressing TAB
/// - ImGuiInputTextFlags_CallbackHistory:     Callback on pressing Up/Down arrows
/// - ImGuiInputTextFlags_CallbackCharFilter:  Callback on character inputs to replace or discard them. Modify 'EventChar' to replace or discard, or return 1 in callback to discard.
/// - ImGuiInputTextFlags_CallbackResize:      Callback on buffer capacity changes request (beyond 'buf_size' parameter value), allowing the string to grow.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiInputTextCallbackData
{
    /// <summary>
    /// Parent UI context
    /// </summary>
    public ImGuiContext* Ctx;

    /// <summary>
    /// One ImGuiInputTextFlags_Callback*    // Read-only
    /// </summary>
    public ImGuiInputTextFlags EventFlag;

    /// <summary>
    /// What user passed to InputText()      // Read-only
    /// </summary>
    public ImGuiInputTextFlags Flags;

    /// <summary>
    /// What user passed to InputText()      // Read-only
    /// </summary>
    public nint UserData;

    /// <summary>
    /// Arguments for the different callback events
    /// - During Resize callback, Buf will be same as your input buffer.
    /// - However, during Completion/History/Always callback, Buf always points to our own internal data (it is not the same as your buffer)! Changes to it will be reflected into your own buffer shortly after the callback.
    /// - To modify the text buffer in a callback, prefer using the InsertChars() / DeleteChars() function. InsertChars() will take care of calling the resize callback if necessary.
    /// - If you know your edits are not going to resize the underlying buffer allocation, you may modify the contents of 'Buf[]' directly. You need to update 'BufTextLen' accordingly (0 &lt;= BufTextLen &lt; BufSize) and set 'BufDirty'' to true so InputText can update its internal state.
    /// Character input                      // Read-write   // [CharFilter] Replace character with another one, or set to zero to drop. return 1 is equivalent to setting EventChar=0;
    /// </summary>
    public ushort EventChar;

    /// <summary>
    /// Key pressed (Up/Down/TAB)            // Read-only    // [Completion,History]
    /// </summary>
    public ImGuiKey EventKey;

    /// <summary>
    /// Text buffer                          // Read-write   // [Resize] Can replace pointer / [Completion,History,Always] Only write to pointed data, don't replace the actual pointer!
    /// </summary>
    public byte* Buf;

    /// <summary>
    /// Text length (in bytes)               // Read-write   // [Resize,Completion,History,Always] Exclude zero-terminator storage. In C land: == strlen(some_text), in C++ land: string.length()
    /// </summary>
    public int BufTextLen;

    /// <summary>
    /// Buffer size (in bytes) = capacity+1  // Read-only    // [Resize,Completion,History,Always] Include zero-terminator storage. In C land: == ARRAYSIZE(my_char_array), in C++ land: string.capacity()+1
    /// </summary>
    public int BufSize;

    /// <summary>
    /// Set if you modify Buf/BufTextLen!    // Write        // [Completion,History,Always]
    /// </summary>
    public bool BufDirty;

    /// <summary>
    /// // Read-write   // [Completion,History,Always]
    /// </summary>
    public int CursorPos;

    /// <summary>
    /// // Read-write   // [Completion,History,Always] == to SelectionEnd when no selection
    /// </summary>
    public int SelectionStart;

    /// <summary>
    /// // Read-write   // [Completion,History,Always]
    /// </summary>
    public int SelectionEnd;

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiInputTextCallbackData_DeleteChars")]
    public static partial void DeleteChars(ImGuiInputTextCallbackData* self, int pos, int bytes_count);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiInputTextCallbackData_InsertChars")]
    public static partial void InsertChars(ImGuiInputTextCallbackData* self, int pos, byte* text, byte* text_end);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiInputTextCallbackData_SelectAll")]
    public static partial void SelectAll(ImGuiInputTextCallbackData* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiInputTextCallbackData_ClearSelection")]
    public static partial void ClearSelection(ImGuiInputTextCallbackData* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiInputTextCallbackData_HasSelection")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool HasSelection(ImGuiInputTextCallbackData* self);

}
