// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Data payload for Drag and Drop operations: AcceptDragDropPayload(), GetDragDropPayload()
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiPayload
{
    /// <summary>
    /// Members
    /// Data (copied and owned by dear imgui)
    /// </summary>
    public nint Data;

    /// <summary>
    /// Data size
    /// </summary>
    public int DataSize;

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiPayload_Clear")]
    public static partial void Clear(ImGuiPayload* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiPayload_IsDataType")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool IsDataType(ImGuiPayload* self, byte* type);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiPayload_IsPreview")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool IsPreview(ImGuiPayload* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiPayload_IsDelivery")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool IsDelivery(ImGuiPayload* self);

}
