// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Enumeration for PushStyleVar() / PopStyleVar() to temporarily modify the ImGuiStyle structure.
/// - The enum only refers to fields of ImGuiStyle which makes sense to be pushed/popped inside UI code.
/// During initialization or between frames, feel free to just poke into ImGuiStyle directly.
/// - Tip: Use your programming IDE navigation facilities on the names in the _second column_ below to find the actual members and their description.
/// - In Visual Studio: Ctrl+Comma ("Edit.GoToAll") can follow symbols inside comments, whereas Ctrl+F12 ("Edit.GoToImplementation") cannot.
/// - In Visual Studio w/ Visual Assist installed: Alt+G ("VAssistX.GoToImplementation") can also follow symbols inside comments.
/// - In VS Code, CLion, etc.: Ctrl+Click can follow symbols inside comments.
/// - When changing this enum, you need to update the associated internal table GStyleVarInfo[] accordingly. This is where we link enum values to members offset/type.
/// </summary>
public enum ImGuiStyleVar
{
    Alpha = 0, // float     Alpha
    DisabledAlpha = 1, // float     DisabledAlpha
    WindowPadding = 2, // ImVec2    WindowPadding
    WindowRounding = 3, // float     WindowRounding
    WindowBorderSize = 4, // float     WindowBorderSize
    WindowMinSize = 5, // ImVec2    WindowMinSize
    WindowTitleAlign = 6, // ImVec2    WindowTitleAlign
    ChildRounding = 7, // float     ChildRounding
    ChildBorderSize = 8, // float     ChildBorderSize
    PopupRounding = 9, // float     PopupRounding
    PopupBorderSize = 10, // float     PopupBorderSize
    FramePadding = 11, // ImVec2    FramePadding
    FrameRounding = 12, // float     FrameRounding
    FrameBorderSize = 13, // float     FrameBorderSize
    ItemSpacing = 14, // ImVec2    ItemSpacing
    ItemInnerSpacing = 15, // ImVec2    ItemInnerSpacing
    IndentSpacing = 16, // float     IndentSpacing
    CellPadding = 17, // ImVec2    CellPadding
    ScrollbarSize = 18, // float     ScrollbarSize
    ScrollbarRounding = 19, // float     ScrollbarRounding
    ScrollbarPadding = 20, // float     ScrollbarPadding
    GrabMinSize = 21, // float     GrabMinSize
    GrabRounding = 22, // float     GrabRounding
    ImageBorderSize = 23, // float     ImageBorderSize
    TabRounding = 24, // float     TabRounding
    TabBorderSize = 25, // float     TabBorderSize
    TabMinWidthBase = 26, // float     TabMinWidthBase
    TabMinWidthShrink = 27, // float     TabMinWidthShrink
    TabBarBorderSize = 28, // float     TabBarBorderSize
    TabBarOverlineSize = 29, // float     TabBarOverlineSize
    TableAngledHeadersAngle = 30, // float     TableAngledHeadersAngle
    TableAngledHeadersTextAlign = 31, // ImVec2  TableAngledHeadersTextAlign
    TreeLinesSize = 32, // float     TreeLinesSize
    TreeLinesRounding = 33, // float     TreeLinesRounding
    ButtonTextAlign = 34, // ImVec2    ButtonTextAlign
    SelectableTextAlign = 35, // ImVec2    SelectableTextAlign
    SeparatorTextBorderSize = 36, // float     SeparatorTextBorderSize
    SeparatorTextAlign = 37, // ImVec2    SeparatorTextAlign
    SeparatorTextPadding = 38 // ImVec2    SeparatorTextPadding
}
