// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::BeginTabItem()
/// </summary>
[Flags]
public enum ImGuiTabItemFlags
{
    None = 0,
    UnsavedDocument = 1 << 0, // Display a dot next to the title + set ImGuiTabItemFlags_NoAssumedClosure.
    SetSelected = 1 << 1, // Trigger flag to programmatically make the tab selected when calling BeginTabItem()
    NoCloseWithMiddleMouseButton = 1 << 2, // Disable behavior of closing tabs (that are submitted with p_open != NULL) with middle mouse button. You may handle this behavior manually on user's side with if (IsItemHovered() && IsMouseClicked(2)) *p_open = false.
    NoPushId = 1 << 3, // Don't call PushID()/PopID() on BeginTabItem()/EndTabItem()
    NoTooltip = 1 << 4, // Disable tooltip for the given tab
    NoReorder = 1 << 5, // Disable reordering this tab or having another tab cross over this tab
    Leading = 1 << 6, // Enforce the tab position to the left of the tab bar (after the tab list popup button)
    Trailing = 1 << 7, // Enforce the tab position to the right of the tab bar (before the scrolling buttons)
    NoAssumedClosure = 1 << 8 // Tab is selected when trying to close + closure is not immediately assumed (will wait for user to stop submitting the tab). Otherwise closure is assumed when pressing the X, so if you keep submitting the tab may reappear at end of tab bar.
}
