// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::InputText()
/// (Those are per-item flags. There are shared flags in ImGuiIO: io.ConfigInputTextCursorBlink and io.ConfigInputTextEnterKeepActive)
/// </summary>
[Flags]
public enum ImGuiInputTextFlags
{
    None = 0,
    CharsDecimal = 1 << 0, // Allow 0123456789.+-*/
    CharsHexadecimal = 1 << 1, // Allow 0123456789ABCDEFabcdef
    CharsScientific = 1 << 2, // Allow 0123456789.+-*/eE (Scientific notation input)
    CharsUppercase = 1 << 3, // Turn a..z into A..Z
    CharsNoBlank = 1 << 4, // Filter out spaces, tabs
    AllowTabInput = 1 << 5, // Pressing TAB input a '\t' character into the text field
    EnterReturnsTrue = 1 << 6, // Return 'true' when Enter is pressed (as opposed to every time the value was modified). Consider using IsItemDeactivatedAfterEdit() instead!
    EscapeClearsAll = 1 << 7, // Escape key clears content if not empty, and deactivate otherwise (contrast to default behavior of Escape to revert)
    CtrlEnterForNewLine = 1 << 8, // In multi-line mode, validate with Enter, add new line with Ctrl+Enter (default is opposite: validate with Ctrl+Enter, add line with Enter).
    ReadOnly = 1 << 9, // Read-only mode
    Password = 1 << 10, // Password mode, display all characters as '*', disable copy
    AlwaysOverwrite = 1 << 11, // Overwrite mode
    AutoSelectAll = 1 << 12, // Select entire text when first taking mouse focus
    ParseEmptyRefVal = 1 << 13, // InputFloat(), InputInt(), InputScalar() etc. only: parse empty string as zero value.
    DisplayEmptyRefVal = 1 << 14, // InputFloat(), InputInt(), InputScalar() etc. only: when value is zero, do not display it. Generally used with ImGuiInputTextFlags_ParseEmptyRefVal.
    NoHorizontalScroll = 1 << 15, // Disable following the cursor horizontally
    NoUndoRedo = 1 << 16, // Disable undo/redo. Note that input text owns the text data while active, if you want to provide your own undo/redo stack you need e.g. to call ClearActiveID().
    ElideLeft = 1 << 17, // When text doesn't fit, elide left side to ensure right side stays visible. Useful for path/filenames. Single-line only!
    CallbackCompletion = 1 << 18, // Callback on pressing TAB (for completion handling)
    CallbackHistory = 1 << 19, // Callback on pressing Up/Down arrows (for history handling)
    CallbackAlways = 1 << 20, // Callback on each iteration. User code may query cursor position, modify text buffer.
    CallbackCharFilter = 1 << 21, // Callback on character inputs to replace or discard them. Modify 'EventChar' to replace or discard, or return 1 in callback to discard.
    CallbackResize = 1 << 22, // Callback on buffer capacity changes request (beyond 'buf_size' parameter value), allowing the string to grow. Notify when the string wants to be resized (for string types which hold a cache of their Size). You will be provided a new BufSize in the callback and NEED to honor it. (see misc/cpp/imgui_stdlib.h for an example of using this)
    CallbackEdit = 1 << 23, // Callback on any edit. Note that InputText() already returns true on edit + you can always use IsItemEdited(). The callback is useful to manipulate the underlying buffer while focus is active.
    WordWrap = 1 << 24 // InputTextMultiline(): word-wrap lines that are too long.
}
