// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// [Internal]
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiTextFilter_ImGuiTextRange
{
    public byte* B;

    public byte* E;

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiTextFilter_ImGuiTextRange_empty")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool empty(ImGuiTextFilter_ImGuiTextRange* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiTextFilter_ImGuiTextRange_split")]
    public static partial void split(ImGuiTextFilter_ImGuiTextRange* self, byte separator, ImVector_ImGuiTextRange* @out);

}
