// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::Selectable()
/// </summary>
[Flags]
public enum ImGuiSelectableFlags
{
    None = 0,
    NoAutoClosePopups = 1 << 0, // Clicking this doesn't close parent popup window (overrides ImGuiItemFlags_AutoClosePopups)
    SpanAllColumns = 1 << 1, // Frame will span all columns of its container table (text will still fit in current column)
    AllowDoubleClick = 1 << 2, // Generate press events on double clicks too
    Disabled = 1 << 3, // Cannot be selected, display grayed out text
    AllowOverlap = 1 << 4, // (WIP) Hit testing to allow subsequent widgets to overlap this one
    Highlight = 1 << 5, // Make the item be displayed as if it is hovered
    SelectOnNav = 1 << 6, // Auto-select when moved into, unless Ctrl is held. Automatic when in a BeginMultiSelect() block.
    DontClosePopups = 1 << 0 // Renamed in 1.91.0
}
