// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Callback and functions types
/// Callback function for ImGui::InputText()
/// </summary>
/// <param name="value">The underlying function pointer.</param>
public readonly unsafe struct ImGuiInputTextCallback(delegate* unmanaged[Cdecl]<ImGuiInputTextCallbackData*, int> value)
{
    /// <summary>The underlying function pointer.</summary>
    public readonly delegate* unmanaged[Cdecl]<ImGuiInputTextCallbackData*, int> Value = value;

    /// <summary>Implicitly converts a ImGuiInputTextCallback to its underlying function pointer.</summary>
    /// <param name="callback">The ImGuiInputTextCallback to convert.</param>
    public static implicit operator delegate* unmanaged[Cdecl]<ImGuiInputTextCallbackData*, int>(ImGuiInputTextCallback callback) => callback.Value;

    /// <summary>Implicitly converts a function pointer to ImGuiInputTextCallback.</summary>
    /// <param name="value">The function pointer to convert.</param>
    public static implicit operator ImGuiInputTextCallback(delegate* unmanaged[Cdecl]<ImGuiInputTextCallbackData*, int> value) => new(value);
}
