// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Identify a mouse button.
/// Those values are guaranteed to be stable and we frequently use 0/1 directly. Named enums provided for convenience.
/// </summary>
public enum ImGuiMouseButton
{
    Left = 0,
    Right = 1,
    Middle = 2
}
