// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Selection request item
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImGuiSelectionRequest
{
    /// <summary>
    /// ------------------------------------------// BeginMultiSelect / EndMultiSelect
    /// ms:w, app:r     /  ms:w, app:r   // Request type. You'll most often receive 1 Clear + 1 SetRange with a single-item range.
    /// </summary>
    public ImGuiSelectionRequestType Type;

    /// <summary>
    /// ms:w, app:r     /  ms:w, app:r   // Parameter for SetAll/SetRange requests (true = select, false = unselect)
    /// </summary>
    public bool Selected;

    /// <summary>
    /// /  ms:w  app:r   // Parameter for SetRange request: +1 when RangeFirstItem comes before RangeLastItem, -1 otherwise. Useful if you want to preserve selection order on a backward Shift+Click.
    /// </summary>
    public sbyte RangeDirection;

    /// <summary>
    /// /  ms:w, app:r   // Parameter for SetRange request (this is generally == RangeSrcItem when shift selecting from top to bottom).
    /// </summary>
    public ImGuiSelectionUserData RangeFirstItem;

    /// <summary>
    /// /  ms:w, app:r   // Parameter for SetRange request (this is generally == RangeSrcItem when shift selecting from bottom to top). Inclusive!
    /// </summary>
    public ImGuiSelectionUserData RangeLastItem;
}
