// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// - Currently represents the Platform Window created by the application which is hosting our Dear ImGui windows.
/// - In 'docking' branch with multi-viewport enabled, we extend this concept to have multiple active viewports.
/// - In the future we will extend this concept further to also represent Platform Monitor and support a "no main platform window" operation mode.
/// - About Main Area vs Work Area:
/// - Main Area = entire viewport.
/// - Work Area = entire viewport minus sections used by main menu bars (for platform windows), or by task bar (for platform monitor).
/// - Windows are generally trying to stay within the Work Area of their host viewport.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiViewport
{
    /// <summary>
    /// Unique identifier for the viewport
    /// </summary>
    public ImGuiID ID;

    /// <summary>
    /// See ImGuiViewportFlags_
    /// </summary>
    public ImGuiViewportFlags Flags;

    /// <summary>
    /// Main Area: Position of the viewport (Dear ImGui coordinates are the same as OS desktop/native coordinates)
    /// </summary>
    public ImVec2 Pos;

    /// <summary>
    /// Main Area: Size of the viewport.
    /// </summary>
    public ImVec2 Size;

    /// <summary>
    /// Density of the viewport for Retina display (always 1,1 on Windows, may be 2,2 etc on macOS/iOS). This will affect font rasterizer density.
    /// </summary>
    public ImVec2 FramebufferScale;

    /// <summary>
    /// Work Area: Position of the viewport minus task bars, menus bars, status bars (&gt;= Pos)
    /// </summary>
    public ImVec2 WorkPos;

    /// <summary>
    /// Work Area: Size of the viewport minus task bars, menu bars, status bars (&lt;= Size)
    /// </summary>
    public ImVec2 WorkSize;

    /// <summary>
    /// Platform/Backend Dependent Data
    /// void* to hold higher-level, platform window handle (e.g. HWND, GLFWWindow*, SDL_Window*)
    /// </summary>
    public nint PlatformHandle;

    /// <summary>
    /// void* to hold lower-level, platform-native window handle (under Win32 this is expected to be a HWND, unused for other platforms)
    /// </summary>
    public nint PlatformHandleRaw;

    /// <summary>
    /// Helpers
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiViewport_GetCenter")]
    public static partial ImVec2 GetCenter(ImGuiViewport* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiViewport_GetWorkCenter")]
    public static partial ImVec2 GetWorkCenter(ImGuiViewport* self);

}
