// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Resizing callback data to apply custom constraint. As enabled by SetNextWindowSizeConstraints(). Callback is called during the next Begin().
/// NB: For basic min/max size constraint on each axis you don't need to use the callback! The SetNextWindowSizeConstraints() parameters are enough.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiSizeCallbackData
{
    /// <summary>
    /// Read-only.   What user passed to SetNextWindowSizeConstraints(). Generally store an integer or float in here (need reinterpret_cast&lt;&gt;).
    /// </summary>
    public void* UserData;

    /// <summary>
    /// Read-only.   Window position, for reference.
    /// </summary>
    public ImVec2 Pos;

    /// <summary>
    /// Read-only.   Current window size.
    /// </summary>
    public ImVec2 CurrentSize;

    /// <summary>
    /// Read-write.  Desired size, based on user's mouse position. Write to this field to restrain resizing.
    /// </summary>
    public ImVec2 DesiredSize;
}
