// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Access via ImGui::GetPlatformIO()
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiPlatformIO
{
    /// <summary>
    /// Optional: Access OS clipboard
    /// (default to use native Win32 clipboard on Windows, otherwise uses a private clipboard. Override to access OS clipboard on other architectures)
    /// </summary>
    public delegate* unmanaged[Cdecl]<ImGuiContext*, byte*> Platform_GetClipboardTextFn;

    public delegate* unmanaged[Cdecl]<ImGuiContext*, byte*, void> Platform_SetClipboardTextFn;

    public void* Platform_ClipboardUserData;

    /// <summary>
    /// Optional: Open link/folder/file in OS Shell
    /// (default to use ShellExecuteW() on Windows, system() on Linux/Mac. expected to return false on failure, but some platforms may always return true)
    /// </summary>
    public delegate* unmanaged[Cdecl]<ImGuiContext*, byte*, bool> Platform_OpenInShellFn;

    public void* Platform_OpenInShellUserData;

    /// <summary>
    /// Optional: Notify OS Input Method Editor of the screen position of your cursor for text input position (e.g. when using Japanese/Chinese IME on Windows)
    /// (default to use native imm32 api on Windows)
    /// </summary>
    public delegate* unmanaged[Cdecl]<ImGuiContext*, ImGuiViewport*, ImGuiPlatformImeData*, void> Platform_SetImeDataFn;

    public void* Platform_ImeUserData;

    /// <summary>
    /// Optional: Platform locale
    /// [Experimental] Configure decimal point e.g. '.' or ',' useful for some languages (e.g. German), generally pulled from *localeconv()-&gt;decimal_point
    /// '.'
    /// </summary>
    public ushort Platform_LocaleDecimalPoint;

    /// <summary>
    /// Optional: Maximum texture size supported by renderer (used to adjust how we size textures). 0 if not known.
    /// </summary>
    public int Renderer_TextureMaxWidth;

    public int Renderer_TextureMaxHeight;

    /// <summary>
    /// Written by some backends during ImGui_ImplXXXX_RenderDrawData() call to point backend_specific ImGui_ImplXXXX_RenderState* structure.
    /// </summary>
    public void* Renderer_RenderState;

    /// <summary>
    /// Textures list (the list is updated by calling ImGui::EndFrame or ImGui::Render)
    /// The ImGui_ImplXXXX_RenderDrawData() function of each backend generally access this via ImDrawData::Textures which points to this. The array is available here mostly because backends will want to destroy textures on shutdown.
    /// List of textures used by Dear ImGui (most often 1) + contents of external texture list is automatically appended into this.
    /// </summary>
    public ImVector_ImTextureDataPtr Textures;

    /// <summary>
    /// Clear all Platform_XXX fields. Typically called on Platform Backend shutdown.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiPlatformIO_ClearPlatformHandlers")]
    public static partial void ClearPlatformHandlers(ImGuiPlatformIO* self);

    /// <summary>
    /// Clear all Renderer_XXX fields. Typically called on Renderer Backend shutdown.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiPlatformIO_ClearRendererHandlers")]
    public static partial void ClearRendererHandlers(ImGuiPlatformIO* self);

}
