// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::TableNextRow()
/// </summary>
[Flags]
public enum ImGuiTableRowFlags
{
    None = 0,
    Headers = 1 << 0 // Identify header row (set default background color + width of its contents accounted differently for auto column width)
}
