// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Enumeration for AddMouseSourceEvent() actual source of Mouse Input data.
/// Historically we use "Mouse" terminology everywhere to indicate pointer data, e.g. MousePos, IsMousePressed(), io.AddMousePosEvent()
/// But that "Mouse" data can come from different source which occasionally may be useful for application to know about.
/// You can submit a change of pointer type using io.AddMouseSourceEvent().
/// Forward declared enum type ImGuiMouseSource
/// </summary>
public enum ImGuiMouseSource
{
    Mouse = 0, // Input is coming from an actual mouse.
    TouchScreen = 1, // Input is coming from a touch screen (no hovering prior to initial press, less precise initial press aiming, dual-axis wheeling possible).
    Pen = 2 // Input is coming from a pressure/magnetic pen (often used in conjunction with high-sampling rates).
}
