// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Function signature for ImGui::SetAllocatorFunctions()
/// </summary>
/// <param name="value">The underlying function pointer.</param>
public readonly unsafe struct ImGuiMemFreeFunc(delegate* unmanaged[Cdecl]<nint, nint, void> value)
{
    /// <summary>The underlying function pointer.</summary>
    public readonly delegate* unmanaged[Cdecl]<nint, nint, void> Value = value;

    /// <summary>Implicitly converts a ImGuiMemFreeFunc to its underlying function pointer.</summary>
    /// <param name="callback">The ImGuiMemFreeFunc to convert.</param>
    public static implicit operator delegate* unmanaged[Cdecl]<nint, nint, void>(ImGuiMemFreeFunc callback) => callback.Value;

    /// <summary>Implicitly converts a function pointer to ImGuiMemFreeFunc.</summary>
    /// <param name="value">The function pointer to convert.</param>
    public static implicit operator ImGuiMemFreeFunc(delegate* unmanaged[Cdecl]<nint, nint, void> value) => new(value);
}
