// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Function signature for ImGui::SetAllocatorFunctions()
/// </summary>
/// <param name="value">The underlying function pointer.</param>
public readonly unsafe struct ImGuiMemAllocFunc(delegate* unmanaged[Cdecl]<nuint, nint, nint> value)
{
    /// <summary>The underlying function pointer.</summary>
    public readonly delegate* unmanaged[Cdecl]<nuint, nint, nint> Value = value;

    /// <summary>Implicitly converts a ImGuiMemAllocFunc to its underlying function pointer.</summary>
    /// <param name="callback">The ImGuiMemAllocFunc to convert.</param>
    public static implicit operator delegate* unmanaged[Cdecl]<nuint, nint, nint>(ImGuiMemAllocFunc callback) => callback.Value;

    /// <summary>Implicitly converts a function pointer to ImGuiMemAllocFunc.</summary>
    /// <param name="value">The function pointer to convert.</param>
    public static implicit operator ImGuiMemAllocFunc(delegate* unmanaged[Cdecl]<nuint, nint, nint> value) => new(value);
}
