// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Optional helper to apply multi-selection requests to existing randomly accessible storage.
/// Convenient if you want to quickly wire multi-select API on e.g. an array of bool or items storing their own selection state.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiSelectionExternalStorage
{
    /// <summary>
    /// Members
    /// User data for use by adapter function                                // e.g. selection.UserData = (void*)my_items;
    /// </summary>
    public void* UserData;

    /// <summary>
    /// e.g. AdapterSetItemSelected = [](ImGuiSelectionExternalStorage* self, int idx, bool selected) { ((MyItems**)self-&gt;UserData)[idx]-&gt;Selected = selected; }
    /// </summary>
    public delegate* unmanaged[Cdecl]<ImGuiSelectionExternalStorage*, int, byte, void> AdapterSetItemSelected;

    /// <summary>
    /// Apply selection requests by using AdapterSetItemSelected() calls
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionExternalStorage_ApplyRequests")]
    public static partial void ApplyRequests(ImGuiSelectionExternalStorage* self, ImGuiMultiSelectIO* ms_io);

}
