// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::TableSetupColumn()
/// </summary>
[Flags]
public enum ImGuiTableColumnFlags
{
    None = 0,
    Disabled = 1 << 0, // Overriding/master disable flag: hide column, won't show in context menu (unlike calling TableSetColumnEnabled() which manipulates the user accessible state)
    DefaultHide = 1 << 1, // Default as a hidden/disabled column.
    DefaultSort = 1 << 2, // Default as a sorting column.
    WidthStretch = 1 << 3, // Column will stretch. Preferable with horizontal scrolling disabled (default if table sizing policy is _SizingStretchSame or _SizingStretchProp).
    WidthFixed = 1 << 4, // Column will not stretch. Preferable with horizontal scrolling enabled (default if table sizing policy is _SizingFixedFit and table is resizable).
    NoResize = 1 << 5, // Disable manual resizing.
    NoReorder = 1 << 6, // Disable manual reordering this column, this will also prevent other columns from crossing over this column.
    NoHide = 1 << 7, // Disable ability to hide/disable this column.
    NoClip = 1 << 8, // Disable clipping for this column (all NoClip columns will render in a same draw command).
    NoSort = 1 << 9, // Disable ability to sort on this field (even if ImGuiTableFlags_Sortable is set on the table).
    NoSortAscending = 1 << 10, // Disable ability to sort in the ascending direction.
    NoSortDescending = 1 << 11, // Disable ability to sort in the descending direction.
    NoHeaderLabel = 1 << 12, // TableHeadersRow() will submit an empty label for this column. Convenient for some small columns. Name will still appear in context menu or in angled headers. You may append into this cell by calling TableSetColumnIndex() right after the TableHeadersRow() call.
    NoHeaderWidth = 1 << 13, // Disable header text width contribution to automatic column width.
    PreferSortAscending = 1 << 14, // Make the initial sort direction Ascending when first sorting on this column (default).
    PreferSortDescending = 1 << 15, // Make the initial sort direction Descending when first sorting on this column.
    IndentEnable = 1 << 16, // Use current Indent value when entering cell (default for column 0).
    IndentDisable = 1 << 17, // Ignore current Indent value when entering cell (default for columns > 0). Indentation changes _within_ the cell will still be honored.
    AngledHeader = 1 << 18, // TableHeadersRow() will submit an angled header row for this column. Note this will add an extra row.
    IsEnabled = 1 << 24, // Status: is enabled == not hidden by user/api (referred to as "Hide" in _DefaultHide and _NoHide) flags.
    IsVisible = 1 << 25, // Status: is visible == is enabled AND not clipped by scrolling.
    IsSorted = 1 << 26, // Status: is currently part of the sort specs
    IsHovered = 1 << 27 // Status: is hovered by mouse
}
