// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// A sorting direction
/// Forward declared enum type ImGuiSortDirection
/// </summary>
public enum ImGuiSortDirection : byte
{
    None = 0,
    Ascending = 1, // Ascending = 0->9, A->Z etc.
    Descending = 2 // Descending = 9->0, Z->A etc.
}
