// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Enumeration for PushStyleColor() / PopStyleColor()
/// </summary>
public enum ImGuiCol
{
    Text = 0,
    TextDisabled = 1,
    WindowBg = 2, // Background of normal windows
    ChildBg = 3, // Background of child windows
    PopupBg = 4, // Background of popups, menus, tooltips windows
    Border = 5,
    BorderShadow = 6,
    FrameBg = 7, // Background of checkbox, radio button, plot, slider, text input
    FrameBgHovered = 8,
    FrameBgActive = 9,
    TitleBg = 10, // Title bar
    TitleBgActive = 11, // Title bar when focused
    TitleBgCollapsed = 12, // Title bar when collapsed
    MenuBarBg = 13,
    ScrollbarBg = 14,
    ScrollbarGrab = 15,
    ScrollbarGrabHovered = 16,
    ScrollbarGrabActive = 17,
    CheckMark = 18, // Checkbox tick and RadioButton circle
    SliderGrab = 19,
    SliderGrabActive = 20,
    Button = 21,
    ButtonHovered = 22,
    ButtonActive = 23,
    Header = 24, // Header* colors are used for CollapsingHeader, TreeNode, Selectable, MenuItem
    HeaderHovered = 25,
    HeaderActive = 26,
    Separator = 27,
    SeparatorHovered = 28,
    SeparatorActive = 29,
    ResizeGrip = 30, // Resize grip in lower-right and lower-left corners of windows.
    ResizeGripHovered = 31,
    ResizeGripActive = 32,
    InputTextCursor = 33, // InputText cursor/caret
    TabHovered = 34, // Tab background, when hovered
    Tab = 35, // Tab background, when tab-bar is focused & tab is unselected
    TabSelected = 36, // Tab background, when tab-bar is focused & tab is selected
    TabSelectedOverline = 37, // Tab horizontal overline, when tab-bar is focused & tab is selected
    TabDimmed = 38, // Tab background, when tab-bar is unfocused & tab is unselected
    TabDimmedSelected = 39, // Tab background, when tab-bar is unfocused & tab is selected
    TabDimmedSelectedOverline = 40, // ..horizontal overline, when tab-bar is unfocused & tab is selected
    PlotLines = 41,
    PlotLinesHovered = 42,
    PlotHistogram = 43,
    PlotHistogramHovered = 44,
    TableHeaderBg = 45, // Table header background
    TableBorderStrong = 46, // Table outer and header borders (prefer using Alpha=1.0 here)
    TableBorderLight = 47, // Table inner borders (prefer using Alpha=1.0 here)
    TableRowBg = 48, // Table row background (even rows)
    TableRowBgAlt = 49, // Table row background (odd rows)
    TextLink = 50, // Hyperlink color
    TextSelectedBg = 51, // Selected text inside an InputText
    TreeLines = 52, // Tree node hierarchy outlines when using ImGuiTreeNodeFlags_DrawLines
    DragDropTarget = 53, // Rectangle border highlighting a drop target
    DragDropTargetBg = 54, // Rectangle background highlighting a drop target
    UnsavedMarker = 55, // Unsaved Document marker (in window title and tabs)
    NavCursor = 56, // Color of keyboard/gamepad navigation cursor/rectangle, when visible
    NavWindowingHighlight = 57, // Highlight window when using Ctrl+Tab
    NavWindowingDimBg = 58, // Darken/colorize entire screen behind the Ctrl+Tab window list, when active
    ModalWindowDimBg = 59, // Darken/colorize entire screen behind a modal window, when one is active
    TabActive = 36, // [renamed in 1.90.9]
    TabUnfocused = 38, // [renamed in 1.90.9]
    TabUnfocusedActive = 39, // [renamed in 1.90.9]
    NavHighlight = 56 // [renamed in 1.91.4]
}
