// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Enumeration for ImGui::SetNextWindow***(), SetWindow***(), SetNextItem***() functions
/// Represent a condition.
/// Important: Treat as a regular enum! Do NOT combine multiple values using binary operators! All the functions above treat 0 as a shortcut to ImGuiCond_Always.
/// </summary>
public enum ImGuiCond
{
    None = 0, // No condition (always set the variable), same as _Always
    Always = 1 << 0, // No condition (always set the variable), same as _None
    Once = 1 << 1, // Set the variable once per runtime session (only the first call will succeed)
    FirstUseEver = 1 << 2, // Set the variable if the object/window has no persistently saved data (no entry in .ini file)
    Appearing = 1 << 3 // Set the variable if the object/window is appearing after being hidden/inactive (or the first time)
}
