// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::BeginCombo()
/// </summary>
[Flags]
public enum ImGuiComboFlags
{
    None = 0,
    PopupAlignLeft = 1 << 0, // Align the popup toward the left by default
    HeightSmall = 1 << 1, // Max ~4 items visible. Tip: If you want your combo popup to be a specific size you can use SetNextWindowSizeConstraints() prior to calling BeginCombo()
    HeightRegular = 1 << 2, // Max ~8 items visible (default)
    HeightLarge = 1 << 3, // Max ~20 items visible
    HeightLargest = 1 << 4, // As many fitting items as possible
    NoArrowButton = 1 << 5, // Display on the preview box without the square arrow button
    NoPreview = 1 << 6, // Display only a square arrow button
    WidthFitPreview = 1 << 7 // Width dynamically calculated from preview contents
}
