// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Multi-Selection item index or identifier when using BeginMultiSelect()
/// - Used by SetNextItemSelectionUserData() + and inside ImGuiMultiSelectIO structure.
/// - Most users are likely to use this store an item INDEX but this may be used to store a POINTER/ID as well. Read comments near ImGuiMultiSelectIO for details.
/// </summary>
/// <param name="value">The underlying ImGuiSelectionUserData value.</param>
public readonly struct ImGuiSelectionUserData(long value)
{
    /// <summary>The underlying ImGuiSelectionUserData value.</summary>
    public readonly long Value = value;

    /// <summary>Implicitly converts a ImGuiSelectionUserData to long.</summary>
    /// <param name="id">The ImGuiSelectionUserData to convert.</param>
    public static implicit operator long(ImGuiSelectionUserData id) => id.Value;

    /// <summary>Implicitly converts a long to ImGuiSelectionUserData.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImGuiSelectionUserData(long value) => new(value);
}
