// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Scalar data types
/// A unique ID used by widgets (typically the result of hashing a stack of string)
/// </summary>
/// <param name="value">The underlying ImGuiID value.</param>
public readonly struct ImGuiID(uint value)
{
    /// <summary>The underlying ImGuiID value.</summary>
    public readonly uint Value = value;

    /// <summary>Implicitly converts a ImGuiID to uint.</summary>
    /// <param name="id">The ImGuiID to convert.</param>
    public static implicit operator uint(ImGuiID id) => id.Value;

    /// <summary>Implicitly converts a uint to ImGuiID.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImGuiID(uint value) => new(value);
}
