// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// A cardinal direction
/// Forward declared enum type ImGuiDir
/// </summary>
public enum ImGuiDir
{
    None = -1,
    Left = 0,
    Right = 1,
    Up = 2,
    Down = 3
}
