// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Forward declarations: ImGui layer
/// Dear ImGui context (opaque structure, unless including imgui_internal.h)
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImGuiContext
{
}
