// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// Sorting specifications for a table (often handling sort specs for a single column, occasionally more)
/// Obtained by calling TableGetSortSpecs().
/// When 'SpecsDirty == true' you can sort your data. It will be true with sorting specs have changed since last call, or the first time.
/// Make sure to set 'SpecsDirty = false' after sorting, else you may wastefully sort your data every frame!
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiTableSortSpecs
{
    /// <summary>
    /// Pointer to sort spec array.
    /// </summary>
    public ImGuiTableColumnSortSpecs* Specs;

    /// <summary>
    /// Sort spec count. Most often 1. May be &gt; 1 when ImGuiTableFlags_SortMulti is enabled. May be == 0 when ImGuiTableFlags_SortTristate is enabled.
    /// </summary>
    public int SpecsCount;

    /// <summary>
    /// Set to true when specs have changed since last time! Use this to sort again, then clear the flag.
    /// </summary>
    public bool SpecsDirty;
}
