// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Enumeration for GetMouseCursor()
/// User code may request backend to display given cursor by calling SetMouseCursor(), which is why we have some cursors that are marked unused here
/// </summary>
public enum ImGuiMouseCursor
{
    None = -1,
    Arrow = 0,
    TextInput = 1, // When hovering over InputText, etc.
    ResizeAll = 2, // (Unused by Dear ImGui functions)
    ResizeNS = 3, // When hovering over a horizontal border
    ResizeEW = 4, // When hovering over a vertical border or a column
    ResizeNESW = 5, // When hovering over the bottom-left corner of a window
    ResizeNWSE = 6, // When hovering over the bottom-right corner of a window
    Hand = 7, // (Unused by Dear ImGui functions. Use for e.g. hyperlinks)
    Wait = 8, // When waiting for something to process/load.
    Progress = 9, // When waiting for something to process/load, but application is still interactive.
    NotAllowed = 10 // When hovering something with disallowed interaction. Usually a crossed circle.
}
