// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Flags for InvisibleButton() [extended in imgui_internal.h]
/// </summary>
[Flags]
public enum ImGuiButtonFlags
{
    None = 0,
    MouseButtonLeft = 1 << 0, // React on left mouse button (default)
    MouseButtonRight = 1 << 1, // React on right mouse button
    MouseButtonMiddle = 1 << 2, // React on center mouse button
    EnableNav = 1 << 3 // InvisibleButton(): do not disable navigation/tabbing. Otherwise disabled by default.
}
