// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// (Optional) Support for IME (Input Method Editor) via the platform_io.Platform_SetImeDataFn() function. Handler is called during EndFrame().
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImGuiPlatformImeData
{
    /// <summary>
    /// A widget wants the IME to be visible.
    /// </summary>
    public bool WantVisible;

    /// <summary>
    /// A widget wants text input, not necessarily IME to be visible. This is automatically set to the upcoming value of io.WantTextInput.
    /// </summary>
    public bool WantTextInput;

    /// <summary>
    /// Position of input cursor (for IME).
    /// </summary>
    public ImVec2 InputPos;

    /// <summary>
    /// Line height (for IME).
    /// </summary>
    public float InputLineHeight;

    /// <summary>
    /// ID of platform window/viewport.
    /// </summary>
    public ImGuiID ViewportId;
}
