// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Optional helper to store multi-selection state + apply multi-selection requests.
/// - Used by our demos and provided as a convenience to easily implement basic multi-selection.
/// - Iterate selection with 'void* it = NULL; ImGuiID id; while (selection.GetNextSelectedItem(&amp;it, &amp;id)) { ... }'
/// Or you can check 'if (Contains(id)) { ... }' for each possible object if their number is not too high to iterate.
/// - USING THIS IS NOT MANDATORY. This is only a helper and not a required API.
/// To store a multi-selection, in your application you could:
/// - Use this helper as a convenience. We use our simple key-&gt;value ImGuiStorage as a std::set&lt;ImGuiID&gt; replacement.
/// - Use your own external storage: e.g. std::set&lt;MyObjectId&gt;, std::vector&lt;MyObjectId&gt;, interval trees, intrusively stored selection etc.
/// In ImGuiSelectionBasicStorage we:
/// - always use indices in the multi-selection API (passed to SetNextItemSelectionUserData(), retrieved in ImGuiMultiSelectIO)
/// - use the AdapterIndexToStorageId() indirection layer to abstract how persistent selection data is derived from an index.
/// - use decently optimized logic to allow queries and insertion of very large selection sets.
/// - do not preserve selection order.
/// Many combinations are possible depending on how you prefer to store your items and how you prefer to store your selection.
/// Large applications are likely to eventually want to get rid of this indirection layer and do their own thing.
/// See https://github.com/ocornut/imgui/wiki/Multi-Select for details and pseudo-code using this helper.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiSelectionBasicStorage
{
    /// <summary>
    /// Members
    /// // Number of selected items, maintained by this helper.
    /// </summary>
    public int Size;

    /// <summary>
    /// = false  // GetNextSelectedItem() will return ordered selection (currently implemented by two additional sorts of selection. Could be improved)
    /// </summary>
    public bool PreserveOrder;

    /// <summary>
    /// = NULL   // User data for use by adapter function        // e.g. selection.UserData = (void*)my_items;
    /// </summary>
    public nint UserData;

    /// <summary>
    /// e.g. selection.AdapterIndexToStorageId = [](ImGuiSelectionBasicStorage* self, int idx) { return ((MyItems**)self-&gt;UserData)[idx]-&gt;ID; };
    /// </summary>
    public nint AdapterIndexToStorageId;

    private int _internal0; // _SelectionOrder

    private ImGuiStorage _internal1; // _Storage

    /// <summary>
    /// Apply selection requests coming from BeginMultiSelect() and EndMultiSelect() functions. It uses 'items_count' passed to BeginMultiSelect()
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionBasicStorage_ApplyRequests")]
    public static partial void ApplyRequests(ImGuiSelectionBasicStorage* self, ImGuiMultiSelectIO* ms_io);

    /// <summary>
    /// Query if an item id is in selection.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionBasicStorage_Contains")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool Contains(ImGuiSelectionBasicStorage* self, ImGuiID id);

    /// <summary>
    /// Clear selection
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionBasicStorage_Clear")]
    public static partial void Clear(ImGuiSelectionBasicStorage* self);

    /// <summary>
    /// Swap two selections
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionBasicStorage_Swap")]
    public static partial void Swap(ImGuiSelectionBasicStorage* self, ImGuiSelectionBasicStorage* r);

    /// <summary>
    /// Add/remove an item from selection (generally done by ApplyRequests() function)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionBasicStorage_SetItemSelected")]
    public static partial void SetItemSelected(ImGuiSelectionBasicStorage* self, ImGuiID id, [MarshalAs(UnmanagedType.U1)] bool selected);

    /// <summary>
    /// Iterate selection with 'void* it = NULL; ImGuiID id; while (selection.GetNextSelectedItem(&amp;it, &amp;id)) { ... }'
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionBasicStorage_GetNextSelectedItem")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool GetNextSelectedItem(ImGuiSelectionBasicStorage* self, nint opaque_it, ImGuiID* out_id);

    /// <summary>
    /// Convert index to item id based on provided adapter.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiSelectionBasicStorage_GetStorageIdFromIndex")]
    public static partial ImGuiID GetStorageIdFromIndex(ImGuiSelectionBasicStorage* self, int idx);

}
