// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Helper: Manually clip large list of items.
/// If you have lots evenly spaced items and you have random access to the list, you can perform coarse
/// clipping based on visibility to only submit items that are in view.
/// The clipper calculates the range of visible items and advance the cursor to compensate for the non-visible items we have skipped.
/// (Dear ImGui already clip items based on their bounds but: it needs to first layout the item to do so, and generally
/// fetching/submitting your own data incurs additional cost. Coarse clipping using ImGuiListClipper allows you to easily
/// scale using lists with tens of thousands of items without a problem)
/// Usage:
/// ImGuiListClipper clipper;
/// clipper.Begin(1000);         // We have 1000 elements, evenly spaced.
/// while (clipper.Step())
/// for (int i = clipper.DisplayStart; i &lt; clipper.DisplayEnd; i++)
/// ImGui::Text("line number %d", i);
/// Generally what happens is:
/// - Clipper lets you process the first element (DisplayStart = 0, DisplayEnd = 1) regardless of it being visible or not.
/// - User code submit that one element.
/// - Clipper can measure the height of the first element
/// - Clipper calculate the actual range of elements to display based on the current clipping rectangle, position the cursor before the first visible element.
/// - User code submit visible elements.
/// - The clipper also handles various subtleties related to keyboard/gamepad navigation, wrapping etc.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiListClipper
{
    /// <summary>
    /// Parent UI context
    /// </summary>
    public ImGuiContext Ctx;

    /// <summary>
    /// First item to display, updated by each call to Step()
    /// </summary>
    public int DisplayStart;

    /// <summary>
    /// End of items to display (exclusive)
    /// </summary>
    public int DisplayEnd;

    private int _internal0; // ItemsCount

    private float _internal1; // ItemsHeight

    private double _internal2; // StartPosY

    private double _internal3; // StartSeekOffsetY

    private nint _internal4; // TempData

    private ImGuiListClipperFlags _internal5; // Flags

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiListClipper_Begin")]
    public static partial void Begin(ImGuiListClipper* self, int items_count, float items_height);

    /// <summary>
    /// Automatically called on the last call of Step() that returns false.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiListClipper_End")]
    public static partial void End(ImGuiListClipper* self);

    /// <summary>
    /// Call until it returns false. The DisplayStart/DisplayEnd fields will be set and you can process/draw those items.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiListClipper_Step")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool Step(ImGuiListClipper* self);

    /// <summary>
    /// Call IncludeItemByIndex() or IncludeItemsByIndex() *BEFORE* first call to Step() if you need a range of items to not be clipped, regardless of their visibility.
    /// (Due to alignment / padding of certain items it is possible that an extra item may be included on either end of the display range).
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiListClipper_IncludeItemByIndex")]
    public static partial void IncludeItemByIndex(ImGuiListClipper* self, int item_index);

    /// <summary>
    /// item_end is exclusive e.g. use (42, 42+1) to make item 42 never clipped.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiListClipper_IncludeItemsByIndex")]
    public static partial void IncludeItemsByIndex(ImGuiListClipper* self, int item_begin, int item_end);

    /// <summary>
    /// Seek cursor toward given item. This is automatically called while stepping.
    /// - The only reason to call this is: you can use ImGuiListClipper::Begin(INT_MAX) if you don't know item count ahead of time.
    /// - In this case, after all steps are done, you'll want to call SeekCursorForItem(item_count).
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiListClipper_SeekCursorForItem")]
    public static partial void SeekCursorForItem(ImGuiListClipper* self, int item_index);

}
