// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiIO
{
    /// <summary>
    /// = 0              // See ImGuiConfigFlags_ enum. Set by user/application. Keyboard/Gamepad navigation options, etc.
    /// </summary>
    public ImGuiConfigFlags ConfigFlags;

    /// <summary>
    /// = 0              // See ImGuiBackendFlags_ enum. Set by backend (imgui_impl_xxx files or custom backend) to communicate features supported by the backend.
    /// </summary>
    public ImGuiBackendFlags BackendFlags;

    /// <summary>
    /// &lt;unset&gt;          // Main display size, in pixels (== GetMainViewport()-&gt;Size). May change every frame.
    /// </summary>
    public ImVec2 DisplaySize;

    /// <summary>
    /// = (1, 1)         // Main display density. For retina display where window coordinates are different from framebuffer coordinates. This will affect font density + will end up in ImDrawData::FramebufferScale.
    /// </summary>
    public ImVec2 DisplayFramebufferScale;

    /// <summary>
    /// = 1.0f/60.0f     // Time elapsed since last frame, in seconds. May change every frame.
    /// </summary>
    public float DeltaTime;

    /// <summary>
    /// = 5.0f           // Minimum time between saving positions/sizes to .ini file, in seconds.
    /// </summary>
    public float IniSavingRate;

    /// <summary>
    /// = "imgui.ini"    // Path to .ini file (important: default "imgui.ini" is relative to current working dir!). Set NULL to disable automatic .ini loading/saving or if you want to manually call LoadIniSettingsXXX() / SaveIniSettingsXXX() functions.
    /// </summary>
    public nint IniFilename;

    /// <summary>
    /// = "imgui_log.txt"// Path to .log file (default parameter to ImGui::LogToFile when no file is specified).
    /// </summary>
    public nint LogFilename;

    /// <summary>
    /// = NULL           // Store your own data.
    /// </summary>
    public nint UserData;

    /// <summary>
    /// Font system
    /// &lt;auto&gt;           // Font atlas: load, rasterize and pack one or more fonts into a single texture.
    /// </summary>
    public ImFontAtlas* Fonts;

    /// <summary>
    /// = NULL           // Font to use on NewFrame(). Use NULL to uses Fonts-&gt;Fonts[0].
    /// </summary>
    public ImFont* FontDefault;

    /// <summary>
    /// = false          // Allow user scaling text of individual window with Ctrl+Wheel.
    /// </summary>
    public bool FontAllowUserScaling;

    /// <summary>
    /// Keyboard/Gamepad Navigation options
    /// = false          // Swap Activate&lt;&gt;Cancel (A&lt;&gt;B) buttons, matching typical "Nintendo/Japanese style" gamepad layout.
    /// </summary>
    public bool ConfigNavSwapGamepadButtons;

    /// <summary>
    /// = false          // Directional/tabbing navigation teleports the mouse cursor. May be useful on TV/console systems where moving a virtual mouse is difficult. Will update io.MousePos and set io.WantSetMousePos=true.
    /// </summary>
    public bool ConfigNavMoveSetMousePos;

    /// <summary>
    /// = true           // Sets io.WantCaptureKeyboard when io.NavActive is set.
    /// </summary>
    public bool ConfigNavCaptureKeyboard;

    /// <summary>
    /// = true           // Pressing Escape can clear focused item + navigation id/highlight. Set to false if you want to always keep highlight on.
    /// </summary>
    public bool ConfigNavEscapeClearFocusItem;

    /// <summary>
    /// = false          // Pressing Escape can clear focused window as well (super set of io.ConfigNavEscapeClearFocusItem).
    /// </summary>
    public bool ConfigNavEscapeClearFocusWindow;

    /// <summary>
    /// = true           // Using directional navigation key makes the cursor visible. Mouse click hides the cursor.
    /// </summary>
    public bool ConfigNavCursorVisibleAuto;

    /// <summary>
    /// = false          // Navigation cursor is always visible.
    /// </summary>
    public bool ConfigNavCursorVisibleAlways;

    /// <summary>
    /// Miscellaneous options
    /// (you can visualize and interact with all options in 'Demo-&gt;Configuration')
    /// = false          // Request ImGui to draw a mouse cursor for you (if you are on a platform without a mouse cursor). Cannot be easily renamed to 'io.ConfigXXX' because this is frequently used by backend implementations.
    /// </summary>
    public bool MouseDrawCursor;

    /// <summary>
    /// = defined(__APPLE__) // Swap Cmd&lt;&gt;Ctrl keys + OS X style text editing cursor movement using Alt instead of Ctrl, Shortcuts using Cmd/Super instead of Ctrl, Line/Text Start and End using Cmd+Arrows instead of Home/End, Double click selects by word instead of selecting whole text, Multi-selection in lists uses Cmd/Super instead of Ctrl.
    /// </summary>
    public bool ConfigMacOSXBehaviors;

    /// <summary>
    /// = true           // Enable input queue trickling: some types of events submitted during the same frame (e.g. button down + up) will be spread over multiple frames, improving interactions with low framerates.
    /// </summary>
    public bool ConfigInputTrickleEventQueue;

    /// <summary>
    /// = true           // Enable blinking cursor (optional as some users consider it to be distracting).
    /// </summary>
    public bool ConfigInputTextCursorBlink;

    /// <summary>
    /// = false          // [BETA] Pressing Enter will keep item active and select contents (single-line only).
    /// </summary>
    public bool ConfigInputTextEnterKeepActive;

    /// <summary>
    /// = false          // [BETA] Enable turning DragXXX widgets into text input with a simple mouse click-release (without moving). Not desirable on devices without a keyboard.
    /// </summary>
    public bool ConfigDragClickToInputText;

    /// <summary>
    /// = true           // Enable resizing of windows from their edges and from the lower-left corner. This requires ImGuiBackendFlags_HasMouseCursors for better mouse cursor feedback. (This used to be a per-window ImGuiWindowFlags_ResizeFromAnySide flag)
    /// </summary>
    public bool ConfigWindowsResizeFromEdges;

    /// <summary>
    /// = false      // Enable allowing to move windows only when clicking on their title bar. Does not apply to windows without a title bar.
    /// </summary>
    public bool ConfigWindowsMoveFromTitleBarOnly;

    /// <summary>
    /// = false      // [EXPERIMENTAL] Ctrl+C copy the contents of focused window into the clipboard. Experimental because: (1) has known issues with nested Begin/End pairs (2) text output quality varies (3) text output is in submission order rather than spatial order.
    /// </summary>
    public bool ConfigWindowsCopyContentsWithCtrlC;

    /// <summary>
    /// = true           // Enable scrolling page by page when clicking outside the scrollbar grab. When disabled, always scroll to clicked location. When enabled, Shift+Click scrolls to clicked location.
    /// </summary>
    public bool ConfigScrollbarScrollByPage;

    /// <summary>
    /// = 60.0f          // Timer (in seconds) to free transient windows/tables memory buffers when unused. Set to -1.0f to disable.
    /// </summary>
    public float ConfigMemoryCompactTimer;

    /// <summary>
    /// Inputs Behaviors
    /// (other variables, ones which are expected to be tweaked within UI code, are exposed in ImGuiStyle)
    /// = 0.30f          // Time for a double-click, in seconds.
    /// </summary>
    public float MouseDoubleClickTime;

    /// <summary>
    /// = 6.0f           // Distance threshold to stay in to validate a double-click, in pixels.
    /// </summary>
    public float MouseDoubleClickMaxDist;

    /// <summary>
    /// = 6.0f           // Distance threshold before considering we are dragging.
    /// </summary>
    public float MouseDragThreshold;

    /// <summary>
    /// = 0.275f         // When holding a key/button, time before it starts repeating, in seconds (for buttons in Repeat mode, etc.).
    /// </summary>
    public float KeyRepeatDelay;

    /// <summary>
    /// = 0.050f         // When holding a key/button, rate at which it repeats, in seconds.
    /// </summary>
    public float KeyRepeatRate;

    /// <summary>
    /// Options to configure Error Handling and how we handle recoverable errors [EXPERIMENTAL]
    /// - Error recovery is provided as a way to facilitate:
    /// - Recovery after a programming error (native code or scripting language - the later tends to facilitate iterating on code while running).
    /// - Recovery after running an exception handler or any error processing which may skip code after an error has been detected.
    /// - Error recovery is not perfect nor guaranteed! It is a feature to ease development.
    /// You not are not supposed to rely on it in the course of a normal application run.
    /// - Functions that support error recovery are using IM_ASSERT_USER_ERROR() instead of IM_ASSERT().
    /// - By design, we do NOT allow error recovery to be 100% silent. One of the three options needs to be checked!
    /// - Always ensure that on programmers seats you have at minimum Asserts or Tooltips enabled when making direct imgui API calls!
    /// Otherwise it would severely hinder your ability to catch and correct mistakes!
    /// Read https://github.com/ocornut/imgui/wiki/Error-Handling for details.
    /// - Programmer seats: keep asserts (default), or disable asserts and keep error tooltips (new and nice!)
    /// - Non-programmer seats: maybe disable asserts, but make sure errors are resurfaced (tooltips, visible log entries, use callback etc.)
    /// - Recovery after error/exception: record stack sizes with ErrorRecoveryStoreState(), disable assert, set log callback (to e.g. trigger high-level breakpoint), recover with ErrorRecoveryTryToRecoverState(), restore settings.
    /// = true       // Enable error recovery support. Some errors won't be detected and lead to direct crashes if recovery is disabled.
    /// </summary>
    public bool ConfigErrorRecovery;

    /// <summary>
    /// = true       // Enable asserts on recoverable error. By default call IM_ASSERT() when returning from a failing IM_ASSERT_USER_ERROR()
    /// </summary>
    public bool ConfigErrorRecoveryEnableAssert;

    /// <summary>
    /// = true       // Enable debug log output on recoverable errors.
    /// </summary>
    public bool ConfigErrorRecoveryEnableDebugLog;

    /// <summary>
    /// = true       // Enable tooltip on recoverable errors. The tooltip include a way to enable asserts if they were disabled.
    /// </summary>
    public bool ConfigErrorRecoveryEnableTooltip;

    /// <summary>
    /// Option to enable various debug tools showing buttons that will call the IM_DEBUG_BREAK() macro.
    /// - The Item Picker tool will be available regardless of this being enabled, in order to maximize its discoverability.
    /// - Requires a debugger being attached, otherwise IM_DEBUG_BREAK() options will appear to crash your application.
    /// e.g. io.ConfigDebugIsDebuggerPresent = ::IsDebuggerPresent() on Win32, or refer to ImOsIsDebuggerPresent() imgui_test_engine/imgui_te_utils.cpp for a Unix compatible version.
    /// = false          // Enable various tools calling IM_DEBUG_BREAK().
    /// </summary>
    public bool ConfigDebugIsDebuggerPresent;

    /// <summary>
    /// Tools to detect code submitting items with conflicting/duplicate IDs
    /// - Code should use PushID()/PopID() in loops, or append "##xx" to same-label identifiers.
    /// - Empty label e.g. Button("") == same ID as parent widget/node. Use Button("##xx") instead!
    /// - See FAQ https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system
    /// = true           // Highlight and show an error message popup when multiple items have conflicting identifiers.
    /// </summary>
    public bool ConfigDebugHighlightIdConflicts;

    /// <summary>
    /// =true // Show "Item Picker" button in aforementioned popup.
    /// </summary>
    public bool ConfigDebugHighlightIdConflictsShowItemPicker;

    /// <summary>
    /// Tools to test correct Begin/End and BeginChild/EndChild behaviors.
    /// - Presently Begin()/End() and BeginChild()/EndChild() needs to ALWAYS be called in tandem, regardless of return value of BeginXXX()
    /// - This is inconsistent with other BeginXXX functions and create confusion for many users.
    /// - We expect to update the API eventually. In the meanwhile we provide tools to facilitate checking user-code behavior.
    /// = false          // First-time calls to Begin()/BeginChild() will return false. NEEDS TO BE SET AT APPLICATION BOOT TIME if you don't want to miss windows.
    /// </summary>
    public bool ConfigDebugBeginReturnValueOnce;

    /// <summary>
    /// = false          // Some calls to Begin()/BeginChild() will return false. Will cycle through window depths then repeat. Suggested use: add "io.ConfigDebugBeginReturnValue = io.KeyShift" in your main loop then occasionally press SHIFT. Windows should be flickering while running.
    /// </summary>
    public bool ConfigDebugBeginReturnValueLoop;

    /// <summary>
    /// Option to deactivate io.AddFocusEvent(false) handling.
    /// - May facilitate interactions with a debugger when focus loss leads to clearing inputs data.
    /// - Backends may have other side-effects on focus loss, so this will reduce side-effects but not necessary remove all of them.
    /// = false          // Ignore io.AddFocusEvent(false), consequently not calling io.ClearInputKeys()/io.ClearInputMouse() in input processing.
    /// </summary>
    public bool ConfigDebugIgnoreFocusLoss;

    /// <summary>
    /// Option to audit .ini data
    /// = false          // Save .ini data with extra comments (particularly helpful for Docking, but makes saving slower)
    /// </summary>
    public bool ConfigDebugIniSettings;

    /// <summary>
    /// Nowadays those would be stored in ImGuiPlatformIO but we are leaving them here for legacy reasons.
    /// Optional: Platform/Renderer backend name (informational only! will be displayed in About Window) + User data for backend/wrappers to store their own stuff.
    /// = NULL
    /// </summary>
    public nint BackendPlatformName;

    /// <summary>
    /// = NULL
    /// </summary>
    public nint BackendRendererName;

    /// <summary>
    /// = NULL           // User data for platform backend
    /// </summary>
    public nint BackendPlatformUserData;

    /// <summary>
    /// = NULL           // User data for renderer backend
    /// </summary>
    public nint BackendRendererUserData;

    /// <summary>
    /// = NULL           // User data for non C++ programming language backend
    /// </summary>
    public nint BackendLanguageUserData;

    /// <summary>
    /// Set when Dear ImGui will use mouse inputs, in this case do not dispatch them to your main game/application (either way, always pass on mouse inputs to imgui). (e.g. unclicked mouse is hovering over an imgui window, widget is active, mouse was clicked over an imgui window, etc.).
    /// </summary>
    public bool WantCaptureMouse;

    /// <summary>
    /// Set when Dear ImGui will use keyboard inputs, in this case do not dispatch them to your main game/application (either way, always pass keyboard inputs to imgui). (e.g. InputText active, or an imgui window is focused and navigation is enabled, etc.).
    /// </summary>
    public bool WantCaptureKeyboard;

    /// <summary>
    /// Mobile/console: when set, you may display an on-screen keyboard. This is set by Dear ImGui when it wants textual keyboard input to happen (e.g. when a InputText widget is active).
    /// </summary>
    public bool WantTextInput;

    /// <summary>
    /// MousePos has been altered, backend should reposition mouse on next frame. Rarely used! Set only when io.ConfigNavMoveSetMousePos is enabled.
    /// </summary>
    public bool WantSetMousePos;

    /// <summary>
    /// When manual .ini load/save is active (io.IniFilename == NULL), this will be set to notify your application that you can call SaveIniSettingsToMemory() and save yourself. Important: clear io.WantSaveIniSettings yourself after saving!
    /// </summary>
    public bool WantSaveIniSettings;

    /// <summary>
    /// Keyboard/Gamepad navigation is currently allowed (will handle ImGuiKey_NavXXX events) = a window is focused and it doesn't use the ImGuiWindowFlags_NoNavInputs flag.
    /// </summary>
    public bool NavActive;

    /// <summary>
    /// Keyboard/Gamepad navigation highlight is visible and allowed (will handle ImGuiKey_NavXXX events).
    /// </summary>
    public bool NavVisible;

    /// <summary>
    /// Estimate of application framerate (rolling average over 60 frames, based on io.DeltaTime), in frame per second. Solely for convenience. Slow applications may not want to use a moving average or may want to reset underlying buffers occasionally.
    /// </summary>
    public float Framerate;

    /// <summary>
    /// Vertices output during last call to Render()
    /// </summary>
    public int MetricsRenderVertices;

    /// <summary>
    /// Indices output during last call to Render() = number of triangles * 3
    /// </summary>
    public int MetricsRenderIndices;

    /// <summary>
    /// Number of visible windows
    /// </summary>
    public int MetricsRenderWindows;

    /// <summary>
    /// Number of active windows
    /// </summary>
    public int MetricsActiveWindows;

    /// <summary>
    /// Mouse delta. Note that this is zero if either current or previous position are invalid (-FLT_MAX,-FLT_MAX), so a disappearing/reappearing mouse won't have a huge delta.
    /// </summary>
    public ImVec2 MouseDelta;

    private ImGuiContext _internal0; // Ctx

    private ImVec2 _internal1; // MousePos

    private fixed bool _internal2[5]; // MouseDown

    private float _internal3; // MouseWheel

    private float _internal4; // MouseWheelH

    private ImGuiMouseSource _internal5; // MouseSource

    private bool _internal6; // KeyCtrl

    private bool _internal7; // KeyShift

    private bool _internal8; // KeyAlt

    private bool _internal9; // KeySuper

    private ImGuiKeyChord _internal10; // KeyMods

    // TODO: Fixed array of nint[ImGuiKey_NamedKey_COUNT]
    private nint __internal11_0; // KeysData

    private bool _internal12; // WantCaptureMouseUnlessPopupClose

    private ImVec2 _internal13; // MousePosPrev

    // TODO: Fixed array of ImVec2[5]
    private ImVec2 __internal14_0; // MouseClickedPos

    private fixed double _internal15[5]; // MouseClickedTime

    private fixed bool _internal16[5]; // MouseClicked

    private fixed bool _internal17[5]; // MouseDoubleClicked

    private fixed ushort _internal18[5]; // MouseClickedCount

    private fixed ushort _internal19[5]; // MouseClickedLastCount

    private fixed bool _internal20[5]; // MouseReleased

    private fixed double _internal21[5]; // MouseReleasedTime

    private fixed bool _internal22[5]; // MouseDownOwned

    private fixed bool _internal23[5]; // MouseDownOwnedUnlessPopupClose

    private bool _internal24; // MouseWheelRequestAxisSwap

    private bool _internal25; // MouseCtrlLeftAsRightClick

    private fixed float _internal26[5]; // MouseDownDuration

    private fixed float _internal27[5]; // MouseDownDurationPrev

    private fixed float _internal28[5]; // MouseDragMaxDistanceSqr

    private float _internal29; // PenPressure

    private bool _internal30; // AppFocusLost

    private bool _internal31; // AppAcceptingEvents

    private ushort _internal32; // InputQueueSurrogate

    private ImVector_ImWchar _internal33; // InputQueueCharacters

    /// <summary>
    /// Input Functions
    /// Queue a new key down/up event. Key should be "translated" (as in, generally ImGuiKey_A matches the key end-user would use to emit an 'A' character)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddKeyEvent")]
    public static partial void AddKeyEvent(ImGuiIO* self, ImGuiKey key, [MarshalAs(UnmanagedType.U1)] bool down);

    /// <summary>
    /// Queue a new key down/up event for analog values (e.g. ImGuiKey_Gamepad_ values). Dead-zones should be handled by the backend.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddKeyAnalogEvent")]
    public static partial void AddKeyAnalogEvent(ImGuiIO* self, ImGuiKey key, [MarshalAs(UnmanagedType.U1)] bool down, float v);

    /// <summary>
    /// Queue a mouse position update. Use -FLT_MAX,-FLT_MAX to signify no mouse (e.g. app not focused and not hovered)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddMousePosEvent")]
    public static partial void AddMousePosEvent(ImGuiIO* self, float x, float y);

    /// <summary>
    /// Queue a mouse button change
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddMouseButtonEvent")]
    public static partial void AddMouseButtonEvent(ImGuiIO* self, int button, [MarshalAs(UnmanagedType.U1)] bool down);

    /// <summary>
    /// Queue a mouse wheel update. wheel_y&lt;0: scroll down, wheel_y&gt;0: scroll up, wheel_x&lt;0: scroll right, wheel_x&gt;0: scroll left.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddMouseWheelEvent")]
    public static partial void AddMouseWheelEvent(ImGuiIO* self, float wheel_x, float wheel_y);

    /// <summary>
    /// Queue a mouse source change (Mouse/TouchScreen/Pen)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddMouseSourceEvent")]
    public static partial void AddMouseSourceEvent(ImGuiIO* self, ImGuiMouseSource source);

    /// <summary>
    /// Queue a gain/loss of focus for the application (generally based on OS/platform focus of your window)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddFocusEvent")]
    public static partial void AddFocusEvent(ImGuiIO* self, [MarshalAs(UnmanagedType.U1)] bool focused);

    /// <summary>
    /// Queue a new character input
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddInputCharacter")]
    public static partial void AddInputCharacter(ImGuiIO* self, uint c);

    /// <summary>
    /// Queue a new character input from a UTF-16 character, it can be a surrogate
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddInputCharacterUTF16")]
    public static partial void AddInputCharacterUTF16(ImGuiIO* self, ushort c);

    /// <summary>
    /// Queue a new characters input from a UTF-8 string
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_AddInputCharactersUTF8")]
    public static partial void AddInputCharactersUTF8(ImGuiIO* self, [MarshalAs(UnmanagedType.LPUTF8Str)] string str);

    /// <summary>
    /// [Optional] Specify index for legacy &lt;1.87 IsKeyXXX() functions with native indices + specify native keycode, scancode.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_SetKeyEventNativeDataEx")]
    public static partial void SetKeyEventNativeData(ImGuiIO* self, ImGuiKey key, int native_keycode, int native_scancode, int native_legacy_index);

    /// <summary>
    /// Set master flag for accepting key/mouse/text events (default to true). Useful if you have native dialog boxes that are interrupting your application loop/refresh, and you want to disable events being queued while your app is frozen.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_SetAppAcceptingEvents")]
    public static partial void SetAppAcceptingEvents(ImGuiIO* self, [MarshalAs(UnmanagedType.U1)] bool accepting_events);

    /// <summary>
    /// Clear all incoming events.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_ClearEventsQueue")]
    public static partial void ClearEventsQueue(ImGuiIO* self);

    /// <summary>
    /// Clear current keyboard/gamepad state + current frame text input buffer. Equivalent to releasing all keys/buttons.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_ClearInputKeys")]
    public static partial void ClearInputKeys(ImGuiIO* self);

    /// <summary>
    /// Clear current mouse state.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiIO_ClearInputMouse")]
    public static partial void ClearInputMouse(ImGuiIO* self);

}
