// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// A key identifier (ImGuiKey_XXX or ImGuiMod_XXX value): can represent Keyboard, Mouse and Gamepad values.
/// All our named keys are &gt;= 512. Keys value 0 to 511 are left unused and were legacy native/opaque key values (&lt; 1.87).
/// Support for legacy keys was completely removed in 1.91.5.
/// Read details about the 1.87+ transition : https://github.com/ocornut/imgui/issues/4921
/// Note that "Keys" related to physical keys and are not the same concept as input "Characters", the later are submitted via io.AddInputCharacter().
/// The keyboard key enum values are named after the keys on a standard US keyboard, and on other keyboard types the keys reported may not match the keycaps.
/// Forward declared enum type ImGuiKey
/// </summary>
public enum ImGuiKey
{
    None = 0,
    NamedKey_BEGIN = 512, // First valid key value (other than 0)
    Tab = 512, // == ImGuiKey_NamedKey_BEGIN
    LeftArrow = 513,
    RightArrow = 514,
    UpArrow = 515,
    DownArrow = 516,
    PageUp = 517,
    PageDown = 518,
    Home = 519,
    End = 520,
    Insert = 521,
    Delete = 522,
    Backspace = 523,
    Space = 524,
    Enter = 525,
    Escape = 526,
    LeftCtrl = 527,
    LeftShift = 528,
    LeftAlt = 529,
    LeftSuper = 530, // Also see ImGuiMod_Ctrl, ImGuiMod_Shift, ImGuiMod_Alt, ImGuiMod_Super below!
    RightCtrl = 531,
    RightShift = 532,
    RightAlt = 533,
    RightSuper = 534,
    Menu = 535,
    Zero = 536,
    One = 537,
    Two = 538,
    Three = 539,
    Four = 540,
    Five = 541,
    Six = 542,
    Seven = 543,
    Eight = 544,
    Nine = 545,
    A = 546,
    B = 547,
    C = 548,
    D = 549,
    E = 550,
    F = 551,
    G = 552,
    H = 553,
    I = 554,
    J = 555,
    K = 556,
    L = 557,
    M = 558,
    N = 559,
    O = 560,
    P = 561,
    Q = 562,
    R = 563,
    S = 564,
    T = 565,
    U = 566,
    V = 567,
    W = 568,
    X = 569,
    Y = 570,
    Z = 571,
    F1 = 572,
    F2 = 573,
    F3 = 574,
    F4 = 575,
    F5 = 576,
    F6 = 577,
    F7 = 578,
    F8 = 579,
    F9 = 580,
    F10 = 581,
    F11 = 582,
    F12 = 583,
    F13 = 584,
    F14 = 585,
    F15 = 586,
    F16 = 587,
    F17 = 588,
    F18 = 589,
    F19 = 590,
    F20 = 591,
    F21 = 592,
    F22 = 593,
    F23 = 594,
    F24 = 595,
    Apostrophe = 596, // '
    Comma = 597, // ,
    Minus = 598, // -
    Period = 599, // .
    Slash = 600, // /
    Semicolon = 601, // ;
    Equal = 602, // =
    LeftBracket = 603, // [
    Backslash = 604, // \ (this text inhibit multiline comment caused by backslash)
    RightBracket = 605, // ]
    GraveAccent = 606, // `
    CapsLock = 607,
    ScrollLock = 608,
    NumLock = 609,
    PrintScreen = 610,
    Pause = 611,
    Keypad0 = 612,
    Keypad1 = 613,
    Keypad2 = 614,
    Keypad3 = 615,
    Keypad4 = 616,
    Keypad5 = 617,
    Keypad6 = 618,
    Keypad7 = 619,
    Keypad8 = 620,
    Keypad9 = 621,
    KeypadDecimal = 622,
    KeypadDivide = 623,
    KeypadMultiply = 624,
    KeypadSubtract = 625,
    KeypadAdd = 626,
    KeypadEnter = 627,
    KeypadEqual = 628,
    AppBack = 629, // Available on some keyboard/mouses. Often referred as "Browser Back"
    AppForward = 630,
    Oem102 = 631, // Non-US backslash.
    GamepadStart = 632, // Menu        | +       | Options  |
    GamepadBack = 633, // View        | -       | Share    |
    GamepadFaceLeft = 634, // X           | Y       | Square   | Tap: Toggle Menu. Hold: Windowing mode (Focus/Move/Resize windows)
    GamepadFaceRight = 635, // B           | A       | Circle   | Cancel / Close / Exit
    GamepadFaceUp = 636, // Y           | X       | Triangle | Text Input / On-screen Keyboard
    GamepadFaceDown = 637, // A           | B       | Cross    | Activate / Open / Toggle / Tweak
    GamepadDpadLeft = 638, // D-pad Left  | "       | "        | Move / Tweak / Resize Window (in Windowing mode)
    GamepadDpadRight = 639, // D-pad Right | "       | "        | Move / Tweak / Resize Window (in Windowing mode)
    GamepadDpadUp = 640, // D-pad Up    | "       | "        | Move / Tweak / Resize Window (in Windowing mode)
    GamepadDpadDown = 641, // D-pad Down  | "       | "        | Move / Tweak / Resize Window (in Windowing mode)
    GamepadL1 = 642, // L Bumper    | L       | L1       | Tweak Slower / Focus Previous (in Windowing mode)
    GamepadR1 = 643, // R Bumper    | R       | R1       | Tweak Faster / Focus Next (in Windowing mode)
    GamepadL2 = 644, // L Trigger   | ZL      | L2       | [Analog]
    GamepadR2 = 645, // R Trigger   | ZR      | R2       | [Analog]
    GamepadL3 = 646, // L Stick     | L3      | L3       |
    GamepadR3 = 647, // R Stick     | R3      | R3       |
    GamepadLStickLeft = 648, // |         |          | [Analog] Move Window (in Windowing mode)
    GamepadLStickRight = 649, // |         |          | [Analog] Move Window (in Windowing mode)
    GamepadLStickUp = 650, // |         |          | [Analog] Move Window (in Windowing mode)
    GamepadLStickDown = 651, // |         |          | [Analog] Move Window (in Windowing mode)
    GamepadRStickLeft = 652, // |         |          | [Analog]
    GamepadRStickRight = 653, // |         |          | [Analog]
    GamepadRStickUp = 654, // |         |          | [Analog]
    GamepadRStickDown = 655, // |         |          | [Analog]
    MouseLeft = 656,
    MouseRight = 657,
    MouseMiddle = 658,
    MouseX1 = 659,
    MouseX2 = 660,
    MouseWheelX = 661,
    MouseWheelY = 662,
    ImGuiMod_None = 0,
    ImGuiMod_Ctrl = 1 << 12, // Ctrl (non-macOS), Cmd (macOS)
    ImGuiMod_Shift = 1 << 13, // Shift
    ImGuiMod_Alt = 1 << 14, // Option/Menu
    ImGuiMod_Super = 1 << 15 // Windows/Super (non-macOS), Ctrl (macOS)
}
