// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Configuration flags stored in io.ConfigFlags. Set by user/application.
/// </summary>
[Flags]
public enum ImGuiConfigFlags
{
    None = 0,
    NavEnableKeyboard = 1 << 0, // Master keyboard navigation enable flag. Enable full Tabbing + directional arrows + space/enter to activate.
    NavEnableGamepad = 1 << 1, // Master gamepad navigation enable flag. Backend also needs to set ImGuiBackendFlags_HasGamepad.
    NoMouse = 1 << 4, // Instruct dear imgui to disable mouse inputs and interactions.
    NoMouseCursorChange = 1 << 5, // Instruct backend to not alter mouse cursor shape and visibility. Use if the backend cursor changes are interfering with yours and you don't want to use SetMouseCursor() to change mouse cursor. You may want to honor requests from imgui by reading GetMouseCursor() yourself instead.
    NoKeyboard = 1 << 6, // Instruct dear imgui to disable keyboard inputs and interactions. This is done by ignoring keyboard events and clearing existing states.
    IsSRGB = 1 << 20, // Application is SRGB-aware.
    IsTouchScreen = 1 << 21, // Application is using a touch screen instead of a mouse.
    NavEnableSetMousePos = 1 << 2, // [moved/renamed in 1.91.4] -> use bool io.ConfigNavMoveSetMousePos
    NavNoCaptureKeyboard = 1 << 3 // [moved/renamed in 1.91.4] -> use bool io.ConfigNavCaptureKeyboard
}
