// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

// This type is only referenced

/// <summary>
/// [Internal] Storage used by IsKeyDown(), IsKeyPressed() etc functions.
/// If prior to 1.87 you used io.KeysDownDuration[] (which was marked as internal), you should use GetKeyData(key)-&gt;DownDuration and *NOT* io.KeysData[key]-&gt;DownDuration.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImGuiKeyData
{
    /// <summary>
    /// True for if key is down
    /// </summary>
    public bool Down;

    /// <summary>
    /// Duration the key has been down (&lt;0.0f: not pressed, 0.0f: just pressed, &gt;0.0f: time held)
    /// </summary>
    public float DownDuration;

    /// <summary>
    /// Last frame duration the key has been down
    /// </summary>
    public float DownDurationPrev;

    /// <summary>
    /// 0.0f..1.0f for gamepad values
    /// </summary>
    public float AnalogValue;
}
