// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Main IO structure returned by BeginMultiSelect()/EndMultiSelect().
/// This mainly contains a list of selection requests.
/// - Use 'Demo-&gt;Tools-&gt;Debug Log-&gt;Selection' to see requests as they happen.
/// - Some fields are only useful if your list is dynamic and allows deletion (getting post-deletion focus/state right is shown in the demo)
/// - Below: who reads/writes each fields? 'r'=read, 'w'=write, 'ms'=multi-select code, 'app'=application/user code.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImGuiMultiSelectIO
{
    /// <summary>
    /// ------------------------------------------// BeginMultiSelect / EndMultiSelect
    /// ms:w, app:r     /  ms:w  app:r   // Requests to apply to your selection data.
    /// </summary>
    public ImVector_ImGuiSelectionRequest Requests;

    /// <summary>
    /// ms:w  app:r     /                // (If using clipper) Begin: Source item (often the first selected item) must never be clipped: use clipper.IncludeItemByIndex() to ensure it is submitted.
    /// </summary>
    public ImGuiSelectionUserData RangeSrcItem;

    /// <summary>
    /// ms:w, app:r     /                // (If using deletion) Last known SetNextItemSelectionUserData() value for NavId (if part of submitted items).
    /// </summary>
    public ImGuiSelectionUserData NavIdItem;

    /// <summary>
    /// ms:w, app:r     /        app:r   // (If using deletion) Last known selection state for NavId (if part of submitted items).
    /// </summary>
    public bool NavIdSelected;

    /// <summary>
    /// app:w     /  ms:r          // (If using deletion) Set before EndMultiSelect() to reset ResetSrcItem (e.g. if deleted selection).
    /// </summary>
    public bool RangeSrcReset;

    /// <summary>
    /// ms:w, app:r     /        app:r   // 'int items_count' parameter to BeginMultiSelect() is copied here for convenience, allowing simpler calls to your ApplyRequests handler. Not used internally.
    /// </summary>
    public int ItemsCount;
}
