// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Status of a texture to communicate with Renderer Backend.
/// </summary>
public enum ImTextureStatus
{
    OK = 0,
    Destroyed = 1, // Backend destroyed the texture.
    WantCreate = 2, // Requesting backend to create the texture. Set status OK when done.
    WantUpdates = 3, // Requesting backend to update specific blocks of pixels (write to texture portions which have never been used before). Set status OK when done.
    WantDestroy = 4 // Requesting backend to destroy the texture. Set status to Destroyed when done.
}
