// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImTextureRef
{
    /// <summary>
    /// Members (either are set, never both!)
    /// A texture, generally owned by a ImFontAtlas. Will convert to ImTextureID during render loop, after texture has been uploaded.
    /// </summary>
    public ImTextureData* TexData;

    /// <summary>
    /// _OR_ Low-level backend texture identifier, if already uploaded or created by user/app. Generally provided to e.g. ImGui::Image() calls.
    /// </summary>
    public ImTextureID TexID;

    /// <summary>
    /// == (_TexData ? _TexData-&gt;TexID : _TexID) // Implemented below in the file.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureRef_GetTexID")]
    public static partial ImTextureID GetTexID(ImTextureRef* self);

}
