// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Default: store up to 64-bits (any pointer or integer). A majority of backends are ok with that.
/// </summary>
/// <param name="value">The underlying ImTextureID value.</param>
public readonly struct ImTextureID(nint value)
{
    /// <summary>The underlying ImTextureID value.</summary>
    public readonly nint Value = value;

    /// <summary>Implicitly converts a ImTextureID to nint.</summary>
    /// <param name="id">The ImTextureID to convert.</param>
    public static implicit operator nint(ImTextureID id) => id.Value;

    /// <summary>Implicitly converts a nint to ImTextureID.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImTextureID(nint value) => new(value);
}
