// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Most standard backends only support RGBA32 but we provide a single channel option for low-resource/embedded systems.
/// </summary>
public enum ImTextureFormat
{
    RGBA32 = 0, // 4 components per pixel, each is unsigned 8-bit. Total size = TexWidth * TexHeight * 4
    Alpha8 = 1 // 1 component per pixel, each is unsigned 8-bit. Total size = TexWidth * TexHeight
}
