// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

[StructLayout(LayoutKind.Sequential)]
public partial struct ImVec2
{
    public float X;

    public float Y;
}
