// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Instantiation of ImVector&lt;ImTextureData*&gt;
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImVector_ImTextureDataPtr
{
    public int Size;

    public int Capacity;

    public ImTextureData** Data;
}
