// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

/// <summary>
/// ImVec4: 4D vector used to store clipping rectangles, colors etc. [Compile-time configurable type]
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImVec4
{
    public float X;

    public float Y;

    public float Z;

    public float W;
}
