// <auto-generated>
// This file was generated by Sdl3Sharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace Sdl3Sharp.ImGui.Native;

/// <summary>
/// Instantiation of ImVector&lt;ImFont*&gt;
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImVector_ImFontPtr
{
    public int Size;

    public int Capacity;

    public nint Data;
}
