// We are intentionally exposing the P/Invoke calls so people can do low-level calls if needed
#pragma warning disable CA1401 // P/Invokes should not be visible

using static Sdl3Sharp.Native.Scancode;

namespace Sdl3Sharp.Native;

/// <summary>
/// P/Invoke bindings for SDL_keycode.h - Keyboard keycode definitions.
/// </summary>
/// <remarks>
/// Defines constants which identify keyboard keys and modifiers.
/// See: https://wiki.libsdl.org/SDL3/BestKeyboardPractices
/// </remarks>
public static unsafe partial class Keycode
{
    /// <summary>
    /// The SDL virtual key representation.
    /// Values of this type are used to represent keyboard keys using the current
    /// layout of the keyboard. These values include Unicode values representing
    /// the unmodified character that would be generated by pressing the key, or an
    /// SDLK_* constant for those keys that do not generate characters.
    /// </summary>
    /// <remarks>
    /// A special exception is the number keys at the top of the keyboard which map
    /// to SDLK_0...SDLK_9 on AZERTY layouts.
    /// Keys with the SDLK_EXTENDED_MASK bit set do not map to a scancode or unicode code point.
    /// </remarks>
    public enum SDL_Keycode : uint
    {
        /// <summary>Unknown key (0).</summary>
        SDLK_UNKNOWN = 0x00000000u,

        // Character keys

        /// <summary>Backspace key ('\b').</summary>
        SDLK_BACKSPACE = 0x00000008u,
        /// <summary>Tab key ('\t').</summary>
        SDLK_TAB = 0x00000009u,
        /// <summary>Return/Enter key ('\r').</summary>
        SDLK_RETURN = 0x0000000du,
        /// <summary>Escape key ('\x1B').</summary>
        SDLK_ESCAPE = 0x0000001bu,
        /// <summary>Space key (' ').</summary>
        SDLK_SPACE = 0x00000020u,
        /// <summary>Exclamation mark key ('!').</summary>
        SDLK_EXCLAIM = 0x00000021u,
        /// <summary>Double apostrophe/quote key ('"').</summary>
        SDLK_DBLAPOSTROPHE = 0x00000022u,
        /// <summary>Hash key ('#').</summary>
        SDLK_HASH = 0x00000023u,
        /// <summary>Dollar sign key ('$').</summary>
        SDLK_DOLLAR = 0x00000024u,
        /// <summary>Percent key ('%').</summary>
        SDLK_PERCENT = 0x00000025u,
        /// <summary>Ampersand key ('&amp;').</summary>
        SDLK_AMPERSAND = 0x00000026u,
        /// <summary>Apostrophe key ('\'').</summary>
        SDLK_APOSTROPHE = 0x00000027u,
        /// <summary>Left parenthesis key ('(').</summary>
        SDLK_LEFTPAREN = 0x00000028u,
        /// <summary>Right parenthesis key (')').</summary>
        SDLK_RIGHTPAREN = 0x00000029u,
        /// <summary>Asterisk key ('*').</summary>
        SDLK_ASTERISK = 0x0000002au,
        /// <summary>Plus key ('+').</summary>
        SDLK_PLUS = 0x0000002bu,
        /// <summary>Comma key (',').</summary>
        SDLK_COMMA = 0x0000002cu,
        /// <summary>Minus key ('-').</summary>
        SDLK_MINUS = 0x0000002du,
        /// <summary>Period key ('.').</summary>
        SDLK_PERIOD = 0x0000002eu,
        /// <summary>Forward slash key ('/').</summary>
        SDLK_SLASH = 0x0000002fu,

        // Number keys

        /// <summary>The 0 key.</summary>
        SDLK_0 = 0x00000030u,
        /// <summary>The 1 key.</summary>
        SDLK_1 = 0x00000031u,
        /// <summary>The 2 key.</summary>
        SDLK_2 = 0x00000032u,
        /// <summary>The 3 key.</summary>
        SDLK_3 = 0x00000033u,
        /// <summary>The 4 key.</summary>
        SDLK_4 = 0x00000034u,
        /// <summary>The 5 key.</summary>
        SDLK_5 = 0x00000035u,
        /// <summary>The 6 key.</summary>
        SDLK_6 = 0x00000036u,
        /// <summary>The 7 key.</summary>
        SDLK_7 = 0x00000037u,
        /// <summary>The 8 key.</summary>
        SDLK_8 = 0x00000038u,
        /// <summary>The 9 key.</summary>
        SDLK_9 = 0x00000039u,

        // Punctuation keys

        /// <summary>Colon key (':').</summary>
        SDLK_COLON = 0x0000003au,
        /// <summary>Semicolon key (';').</summary>
        SDLK_SEMICOLON = 0x0000003bu,
        /// <summary>Less than key ('&lt;').</summary>
        SDLK_LESS = 0x0000003cu,
        /// <summary>Equals key ('=').</summary>
        SDLK_EQUALS = 0x0000003du,
        /// <summary>Greater than key ('&gt;').</summary>
        SDLK_GREATER = 0x0000003eu,
        /// <summary>Question mark key ('?').</summary>
        SDLK_QUESTION = 0x0000003fu,
        /// <summary>At sign key ('@').</summary>
        SDLK_AT = 0x00000040u,

        // Bracket keys

        /// <summary>Left bracket key ('[').</summary>
        SDLK_LEFTBRACKET = 0x0000005bu,
        /// <summary>Backslash key ('\\').</summary>
        SDLK_BACKSLASH = 0x0000005cu,
        /// <summary>Right bracket key (']').</summary>
        SDLK_RIGHTBRACKET = 0x0000005du,
        /// <summary>Caret key ('^').</summary>
        SDLK_CARET = 0x0000005eu,
        /// <summary>Underscore key ('_').</summary>
        SDLK_UNDERSCORE = 0x0000005fu,
        /// <summary>Grave accent/backtick key ('`').</summary>
        SDLK_GRAVE = 0x00000060u,

        // Letter keys

        /// <summary>The A key.</summary>
        SDLK_A = 0x00000061u,
        /// <summary>The B key.</summary>
        SDLK_B = 0x00000062u,
        /// <summary>The C key.</summary>
        SDLK_C = 0x00000063u,
        /// <summary>The D key.</summary>
        SDLK_D = 0x00000064u,
        /// <summary>The E key.</summary>
        SDLK_E = 0x00000065u,
        /// <summary>The F key.</summary>
        SDLK_F = 0x00000066u,
        /// <summary>The G key.</summary>
        SDLK_G = 0x00000067u,
        /// <summary>The H key.</summary>
        SDLK_H = 0x00000068u,
        /// <summary>The I key.</summary>
        SDLK_I = 0x00000069u,
        /// <summary>The J key.</summary>
        SDLK_J = 0x0000006au,
        /// <summary>The K key.</summary>
        SDLK_K = 0x0000006bu,
        /// <summary>The L key.</summary>
        SDLK_L = 0x0000006cu,
        /// <summary>The M key.</summary>
        SDLK_M = 0x0000006du,
        /// <summary>The N key.</summary>
        SDLK_N = 0x0000006eu,
        /// <summary>The O key.</summary>
        SDLK_O = 0x0000006fu,
        /// <summary>The P key.</summary>
        SDLK_P = 0x00000070u,
        /// <summary>The Q key.</summary>
        SDLK_Q = 0x00000071u,
        /// <summary>The R key.</summary>
        SDLK_R = 0x00000072u,
        /// <summary>The S key.</summary>
        SDLK_S = 0x00000073u,
        /// <summary>The T key.</summary>
        SDLK_T = 0x00000074u,
        /// <summary>The U key.</summary>
        SDLK_U = 0x00000075u,
        /// <summary>The V key.</summary>
        SDLK_V = 0x00000076u,
        /// <summary>The W key.</summary>
        SDLK_W = 0x00000077u,
        /// <summary>The X key.</summary>
        SDLK_X = 0x00000078u,
        /// <summary>The Y key.</summary>
        SDLK_Y = 0x00000079u,
        /// <summary>The Z key.</summary>
        SDLK_Z = 0x0000007au,

        // Brace and special character keys

        /// <summary>Left brace key ('{').</summary>
        SDLK_LEFTBRACE = 0x0000007bu,
        /// <summary>Pipe key ('|').</summary>
        SDLK_PIPE = 0x0000007cu,
        /// <summary>Right brace key ('}').</summary>
        SDLK_RIGHTBRACE = 0x0000007du,
        /// <summary>Tilde key ('~').</summary>
        SDLK_TILDE = 0x0000007eu,
        /// <summary>Delete key ('\x7F').</summary>
        SDLK_DELETE = 0x0000007fu,
        /// <summary>Plus-minus key ('+-').</summary>
        SDLK_PLUSMINUS = 0x000000b1u,

        // Extended keys (SDLK_EXTENDED_MASK)

        /// <summary>Extended key: Left Tab.</summary>
        SDLK_LEFT_TAB = 0x20000001u,
        /// <summary>Extended key: Level 5 Shift.</summary>
        SDLK_LEVEL5_SHIFT = 0x20000002u,
        /// <summary>Extended key: Multi-key Compose.</summary>
        SDLK_MULTI_KEY_COMPOSE = 0x20000003u,
        /// <summary>Extended key: Left Meta.</summary>
        SDLK_LMETA = 0x20000004u,
        /// <summary>Extended key: Right Meta.</summary>
        SDLK_RMETA = 0x20000005u,
        /// <summary>Extended key: Left Hyper.</summary>
        SDLK_LHYPER = 0x20000006u,
        /// <summary>Extended key: Right Hyper.</summary>
        SDLK_RHYPER = 0x20000007u,

        // Function and navigation keys (derived from scancodes)

        /// <summary>Caps Lock key.</summary>
        SDLK_CAPSLOCK = 0x40000039u,
        /// <summary>F1 key.</summary>
        SDLK_F1 = 0x4000003au,
        /// <summary>F2 key.</summary>
        SDLK_F2 = 0x4000003bu,
        /// <summary>F3 key.</summary>
        SDLK_F3 = 0x4000003cu,
        /// <summary>F4 key.</summary>
        SDLK_F4 = 0x4000003du,
        /// <summary>F5 key.</summary>
        SDLK_F5 = 0x4000003eu,
        /// <summary>F6 key.</summary>
        SDLK_F6 = 0x4000003fu,
        /// <summary>F7 key.</summary>
        SDLK_F7 = 0x40000040u,
        /// <summary>F8 key.</summary>
        SDLK_F8 = 0x40000041u,
        /// <summary>F9 key.</summary>
        SDLK_F9 = 0x40000042u,
        /// <summary>F10 key.</summary>
        SDLK_F10 = 0x40000043u,
        /// <summary>F11 key.</summary>
        SDLK_F11 = 0x40000044u,
        /// <summary>F12 key.</summary>
        SDLK_F12 = 0x40000045u,

        /// <summary>Print Screen key.</summary>
        SDLK_PRINTSCREEN = 0x40000046u,
        /// <summary>Scroll Lock key.</summary>
        SDLK_SCROLLLOCK = 0x40000047u,
        /// <summary>Pause key.</summary>
        SDLK_PAUSE = 0x40000048u,
        /// <summary>Insert key.</summary>
        SDLK_INSERT = 0x40000049u,
        /// <summary>Home key.</summary>
        SDLK_HOME = 0x4000004au,
        /// <summary>Page Up key.</summary>
        SDLK_PAGEUP = 0x4000004bu,
        /// <summary>End key.</summary>
        SDLK_END = 0x4000004du,
        /// <summary>Page Down key.</summary>
        SDLK_PAGEDOWN = 0x4000004eu,
        /// <summary>Right arrow key.</summary>
        SDLK_RIGHT = 0x4000004fu,
        /// <summary>Left arrow key.</summary>
        SDLK_LEFT = 0x40000050u,
        /// <summary>Down arrow key.</summary>
        SDLK_DOWN = 0x40000051u,
        /// <summary>Up arrow key.</summary>
        SDLK_UP = 0x40000052u,

        // Keypad keys

        /// <summary>Num Lock / Clear key.</summary>
        SDLK_NUMLOCKCLEAR = 0x40000053u,
        /// <summary>Keypad divide key.</summary>
        SDLK_KP_DIVIDE = 0x40000054u,
        /// <summary>Keypad multiply key.</summary>
        SDLK_KP_MULTIPLY = 0x40000055u,
        /// <summary>Keypad minus key.</summary>
        SDLK_KP_MINUS = 0x40000056u,
        /// <summary>Keypad plus key.</summary>
        SDLK_KP_PLUS = 0x40000057u,
        /// <summary>Keypad enter key.</summary>
        SDLK_KP_ENTER = 0x40000058u,
        /// <summary>Keypad 1 key.</summary>
        SDLK_KP_1 = 0x40000059u,
        /// <summary>Keypad 2 key.</summary>
        SDLK_KP_2 = 0x4000005au,
        /// <summary>Keypad 3 key.</summary>
        SDLK_KP_3 = 0x4000005bu,
        /// <summary>Keypad 4 key.</summary>
        SDLK_KP_4 = 0x4000005cu,
        /// <summary>Keypad 5 key.</summary>
        SDLK_KP_5 = 0x4000005du,
        /// <summary>Keypad 6 key.</summary>
        SDLK_KP_6 = 0x4000005eu,
        /// <summary>Keypad 7 key.</summary>
        SDLK_KP_7 = 0x4000005fu,
        /// <summary>Keypad 8 key.</summary>
        SDLK_KP_8 = 0x40000060u,
        /// <summary>Keypad 9 key.</summary>
        SDLK_KP_9 = 0x40000061u,
        /// <summary>Keypad 0 key.</summary>
        SDLK_KP_0 = 0x40000062u,
        /// <summary>Keypad period key.</summary>
        SDLK_KP_PERIOD = 0x40000063u,

        // Application and power keys

        /// <summary>Application/Menu key.</summary>
        SDLK_APPLICATION = 0x40000065u,
        /// <summary>Power key.</summary>
        SDLK_POWER = 0x40000066u,
        /// <summary>Keypad equals key.</summary>
        SDLK_KP_EQUALS = 0x40000067u,

        // Extended function keys

        /// <summary>F13 key.</summary>
        SDLK_F13 = 0x40000068u,
        /// <summary>F14 key.</summary>
        SDLK_F14 = 0x40000069u,
        /// <summary>F15 key.</summary>
        SDLK_F15 = 0x4000006au,
        /// <summary>F16 key.</summary>
        SDLK_F16 = 0x4000006bu,
        /// <summary>F17 key.</summary>
        SDLK_F17 = 0x4000006cu,
        /// <summary>F18 key.</summary>
        SDLK_F18 = 0x4000006du,
        /// <summary>F19 key.</summary>
        SDLK_F19 = 0x4000006eu,
        /// <summary>F20 key.</summary>
        SDLK_F20 = 0x4000006fu,
        /// <summary>F21 key.</summary>
        SDLK_F21 = 0x40000070u,
        /// <summary>F22 key.</summary>
        SDLK_F22 = 0x40000071u,
        /// <summary>F23 key.</summary>
        SDLK_F23 = 0x40000072u,
        /// <summary>F24 key.</summary>
        SDLK_F24 = 0x40000073u,

        // System and editing keys

        /// <summary>Execute key.</summary>
        SDLK_EXECUTE = 0x40000074u,
        /// <summary>Help key.</summary>
        SDLK_HELP = 0x40000075u,
        /// <summary>Menu key.</summary>
        SDLK_MENU = 0x40000076u,
        /// <summary>Select key.</summary>
        SDLK_SELECT = 0x40000077u,
        /// <summary>Stop key.</summary>
        SDLK_STOP = 0x40000078u,
        /// <summary>Again/Redo key.</summary>
        SDLK_AGAIN = 0x40000079u,
        /// <summary>Undo key.</summary>
        SDLK_UNDO = 0x4000007au,
        /// <summary>Cut key.</summary>
        SDLK_CUT = 0x4000007bu,
        /// <summary>Copy key.</summary>
        SDLK_COPY = 0x4000007cu,
        /// <summary>Paste key.</summary>
        SDLK_PASTE = 0x4000007du,
        /// <summary>Find key.</summary>
        SDLK_FIND = 0x4000007eu,
        /// <summary>Mute key.</summary>
        SDLK_MUTE = 0x4000007fu,
        /// <summary>Volume Up key.</summary>
        SDLK_VOLUMEUP = 0x40000080u,
        /// <summary>Volume Down key.</summary>
        SDLK_VOLUMEDOWN = 0x40000081u,

        // Additional keypad keys

        /// <summary>Keypad comma key.</summary>
        SDLK_KP_COMMA = 0x40000085u,
        /// <summary>Keypad equals key (AS/400).</summary>
        SDLK_KP_EQUALSAS400 = 0x40000086u,

        // System keys

        /// <summary>Alt Erase key.</summary>
        SDLK_ALTERASE = 0x40000099u,
        /// <summary>SysReq key.</summary>
        SDLK_SYSREQ = 0x4000009au,
        /// <summary>Cancel key.</summary>
        SDLK_CANCEL = 0x4000009bu,
        /// <summary>Clear key.</summary>
        SDLK_CLEAR = 0x4000009cu,
        /// <summary>Prior key.</summary>
        SDLK_PRIOR = 0x4000009du,
        /// <summary>Return2 key.</summary>
        SDLK_RETURN2 = 0x4000009eu,
        /// <summary>Separator key.</summary>
        SDLK_SEPARATOR = 0x4000009fu,
        /// <summary>Out key.</summary>
        SDLK_OUT = 0x400000a0u,
        /// <summary>Oper key.</summary>
        SDLK_OPER = 0x400000a1u,
        /// <summary>Clear Again key.</summary>
        SDLK_CLEARAGAIN = 0x400000a2u,
        /// <summary>CrSel key.</summary>
        SDLK_CRSEL = 0x400000a3u,
        /// <summary>ExSel key.</summary>
        SDLK_EXSEL = 0x400000a4u,

        // Extended keypad keys

        /// <summary>Keypad 00 key.</summary>
        SDLK_KP_00 = 0x400000b0u,
        /// <summary>Keypad 000 key.</summary>
        SDLK_KP_000 = 0x400000b1u,
        /// <summary>Thousands separator key.</summary>
        SDLK_THOUSANDSSEPARATOR = 0x400000b2u,
        /// <summary>Decimal separator key.</summary>
        SDLK_DECIMALSEPARATOR = 0x400000b3u,
        /// <summary>Currency unit key.</summary>
        SDLK_CURRENCYUNIT = 0x400000b4u,
        /// <summary>Currency subunit key.</summary>
        SDLK_CURRENCYSUBUNIT = 0x400000b5u,
        /// <summary>Keypad left parenthesis key.</summary>
        SDLK_KP_LEFTPAREN = 0x400000b6u,
        /// <summary>Keypad right parenthesis key.</summary>
        SDLK_KP_RIGHTPAREN = 0x400000b7u,
        /// <summary>Keypad left brace key.</summary>
        SDLK_KP_LEFTBRACE = 0x400000b8u,
        /// <summary>Keypad right brace key.</summary>
        SDLK_KP_RIGHTBRACE = 0x400000b9u,
        /// <summary>Keypad tab key.</summary>
        SDLK_KP_TAB = 0x400000bau,
        /// <summary>Keypad backspace key.</summary>
        SDLK_KP_BACKSPACE = 0x400000bbu,
        /// <summary>Keypad A key.</summary>
        SDLK_KP_A = 0x400000bcu,
        /// <summary>Keypad B key.</summary>
        SDLK_KP_B = 0x400000bdu,
        /// <summary>Keypad C key.</summary>
        SDLK_KP_C = 0x400000beu,
        /// <summary>Keypad D key.</summary>
        SDLK_KP_D = 0x400000bfu,
        /// <summary>Keypad E key.</summary>
        SDLK_KP_E = 0x400000c0u,
        /// <summary>Keypad F key.</summary>
        SDLK_KP_F = 0x400000c1u,
        /// <summary>Keypad XOR key.</summary>
        SDLK_KP_XOR = 0x400000c2u,
        /// <summary>Keypad power key.</summary>
        SDLK_KP_POWER = 0x400000c3u,
        /// <summary>Keypad percent key.</summary>
        SDLK_KP_PERCENT = 0x400000c4u,
        /// <summary>Keypad less than key.</summary>
        SDLK_KP_LESS = 0x400000c5u,
        /// <summary>Keypad greater than key.</summary>
        SDLK_KP_GREATER = 0x400000c6u,
        /// <summary>Keypad ampersand key.</summary>
        SDLK_KP_AMPERSAND = 0x400000c7u,
        /// <summary>Keypad double ampersand key.</summary>
        SDLK_KP_DBLAMPERSAND = 0x400000c8u,
        /// <summary>Keypad vertical bar key.</summary>
        SDLK_KP_VERTICALBAR = 0x400000c9u,
        /// <summary>Keypad double vertical bar key.</summary>
        SDLK_KP_DBLVERTICALBAR = 0x400000cau,
        /// <summary>Keypad colon key.</summary>
        SDLK_KP_COLON = 0x400000cbu,
        /// <summary>Keypad hash key.</summary>
        SDLK_KP_HASH = 0x400000ccu,
        /// <summary>Keypad space key.</summary>
        SDLK_KP_SPACE = 0x400000cdu,
        /// <summary>Keypad at key.</summary>
        SDLK_KP_AT = 0x400000ceu,
        /// <summary>Keypad exclamation key.</summary>
        SDLK_KP_EXCLAM = 0x400000cfu,
        /// <summary>Keypad memory store key.</summary>
        SDLK_KP_MEMSTORE = 0x400000d0u,
        /// <summary>Keypad memory recall key.</summary>
        SDLK_KP_MEMRECALL = 0x400000d1u,
        /// <summary>Keypad memory clear key.</summary>
        SDLK_KP_MEMCLEAR = 0x400000d2u,
        /// <summary>Keypad memory add key.</summary>
        SDLK_KP_MEMADD = 0x400000d3u,
        /// <summary>Keypad memory subtract key.</summary>
        SDLK_KP_MEMSUBTRACT = 0x400000d4u,
        /// <summary>Keypad memory multiply key.</summary>
        SDLK_KP_MEMMULTIPLY = 0x400000d5u,
        /// <summary>Keypad memory divide key.</summary>
        SDLK_KP_MEMDIVIDE = 0x400000d6u,
        /// <summary>Keypad plus/minus key.</summary>
        SDLK_KP_PLUSMINUS = 0x400000d7u,
        /// <summary>Keypad clear key.</summary>
        SDLK_KP_CLEAR = 0x400000d8u,
        /// <summary>Keypad clear entry key.</summary>
        SDLK_KP_CLEARENTRY = 0x400000d9u,
        /// <summary>Keypad binary key.</summary>
        SDLK_KP_BINARY = 0x400000dau,
        /// <summary>Keypad octal key.</summary>
        SDLK_KP_OCTAL = 0x400000dbu,
        /// <summary>Keypad decimal key.</summary>
        SDLK_KP_DECIMAL = 0x400000dcu,
        /// <summary>Keypad hexadecimal key.</summary>
        SDLK_KP_HEXADECIMAL = 0x400000ddu,

        // Modifier keys

        /// <summary>Left Control key.</summary>
        SDLK_LCTRL = 0x400000e0u,
        /// <summary>Left Shift key.</summary>
        SDLK_LSHIFT = 0x400000e1u,
        /// <summary>Left Alt key.</summary>
        SDLK_LALT = 0x400000e2u,
        /// <summary>Left GUI key (Windows key, Command key, etc.).</summary>
        SDLK_LGUI = 0x400000e3u,
        /// <summary>Right Control key.</summary>
        SDLK_RCTRL = 0x400000e4u,
        /// <summary>Right Shift key.</summary>
        SDLK_RSHIFT = 0x400000e5u,
        /// <summary>Right Alt key.</summary>
        SDLK_RALT = 0x400000e6u,
        /// <summary>Right GUI key (Windows key, Command key, etc.).</summary>
        SDLK_RGUI = 0x400000e7u,

        // Mode and power management keys

        /// <summary>Mode key.</summary>
        SDLK_MODE = 0x40000101u,
        /// <summary>Sleep key.</summary>
        SDLK_SLEEP = 0x40000102u,
        /// <summary>Wake key.</summary>
        SDLK_WAKE = 0x40000103u,

        // Media keys

        /// <summary>Channel increment key.</summary>
        SDLK_CHANNEL_INCREMENT = 0x40000104u,
        /// <summary>Channel decrement key.</summary>
        SDLK_CHANNEL_DECREMENT = 0x40000105u,
        /// <summary>Media play key.</summary>
        SDLK_MEDIA_PLAY = 0x40000106u,
        /// <summary>Media pause key.</summary>
        SDLK_MEDIA_PAUSE = 0x40000107u,
        /// <summary>Media record key.</summary>
        SDLK_MEDIA_RECORD = 0x40000108u,
        /// <summary>Media fast forward key.</summary>
        SDLK_MEDIA_FAST_FORWARD = 0x40000109u,
        /// <summary>Media rewind key.</summary>
        SDLK_MEDIA_REWIND = 0x4000010au,
        /// <summary>Media next track key.</summary>
        SDLK_MEDIA_NEXT_TRACK = 0x4000010bu,
        /// <summary>Media previous track key.</summary>
        SDLK_MEDIA_PREVIOUS_TRACK = 0x4000010cu,
        /// <summary>Media stop key.</summary>
        SDLK_MEDIA_STOP = 0x4000010du,
        /// <summary>Media eject key.</summary>
        SDLK_MEDIA_EJECT = 0x4000010eu,
        /// <summary>Media play/pause key.</summary>
        SDLK_MEDIA_PLAY_PAUSE = 0x4000010fu,
        /// <summary>Media select key.</summary>
        SDLK_MEDIA_SELECT = 0x40000110u,

        // Application control keys

        /// <summary>AC New key.</summary>
        SDLK_AC_NEW = 0x40000111u,
        /// <summary>AC Open key.</summary>
        SDLK_AC_OPEN = 0x40000112u,
        /// <summary>AC Close key.</summary>
        SDLK_AC_CLOSE = 0x40000113u,
        /// <summary>AC Exit key.</summary>
        SDLK_AC_EXIT = 0x40000114u,
        /// <summary>AC Save key.</summary>
        SDLK_AC_SAVE = 0x40000115u,
        /// <summary>AC Print key.</summary>
        SDLK_AC_PRINT = 0x40000116u,
        /// <summary>AC Properties key.</summary>
        SDLK_AC_PROPERTIES = 0x40000117u,
        /// <summary>AC Search key.</summary>
        SDLK_AC_SEARCH = 0x40000118u,
        /// <summary>AC Home key.</summary>
        SDLK_AC_HOME = 0x40000119u,
        /// <summary>AC Back key.</summary>
        SDLK_AC_BACK = 0x4000011au,
        /// <summary>AC Forward key.</summary>
        SDLK_AC_FORWARD = 0x4000011bu,
        /// <summary>AC Stop key.</summary>
        SDLK_AC_STOP = 0x4000011cu,
        /// <summary>AC Refresh key.</summary>
        SDLK_AC_REFRESH = 0x4000011du,
        /// <summary>AC Bookmarks key.</summary>
        SDLK_AC_BOOKMARKS = 0x4000011eu,

        // Mobile/phone keys

        /// <summary>Soft left key (mobile).</summary>
        SDLK_SOFTLEFT = 0x4000011fu,
        /// <summary>Soft right key (mobile).</summary>
        SDLK_SOFTRIGHT = 0x40000120u,
        /// <summary>Call key (mobile).</summary>
        SDLK_CALL = 0x40000121u,
        /// <summary>End call key (mobile).</summary>
        SDLK_ENDCALL = 0x40000122u,

        /// <summary>Mask for extended keys that don't map to a scancode or unicode code point.</summary>
        SDLK_EXTENDED_MASK = 1u << 29,

       /// <summary>Mask indicating the keycode is derived from a scancode.</summary>
       SDLK_SCANCODE_MASK = 1u << 30
}

/// <summary>
/// Valid key modifiers (possibly OR'd together).
/// </summary>
[Flags]
    public enum SDL_Keymod : ushort
    {
        /// <summary>No modifier is applicable.</summary>
        SDL_KMOD_NONE = 0x0000,
        /// <summary>The left Shift key is down.</summary>
        SDL_KMOD_LSHIFT = 0x0001,
        /// <summary>The right Shift key is down.</summary>
        SDL_KMOD_RSHIFT = 0x0002,
        /// <summary>The Level 5 Shift key is down.</summary>
        SDL_KMOD_LEVEL5 = 0x0004,
        /// <summary>The left Ctrl (Control) key is down.</summary>
        SDL_KMOD_LCTRL = 0x0040,
        /// <summary>The right Ctrl (Control) key is down.</summary>
        SDL_KMOD_RCTRL = 0x0080,
        /// <summary>The left Alt key is down.</summary>
        SDL_KMOD_LALT = 0x0100,
        /// <summary>The right Alt key is down.</summary>
        SDL_KMOD_RALT = 0x0200,
        /// <summary>The left GUI key (often the Windows key) is down.</summary>
        SDL_KMOD_LGUI = 0x0400,
        /// <summary>The right GUI key (often the Windows key) is down.</summary>
        SDL_KMOD_RGUI = 0x0800,
        /// <summary>The Num Lock key (may be located on an extended keypad) is down.</summary>
        SDL_KMOD_NUM = 0x1000,
        /// <summary>The Caps Lock key is down.</summary>
        SDL_KMOD_CAPS = 0x2000,
        /// <summary>The AltGr key is down.</summary>
        SDL_KMOD_MODE = 0x4000,
        /// <summary>The Scroll Lock key is down.</summary>
        SDL_KMOD_SCROLL = 0x8000,

        // Combined modifier constants

        /// <summary>Any Ctrl key is down (left or right).</summary>
        SDL_KMOD_CTRL = SDL_KMOD_LCTRL | SDL_KMOD_RCTRL,
        /// <summary>Any Shift key is down (left or right).</summary>
        SDL_KMOD_SHIFT = SDL_KMOD_LSHIFT | SDL_KMOD_RSHIFT,
        /// <summary>Any Alt key is down (left or right).</summary>
        SDL_KMOD_ALT = SDL_KMOD_LALT | SDL_KMOD_RALT,
        /// <summary>Any GUI key is down (left or right).</summary>
        SDL_KMOD_GUI = SDL_KMOD_LGUI | SDL_KMOD_RGUI
    }

    /// <summary>
    /// Converts a scancode to a keycode.
    /// </summary>
    /// <param name="scancode">The scancode to convert.</param>
    /// <returns>The corresponding keycode.</returns>
    public static SDL_Keycode SDL_SCANCODE_TO_KEYCODE(SDL_Scancode scancode)
    {
        return (SDL_Keycode)((uint)scancode | (uint)SDL_Keycode.SDLK_SCANCODE_MASK);
    }
}
