<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.0-preview.1</Version>
    <Authors>Paul Vick</Authors>
    <Company>Paul Vick</Company>
    <Description>Dear ImGui bindings for SdlSharp, using SDL3 GPU backend.</Description>
    <Copyright>Copyright 2019-2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/panopticoncentral/sdk-sharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SdlSharp/SdlSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImguiSharp.Redist" Version="0.1.0-preview.1" />
  </ItemGroup>

</Project>
