using System.Text;

namespace SdlSharp.ImGui.Generator;

/// <summary>
/// Helper class for writing formatted C# code.
/// </summary>
public sealed class CodeWriter
{
    private readonly StringBuilder _sb = new();
    private int _indentLevel;
    private const string IndentString = "    ";

    public void AppendLine()
    {
        _ = _sb.AppendLine();
    }

    public void AppendLine(string line)
    {
        if (string.IsNullOrEmpty(line))
        {
            _ = _sb.AppendLine();
            return;
        }

        for (var i = 0; i < _indentLevel; i++)
        {
            _ = _sb.Append(IndentString);
        }

        _ = _sb.AppendLine(line);
    }

    public void Append(string text)
    {
        _ = _sb.Append(text);
    }

    public void OpenBrace()
    {
        AppendLine("{");
        _indentLevel++;
    }

    public void CloseBrace(bool withSemicolon = false)
    {
        _indentLevel--;
        AppendLine(withSemicolon ? "};" : "}");
    }

    public void Indent()
    {
        _indentLevel++;
    }

    public void Unindent()
    {
        _indentLevel--;
    }

    public override string ToString()
    {
        return _sb.ToString();
    }

    /// <summary>
    /// Writes the standard file header.
    /// </summary>
    public void WriteFileHeader()
    {
        AppendLine("// <auto-generated>");
        AppendLine("// This file was generated by SdlSharp.ImGui.Generator");
        AppendLine("// Do not modify this file directly.");
        AppendLine("// </auto-generated>");
        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();
    }

    /// <summary>
    /// Writes a summary XML doc comment.
    /// </summary>
    public void WriteSummary(string? summary)
    {
        if (string.IsNullOrWhiteSpace(summary))
        {
            return;
        }

        // Clean up the comment
        summary = summary.Trim();
        if (summary.StartsWith("//"))
        {
            summary = summary[2..].Trim();
        }

        AppendLine("/// <summary>");
        AppendLine($"/// {EscapeXml(summary)}");
        AppendLine("/// </summary>");
    }

    /// <summary>
    /// Writes XML doc comments from the attached comment.
    /// </summary>
    public void WriteDocComment(Comments? comments)
    {
        if (comments == null)
        {
            return;
        }

        var lines = new List<string>();

        if (comments.Preceding != null)
        {
            foreach (var line in comments.Preceding)
            {
                var cleaned = CleanComment(line);
                if (!string.IsNullOrWhiteSpace(cleaned))
                {
                    lines.Add(cleaned);
                }
            }
        }

        if (!string.IsNullOrWhiteSpace(comments.Attached))
        {
            var cleaned = CleanComment(comments.Attached);
            if (!string.IsNullOrWhiteSpace(cleaned))
            {
                lines.Add(cleaned);
            }
        }

        if (lines.Count == 0)
        {
            return;
        }

        AppendLine("/// <summary>");
        foreach (var line in lines)
        {
            AppendLine($"/// {EscapeXml(line)}");
        }

        AppendLine("/// </summary>");
    }

    private static string CleanComment(string comment)
    {
        comment = comment.Trim();
        if (comment.StartsWith("//"))
        {
            comment = comment[2..].Trim();
        }

        return comment;
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}

/// <summary>
/// Utilities for converting C names to C# conventions.
/// </summary>
public static class NamingConventions
{
    /// <summary>
    /// Converts an ImGui enum name (ImGuiWindowFlags_) to C# style (ImGuiWindowFlags).
    /// </summary>
    public static string CleanEnumName(string name)
    {
        // Remove trailing underscore
        return name.EndsWith('_') ? name[..^1] : name;
    }

    /// <summary>
    /// Converts an enum element name to C# style.
    /// For example: ImGuiWindowFlags_NoTitleBar -> NoTitleBar
    /// </summary>
    public static string CleanEnumElementName(string enumName, string elementName)
    {
        var prefix = enumName;

        // Try with underscore
        if (elementName.StartsWith(prefix))
        {
            return elementName[prefix.Length..];
        }

        // Try without trailing underscore
        if (prefix.EndsWith('_'))
        {
            var prefixWithoutUnderscore = prefix[..^1];
            if (elementName.StartsWith(prefixWithoutUnderscore + "_"))
            {
                return elementName[(prefixWithoutUnderscore.Length + 1)..];
            }
        }

        return elementName;
    }

    /// <summary>
    /// Converts a field name to PascalCase.
    /// </summary>
    public static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        // Handle leading underscore (private field indicator)
        if (name.StartsWith('_'))
        {
            var rest = name[1..];
            if (rest.Length > 0)
            {
                return char.ToUpper(rest[0]) + rest[1..];
            }
        }

        // Simple PascalCase
        return char.ToUpper(name[0]) + name[1..];
    }

    /// <summary>
    /// Converts a parameter name to camelCase, avoiding C# keywords.
    /// </summary>
    public static string ToParameterName(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        // Convert to camelCase
        var result = char.ToLower(name[0]) + name[1..];

        // Check for C# keywords
        return IsKeyword(result) ? "@" + result : result;
    }

    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
        "char", "checked", "class", "const", "continue", "decimal", "default",
        "delegate", "do", "double", "else", "enum", "event", "explicit",
        "extern", "false", "finally", "fixed", "float", "for", "foreach",
        "goto", "if", "implicit", "in", "int", "interface", "internal",
        "is", "lock", "long", "namespace", "new", "null", "object",
        "operator", "out", "override", "params", "private", "protected",
        "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong",
        "unchecked", "unsafe", "ushort", "using", "virtual", "void",
        "volatile", "while"
    ];

    public static bool IsKeyword(string name)
    {
        return CSharpKeywords.Contains(name);
    }
}
