// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>Opaque handle to an internal ImGui ImDrawListSharedData structure.</summary>
/// <param name="value">The underlying native pointer.</param>
public readonly struct ImDrawListSharedData(nint value)
{
    /// <summary>The underlying native pointer.</summary>
    public readonly nint Value = value;

    /// <summary>Implicitly converts a ImDrawListSharedData to nint.</summary>
    /// <param name="handle">The ImDrawListSharedData to convert.</param>
    public static implicit operator nint(ImDrawListSharedData handle) => handle.Value;

    /// <summary>Implicitly converts a nint to ImDrawListSharedData.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImDrawListSharedData(nint value) => new(value);
}
