// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <param name="value">The underlying function pointer.</param>
public readonly unsafe struct ImDrawCallback(delegate* unmanaged[Cdecl]<ImDrawList*, ImDrawCmd*, void> value)
{
    /// <summary>The underlying function pointer.</summary>
    public readonly delegate* unmanaged[Cdecl]<ImDrawList*, ImDrawCmd*, void> Value = value;

    /// <summary>Implicitly converts a ImDrawCallback to its underlying function pointer.</summary>
    /// <param name="callback">The ImDrawCallback to convert.</param>
    public static implicit operator delegate* unmanaged[Cdecl]<ImDrawList*, ImDrawCmd*, void>(ImDrawCallback callback) => callback.Value;

    /// <summary>Implicitly converts a function pointer to ImDrawCallback.</summary>
    /// <param name="value">The function pointer to convert.</param>
    public static implicit operator ImDrawCallback(delegate* unmanaged[Cdecl]<ImDrawList*, ImDrawCmd*, void> value) => new(value);
}
