// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Split/Merge functions are used to split the draw list into different layers which can be drawn into out of order.
/// This is used by the Columns/Tables API, so items of each column can be batched together in a same draw call.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImDrawListSplitter
{
    /// <summary>
    /// Current channel number (0)
    /// </summary>
    public int Current;

    /// <summary>
    /// Number of active channels (1+)
    /// </summary>
    public int Count;

    /// <summary>
    /// Draw channels (not resized down so _Count might be &lt; Channels.Size)
    /// </summary>
    public ImVector_ImDrawChannel Channels;

    /// <summary>
    /// Do not clear Channels[] so our allocations are reused next frame
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawListSplitter_Clear")]
    public static partial void Clear(ImDrawListSplitter* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawListSplitter_ClearFreeMemory")]
    public static partial void ClearFreeMemory(ImDrawListSplitter* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawListSplitter_Split")]
    public static partial void Split(ImDrawListSplitter* self, ImDrawList* draw_list, int count);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawListSplitter_Merge")]
    public static partial void Merge(ImDrawListSplitter* self, ImDrawList* draw_list);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawListSplitter_SetCurrentChannel")]
    public static partial void SetCurrentChannel(ImDrawListSplitter* self, ImDrawList* draw_list, int channel_idx);

}
