// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Typically, 1 command = 1 GPU draw call (unless command is a callback)
/// - VtxOffset: When 'io.BackendFlags &amp; ImGuiBackendFlags_RendererHasVtxOffset' is enabled,
/// this fields allow us to render meshes larger than 64K vertices while keeping 16-bit indices.
/// Backends made for &lt;1.71. will typically ignore the VtxOffset fields.
/// - The ClipRect/TexRef/VtxOffset fields must be contiguous as we memcmp() them together (this is asserted for).
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImDrawCmd
{
    /// <summary>
    /// 4*4  // Clipping rectangle (x1, y1, x2, y2). Subtract ImDrawData-&gt;DisplayPos to get clipping rectangle in "viewport" coordinates
    /// </summary>
    public ImVec4 ClipRect;

    /// <summary>
    /// 16   // Reference to a font/texture atlas (where backend called ImTextureData::SetTexID()) or to a user-provided texture ID (via e.g. ImGui::Image() calls). Both will lead to a ImTextureID value.
    /// </summary>
    public ImTextureRef TexRef;

    /// <summary>
    /// 4    // Start offset in vertex buffer. ImGuiBackendFlags_RendererHasVtxOffset: always 0, otherwise may be &gt;0 to support meshes larger than 64K vertices with 16-bit indices.
    /// </summary>
    public uint VtxOffset;

    /// <summary>
    /// 4    // Start offset in index buffer.
    /// </summary>
    public uint IdxOffset;

    /// <summary>
    /// 4    // Number of indices (multiple of 3) to be rendered as triangles. Vertices are stored in the callee ImDrawList's vtx_buffer[] array, indices in idx_buffer[].
    /// </summary>
    public uint ElemCount;

    /// <summary>
    /// 4-8  // If != NULL, call the function instead of rendering the vertices. clip_rect and texture_id will be set normally.
    /// </summary>
    public ImDrawCallback UserCallback;

    /// <summary>
    /// 4-8  // Callback user data (when UserCallback != NULL). If called AddCallback() with size == 0, this is a copy of the AddCallback() argument. If called AddCallback() with size &gt; 0, this is pointing to a buffer where data is stored.
    /// </summary>
    public nint UserCallbackData;

    /// <summary>
    /// 4 // Size of callback user data when using storage, otherwise 0.
    /// </summary>
    public int UserCallbackDataSize;

    /// <summary>
    /// Since 1.83: returns ImTextureID associated with this draw call. Warning: DO NOT assume this is always same as 'TextureId' (we will change this function for an upcoming feature)
    /// Since 1.92: removed ImDrawCmd::TextureId field, the getter function must be used!
    /// == (TexRef._TexData ? TexRef._TexData-&gt;TexID : TexRef._TexID)
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImDrawCmd_GetTexID")]
    public static partial ImTextureID GetTexID(ImDrawCmd* self);

}
