// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// A primary data type
/// </summary>
public enum ImGuiDataType
{
    S8 = 0, // signed char / char (with sensible compilers)
    U8 = 1, // unsigned char
    S16 = 2, // short
    U16 = 3, // unsigned short
    S32 = 4, // int
    U32 = 5, // unsigned int
    S64 = 6, // long long / __int64
    U64 = 7, // unsigned long long / unsigned __int64
    Float = 8, // float
    Double = 9, // double
    Bool = 10, // bool (provided for user convenience, not supported by scalar widgets)
    String = 11 // char* (provided for user convenience, not supported by scalar widgets)
}
