// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Flags for Shortcut(), SetNextItemShortcut(),
/// (and for upcoming extended versions of IsKeyPressed(), IsMouseClicked(), Shortcut(), SetKeyOwner(), SetItemKeyOwner() that are still in imgui_internal.h)
/// Don't mistake with ImGuiInputTextFlags! (which is for ImGui::InputText() function)
/// </summary>
[Flags]
public enum ImGuiInputFlags
{
    None = 0,
    Repeat = 1 << 0, // Enable repeat. Return true on successive repeats. Default for legacy IsKeyPressed(). NOT Default for legacy IsMouseClicked(). MUST BE == 1.
    RouteActive = 1 << 10, // Route to active item only.
    RouteFocused = 1 << 11, // Route to windows in the focus stack (DEFAULT). Deep-most focused window takes inputs. Active item takes inputs over deep-most focused window.
    RouteGlobal = 1 << 12, // Global route (unless a focused window or active item registered the route).
    RouteAlways = 1 << 13, // Do not register route, poll keys directly.
    RouteOverFocused = 1 << 14, // Option: global route: higher priority than focused route (unless active item in focused route).
    RouteOverActive = 1 << 15, // Option: global route: higher priority than active item. Unlikely you need to use that: will interfere with every active items, e.g. Ctrl+A registered by InputText will be overridden by this. May not be fully honored as user/internal code is likely to always assume they can access keys when active.
    RouteUnlessBgFocused = 1 << 16, // Option: global route: will not be applied if underlying background/void is focused (== no Dear ImGui windows are focused). Useful for overlay applications.
    RouteFromRootWindow = 1 << 17, // Option: route evaluated from the point of view of root window rather than current window.
    Tooltip = 1 << 18 // Automatically display a tooltip when hovering item [BETA] Unsure of right api (opt-in/opt-out)
}
