// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// -&gt; ImGuiKey | ImGuiMod_XXX    // Flags: for IsKeyChordPressed(), Shortcut() etc. an ImGuiKey optionally OR-ed with one or more ImGuiMod_XXX values.
/// </summary>
/// <param name="value">The underlying ImGuiKeyChord value.</param>
public readonly struct ImGuiKeyChord(int value)
{
    /// <summary>The underlying ImGuiKeyChord value.</summary>
    public readonly int Value = value;

    /// <summary>Implicitly converts a ImGuiKeyChord to int.</summary>
    /// <param name="id">The ImGuiKeyChord to convert.</param>
    public static implicit operator int(ImGuiKeyChord id) => id.Value;

    /// <summary>Implicitly converts a int to ImGuiKeyChord.</summary>
    /// <param name="value">The value to convert.</param>
    public static implicit operator ImGuiKeyChord(int value) => new(value);
}
