// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Sorting specification for one column of a table (sizeof == 12 bytes)
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImGuiTableColumnSortSpecs
{
    /// <summary>
    /// User id of the column (if specified by a TableSetupColumn() call)
    /// </summary>
    public ImGuiID ColumnUserID;

    /// <summary>
    /// Index of the column
    /// </summary>
    public short ColumnIndex;

    /// <summary>
    /// Index within parent ImGuiTableSortSpecs (always stored in order starting from 0, tables sorted on a single criteria will always have a 0 here)
    /// </summary>
    public short SortOrder;

    /// <summary>
    /// ImGuiSortDirection_Ascending or ImGuiSortDirection_Descending
    /// </summary>
    public ImGuiSortDirection SortDirection;
}
