// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Flags for ImGui::TreeNodeEx(), ImGui::CollapsingHeader*()
/// </summary>
[Flags]
public enum ImGuiTreeNodeFlags
{
    None = 0,
    Selected = 1 << 0, // Draw as selected
    Framed = 1 << 1, // Draw frame with background (e.g. for CollapsingHeader)
    AllowOverlap = 1 << 2, // Hit testing to allow subsequent widgets to overlap this one
    NoTreePushOnOpen = 1 << 3, // Don't do a TreePush() when open (e.g. for CollapsingHeader) = no extra indent nor pushing on ID stack
    NoAutoOpenOnLog = 1 << 4, // Don't automatically and temporarily open node when Logging is active (by default logging will automatically open tree nodes)
    DefaultOpen = 1 << 5, // Default node to be open
    OpenOnDoubleClick = 1 << 6, // Open on double-click instead of simple click (default for multi-select unless any _OpenOnXXX behavior is set explicitly). Both behaviors may be combined.
    OpenOnArrow = 1 << 7, // Open when clicking on the arrow part (default for multi-select unless any _OpenOnXXX behavior is set explicitly). Both behaviors may be combined.
    Leaf = 1 << 8, // No collapsing, no arrow (use as a convenience for leaf nodes).
    Bullet = 1 << 9, // Display a bullet instead of arrow. IMPORTANT: node can still be marked open/close if you don't set the _Leaf flag!
    FramePadding = 1 << 10, // Use FramePadding (even for an unframed text node) to vertically align text baseline to regular widget height. Equivalent to calling AlignTextToFramePadding() before the node.
    SpanAvailWidth = 1 << 11, // Extend hit box to the right-most edge, even if not framed. This is not the default in order to allow adding other items on the same line without using AllowOverlap mode.
    SpanFullWidth = 1 << 12, // Extend hit box to the left-most and right-most edges (cover the indent area).
    SpanLabelWidth = 1 << 13, // Narrow hit box + narrow hovering highlight, will only cover the label text.
    SpanAllColumns = 1 << 14, // Frame will span all columns of its container table (label will still fit in current column)
    LabelSpanAllColumns = 1 << 15, // Label will span all columns of its container table
    NavLeftJumpsToParent = 1 << 17, // Nav: left arrow moves back to parent. This is processed in TreePop() when there's an unfulfilled Left nav request remaining.
    CollapsingHeader = 26,
    DrawLinesNone = 1 << 18, // No lines drawn
    DrawLinesFull = 1 << 19, // Horizontal lines to child nodes. Vertical line drawn down to TreePop() position: cover full contents. Faster (for large trees).
    DrawLinesToNodes = 1 << 20, // Horizontal lines to child nodes. Vertical line drawn down to bottom-most child node. Slower (for large trees).
    NavLeftJumpsBackHere = 1 << 17, // Renamed in 1.92.0
    SpanTextWidth = 1 << 13 // Renamed in 1.90.7
}
