// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Flags stored in ImGuiViewport::Flags, giving indications to the platform backends.
/// </summary>
[Flags]
public enum ImGuiViewportFlags
{
    None = 0,
    IsPlatformWindow = 1 << 0, // Represent a Platform Window
    IsPlatformMonitor = 1 << 1, // Represent a Platform Monitor (unused yet)
    OwnedByApp = 1 << 2 // Platform Window: Is created/managed by the application (rather than a dear imgui backend)
}
