// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Helper: Parse and apply text filters. In format "aaaaa[,bbbb][,ccccc]"
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImGuiTextFilter
{
    public fixed byte InputBuf[256];

    public ImVector_ImGuiTextRange Filters;

    public int CountGrep;

    /// <summary>
    /// Helper calling InputText+Build
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiTextFilter_Draw")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool Draw(ImGuiTextFilter* self, [MarshalAs(UnmanagedType.LPUTF8Str)] string label, float width);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiTextFilter_PassFilter")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool PassFilter(ImGuiTextFilter* self, [MarshalAs(UnmanagedType.LPUTF8Str)] string text, [MarshalAs(UnmanagedType.LPUTF8Str)] string text_end);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiTextFilter_Build")]
    public static partial void Build(ImGuiTextFilter* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiTextFilter_Clear")]
    public static partial void Clear(ImGuiTextFilter* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImGuiTextFilter_IsActive")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool IsActive(ImGuiTextFilter* self);

}
