// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Specs and pixel storage for a texture used by Dear ImGui.
/// This is only useful for (1) core library and (2) backends. End-user/applications do not need to care about this.
/// Renderer Backends will create a GPU-side version of this.
/// Why does we store two identifiers: TexID and BackendUserData?
/// - ImTextureID    TexID           = lower-level identifier stored in ImDrawCmd. ImDrawCmd can refer to textures not created by the backend, and for which there's no ImTextureData.
/// - void*          BackendUserData = higher-level opaque storage for backend own book-keeping. Some backends may have enough with TexID and not need both.
/// In columns below: who reads/writes each fields? 'r'=read, 'w'=write, 'core'=main library, 'backend'=renderer backend
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ImTextureData
{
    /// <summary>
    /// ------------------------------------------ core / backend ---------------------------------------
    /// w    -   // [DEBUG] Sequential index to facilitate identifying a texture when debugging/printing. Unique per atlas.
    /// </summary>
    public int UniqueID;

    /// <summary>
    /// rw   rw  // ImTextureStatus_OK/_WantCreate/_WantUpdates/_WantDestroy. Always use SetStatus() to modify!
    /// </summary>
    public ImTextureStatus Status;

    /// <summary>
    /// -    rw  // Convenience storage for backend. Some backends may have enough with TexID.
    /// </summary>
    public nint BackendUserData;

    /// <summary>
    /// r    w   // Backend-specific texture identifier. Always use SetTexID() to modify! The identifier will stored in ImDrawCmd::GetTexID() and passed to backend's RenderDrawData function.
    /// </summary>
    public ImTextureID TexID;

    /// <summary>
    /// w    r   // ImTextureFormat_RGBA32 (default) or ImTextureFormat_Alpha8
    /// </summary>
    public ImTextureFormat Format;

    /// <summary>
    /// w    r   // Texture width
    /// </summary>
    public int Width;

    /// <summary>
    /// w    r   // Texture height
    /// </summary>
    public int Height;

    /// <summary>
    /// w    r   // 4 or 1
    /// </summary>
    public int BytesPerPixel;

    /// <summary>
    /// w    r   // Pointer to buffer holding 'Width*Height' pixels and 'Width*Height*BytesPerPixels' bytes.
    /// </summary>
    public byte* Pixels;

    /// <summary>
    /// w    r   // Bounding box encompassing all past and queued Updates[].
    /// </summary>
    public ImTextureRect UsedRect;

    /// <summary>
    /// w    r   // Bounding box encompassing all queued Updates[].
    /// </summary>
    public ImTextureRect UpdateRect;

    /// <summary>
    /// w    r   // Array of individual updates.
    /// </summary>
    public ImVector_ImTextureRect Updates;

    /// <summary>
    /// w    r   // In order to facilitate handling Status==WantDestroy in some backend: this is a count successive frames where the texture was not used. Always &gt;0 when Status==WantDestroy.
    /// </summary>
    public int UnusedFrames;

    /// <summary>
    /// w    r   // Number of contexts using this texture. Used during backend shutdown.
    /// </summary>
    public ushort RefCount;

    /// <summary>
    /// w    r   // Tell whether our texture data is known to use colors (rather than just white + alpha).
    /// </summary>
    public bool UseColors;

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_Create")]
    public static partial void Create(ImTextureData* self, ImTextureFormat format, int w, int h);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_DestroyPixels")]
    public static partial void DestroyPixels(ImTextureData* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_GetPixels")]
    public static partial nint GetPixels(ImTextureData* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_GetPixelsAt")]
    public static partial nint GetPixelsAt(ImTextureData* self, int x, int y);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_GetSizeInBytes")]
    public static partial int GetSizeInBytes(ImTextureData* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_GetPitch")]
    public static partial int GetPitch(ImTextureData* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_GetTexRef")]
    public static partial ImTextureRef GetTexRef(ImTextureData* self);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_GetTexID")]
    public static partial ImTextureID GetTexID(ImTextureData* self);

    /// <summary>
    /// Called by Renderer backend
    /// - Call SetTexID() and SetStatus() after honoring texture requests. Never modify TexID and Status directly!
    /// - A backend may decide to destroy a texture that we did not request to destroy, which is fine (e.g. freeing resources), but we immediately set the texture back in _WantCreate mode.
    /// </summary>
    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_SetTexID")]
    public static partial void SetTexID(ImTextureData* self, ImTextureID tex_id);

    [LibraryImport(Common.ImGuiNative, EntryPoint = "ImTextureData_SetStatus")]
    public static partial void SetStatus(ImTextureData* self, ImTextureStatus status);

}
