// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace SdlSharp.ImGui.Native;

/// <summary>
/// Coordinates of a rectangle within a texture.
/// When a texture is in ImTextureStatus_WantUpdates state, we provide a list of individual rectangles to copy to the graphics system.
/// You may use ImTextureData::Updates[] for the list, or ImTextureData::UpdateBox for a single bounding box.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct ImTextureRect
{
    /// <summary>
    /// Upper-left coordinates of rectangle to update
    /// </summary>
    public ushort X;

    /// <summary>
    /// Upper-left coordinates of rectangle to update
    /// </summary>
    public ushort Y;

    /// <summary>
    /// Size of rectangle to update (in pixels)
    /// </summary>
    public ushort W;

    /// <summary>
    /// Size of rectangle to update (in pixels)
    /// </summary>
    public ushort H;
}
