// <auto-generated>
// This file was generated by SdlSharp.ImGui.Generator
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;
using static Sdl3Sharp.Native.Gpu;

namespace SdlSharp.ImGui.Native.Backends;

/// <summary>
/// [BETA] Selected render state data shared with callbacks.
/// This is temporarily stored in GetPlatformIO().Renderer_RenderState during the ImGui_ImplSDLGPU3_RenderDrawData() call.
/// (Please open an issue if you feel you need access to more data)
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct GpuRenderState
{
    public SDL_GPUDevice* Device;

    /// <summary>
    /// Default sampler (bilinear filtering)
    /// </summary>
    public SDL_GPUSampler* SamplerDefault;

    /// <summary>
    /// Current sampler (may be changed by callback)
    /// </summary>
    public SDL_GPUSampler* SamplerCurrent;
}
